### ISSUE TITLE
M2 macbook pro support

### ISSUE THREAD

**Issue by BASIL-NELSON** [crystalidea/macs-fan-control#670] opened 2023-02-19 23:52 UTC
cpu temps not working on m2 macbook pro

![compressed](https://user-images.githubusercontent.com/99857734/219983022-d1eb0842-1628-48a1-b866-f2f6e8d405c2.jpeg)

**Comment by kleuter** [comment] 2023-02-20 08:25
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/664

**Closed by kleuter** 2023-02-20 08:25 UTC
