### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by mauricev** [crystalidea/macs-fan-control#76] opened 2018-07-13 22:03 UTC
MacsFanControl is using at least 4.4 % of the CPU in activity monitor. Sometimes, it spikes 16%. I'm on a Mac Pro. All it should be doing is setting the fan temperature. How can that require any CPU at all?

**Comment by kleuter** [comment] 2018-08-31 20:54
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/55

**Closed by kleuter** 2018-08-31 20:54 UTC
