### ISSUE TITLE
it does not work with imac 2019 (3.6 GHz 8코어 Intel Core i9)

### ISSUE THREAD

**Issue by christopherYae** [crystalidea/macs-fan-control#748] opened 2024-04-28 13:59 UTC
![스크린샷 2024-04-28 시간: 22 56 31](https://github.com/crystalidea/macs-fan-control/assets/168351130/49571bf7-39da-4490-8db5-93c06a1e3126)

actually fan is max when my mac is boot. i can not control fan speed with the macs fan contro.
do you have any idea i can control the fan speed.

(My mac os : 14.4.1(23E224))

**Comment by kleuter** [comment] 2024-06-10 16:07
Please try to reset SMC as described here:
https://support.apple.com/en-us/HT201295

**Comment by kleuter** [comment] 2024-06-11 13:09
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/748

**Closed by kleuter** 2024-06-11 13:09 UTC
