### ISSUE TITLE
Presets deleted when booting into Windows 10.

### ISSUE THREAD

**Issue by DaedalusEagle** [crystalidea/macs-fan-control#471] opened 2021-02-23 17:04 UTC
Greetings,

I have been experiencing an intermittent issue where my profiles and settings are deleted and reset upon rebooting into 
Windows. I am running Macs Fan Control on a clean install of Windows 10. I experienced this issue before I reset my Windows partition in bootcamp as well. The issue appears to occur at random and doesn't always manifest every time I reboot my computer. I am happy to supply further details if necessary and I appreciate the help in advance!

![Window](https://user-images.githubusercontent.com/79476397/108879224-0bb4a400-75cf-11eb-9219-c348cff2686f.png)

<details>
YOUR TECH INFO
Macs Fan Control 1.5.8.1 [Qt 5.13.2]
iMac20,2
CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz [8 cores]
Windows 10 x64

Fans:
Main-min{1200}curr{1198}max{2700}mode{2,TCXc,45,72}

SMC sensors:
TA0P () - 11.375, 11.375
TA0V () - 21.1719, 21.1719
TA0p (Ambient) - 31.375, 31.375
TC0E () - 200.43, 200.43
TC0F () - 202.094, 202.094
TC0J () - 1.66406, 1.66406
TC0P () - 39.0625, 39.0625
TC0T () - 255.957, 255.957
TC0c (CPU Core 1) - 41, 41
TC0p (CPU Proximity) - 39.0625, 39.0625
TC1c (CPU Core 2) - 41, 41
TC2c (CPU Core 3) - 42, 42
TC3c (CPU Core 4) - 40, 40
TC4c (CPU Core 5) - 42, 42
TC5c (CPU Core 6) - 41, 41
TC6c (CPU Core 7) - 41, 41
TC7c (CPU Core 8) - 40, 40
TC8c () - 129, 129
TC9c () - 129, 129
TCS0 () - 41, 41
TCXR () - 199.859, 199.859
TCXc (CPU PECI) - 43.8594, 43.8594
TCXr () - 199.859, 199.859
TG0D (GPU Diode) - 44, 44 [H]
TG0E () - 44.2852, 44.2852
TG0F () - 44.7734, 44.7734
TG0J () - 0.488281, 0.488281
TG0P () - 43.625, 43.625
TG0T () - 255.992, 255.992
TG0d () - 44, 44
TG0p (GPU Proximity) - 43.625, 43.625
TG0s () - 0, 0
TG1D () - 46, 46
TG1E () - 47.8516, 47.8516
TG1F () - 48.7344, 48.7344
TG1J () - 0.882813, 0.882813
TG1P () - 43.0625, 43.0625
TG1T () - 255.879, 255.879
TG1d () - 46, 46
TG1p (GPU Proximity 2) - 43.0625, 43.0625
TG1s () - 0, 0
TG2P () - 42.6875, 42.6875
TG2p () - 42.6875, 42.6875
TH0F () - 36.4219, 36.4219
TH0X () - 36.4766, 36.4766
TH0a () - 36.4766, 36.4766
TH0b () - 36.2344, 36.2344
TH0c () - 246, 246
TH0d () - 246, 246
TH0p () - 136, 136
TH0x () - 36.4766, 36.4766
TI0D () - 41.625, 41.625
TI0d () - 41.625, 41.625
TI2D () - 31.125, 31.125
TI2d () - 31.125, 31.125
TL0P () - 31.8125, 31.8125
TL0V () - 32.6133, 32.6133
TL0p (LCD Proximity) - 31.8125, 31.8125
TL1P () - 32.1875, 32.1875
TL1V () - 30.6484, 30.6484
TL1p (LCD Proximity 2) - 32.1875, 32.1875
TL1v () - 30.6406, 30.6406
TM0P () - 34.1875, 34.1875
TM0V () - 32.207, 32.207
TM0o () - 0, 0
TM0p (Memory Proximity) - 34.1875, 34.1875
TM1P () - 30.625, 30.625
TM1a () - 39.9922, 39.9922
TM1p () - 30.625, 30.625
TM2P () - 31.875, 31.875
TM2a () - 32.207, 32.207
TM2b () - 28.2695, 28.2695
TM2c () - 28.5977, 28.5977
TM2d () - 29.0781, 29.0781
TM2p () - 31.875, 31.875
TM3P () - 33.125, 33.125
TM3a () - 29.875, 29.875
TM3b () - 30.1172, 30.1172
TM3c () - 29.9961, 29.9961
TM3d () - 29.9961, 29.9961
TM3p () - 33.125, 33.125
TM4a () - 30.7617, 30.7617
TMXP () - 34.1875, 34.1875
TPCD (Platform Controller Hub Die) - 59, 59
TS0V () - 35.0742, 35.0742
TS0o () - 0, 0
Tb0P () - 43.5625, 43.5625
Tb0p () - 43.5625, 43.5625
Tm0P () - 36.4375, 36.4375
Tm0p () - 36.4375, 36.4375
Tm1P () - 33.1875, 33.1875
Tm1p () - 33.1875, 33.1875
Tm2P () - 44.0625, 44.0625
Tm2p () - 44.0625, 44.0625
Tm3P () - 33.875, 33.875
Tm3p () - 33.875, 33.875
Tm4P () - 44.0625, 44.0625
Tm4p () - 44.0625, 44.0625
Tp2F () - 30.7773, 30.7773
Tp2H () - 30.75, 30.75
Tp2h () - 30.75, 30.75

GPUs:
AMD Radeon Pro 5700 XT - 45

Disk drives:
APPLE SSD AP0512N - 34

Log:

[2021-02-23 11:54:31:789] [thread 608] [app.cpp#280] Macs Fan Control 1.5.8.1
[2021-02-23 11:54:31:789] [thread 608] [app.cpp#281] Windows 10 x64
[2021-02-23 11:54:31:789] [thread 608] [app.cpp#282] iMac20,2
[2021-02-23 11:54:31:789] [thread 608] [app.cpp#283] Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz [8 cores]
[2021-02-23 11:54:31:789] [thread 608] [app.cpp#284] Qt 5.13.2
[2021-02-23 11:54:31:810] [thread 608] [platform_win.cpp#34] PlatformWin::open trying MMIO
[2021-02-23 11:54:31:810] [thread 608] [platform_win_sys_mmio.cpp#155] Trying to open SMC using with PNP driver
[2021-02-23 11:54:31:817] [thread 608] [service.cpp#87] detectSmcFanKeySize KeyType flt 
[2021-02-23 11:54:31:817] [thread 608] [service.cpp#88] detectSmcFanKeySize KeyLen 4
[2021-02-23 11:54:32:065] [thread 9580] [fancontrol.cpp#179] initialLoadThread
[2021-02-23 11:54:32:065] [thread 9580] [fancontrol.cpp#125] QFanControl::loadFansFromSMC
[2021-02-23 11:54:32:071] [thread 9580] [fancontrol.cpp#131] Fans count - 1
[2021-02-23 11:54:32:071] [thread 9580] [fancontrol.cpp#148] Fan 0: Main
[2021-02-23 11:54:32:118] [thread 9580] [fancontrol.cpp#59] checkFansControlModeFromSMC
[2021-02-23 11:54:32:134] [thread 9580] [tempsensorprovider.cpp#47] TempSensorDisk::loadAvailableSensors
[2021-02-23 11:54:32:150] [thread 9580] [service.cpp#56] getSMCKeysCount: 2214723584 644
[2021-02-23 11:54:35:901] [thread 9580] [service.cpp#647] getTemperature - skipping sensor TC8c with value of 129.0
[2021-02-23 11:54:35:901] [thread 9580] [tempsensorsmc.cpp#305] FilterSupportedTempSensors - skipping sensor TC8c
[2021-02-23 11:54:35:916] [thread 9580] [service.cpp#647] getTemperature - skipping sensor TC9c with value of 129.0
[2021-02-23 11:54:35:916] [thread 9580] [tempsensorsmc.cpp#305] FilterSupportedTempSensors - skipping sensor TC9c
[2021-02-23 11:54:36:043] [thread 9580] [provider_win_amd_api.cpp#18] atiadlxx.dll loaded
[2021-02-23 11:54:36:078] [thread 9580] [provider_win_amd.cpp#91] ADL_Adapter_AdapterInfo_Get 8
[2021-02-23 11:54:36:078] [thread 9580] [provider_win_amd.cpp#121] Adapter[0]
	Adapter Index: 0
	UDID: PCI_VEN_1002&DEV_7319&SUBSYS_021B106B&REV_40_6&39763615&0&00000008A
	Location: PCI bus 3, device 0, function 0
	VendorID: 1002
	Adapter Name: AMD Radeon Pro 5700 XT
	Display Name: \\.\DISPLAY1
	Present: yes

[2021-02-23 11:54:36:078] [thread 9580] [provider_win_amd.cpp#126] 	Primary: yes
[2021-02-23 11:54:36:078] [thread 9580] [provider_win_amd.cpp#141] Can’t get Overdrive capabilities
[2021-02-23 11:54:36:078] [thread 9580] [provider_win_nvidia_api.cpp#37] LoadLibrary (nvapi.dll) failed with 127
[2021-02-23 11:54:36:078] [thread 9580] [tempsensorgpu.cpp#91] Discrete GPU: GPU AMD Radeon Pro 5700 XT, matching SMC - yes
[2021-02-23 11:54:36:078] [thread 9580] [tempsensordisk_win.cpp#293] Loading available SMART drives
[2021-02-23 11:54:36:078] [thread 9580] [tempsensordisk_win.cpp#304] GetLogicalDrives returned 58720276
[2021-02-23 11:54:36:078] [thread 9580] [tempsensordisk_win.cpp#314] Checking drive C:\
[2021-02-23 11:54:36:078] [thread 9580] [tempsensordisk_win.cpp#322] Drive is fixed
[2021-02-23 11:54:36:079] [thread 9580] [tempsensordisk_win.cpp#338] Phisical disk number: 0
[2021-02-23 11:54:36:079] [thread 9580] [tempsensordisk_win.cpp#387] Adding drive \\.\PHYSICALDRIVE0
[2021-02-23 11:54:36:079] [thread 9580] [tempsensordisk_win.cpp#394] Adding drive APPLE SSD AP0512N
[2021-02-23 11:54:36:079] [thread 9580] [tempsensordisk_win.cpp#314] Checking drive E:\
[2021-02-23 11:54:36:079] [thread 9580] [tempsensordisk_win.cpp#442] The drive is NOT fixed (2)
[2021-02-23 11:54:36:079] [thread 9580] [tempsensordisk_win.cpp#314] Checking drive X:\
[2021-02-23 11:54:36:079] [thread 9580] [tempsensordisk_win.cpp#322] Drive is fixed
[2021-02-23 11:54:36:081] [thread 9580] [tempsensordisk_win.cpp#338] Phisical disk number: 1
[2021-02-23 11:54:36:082] [thread 9580] [tempsensordisk_win.cpp#355] Skipping USB drive
[2021-02-23 11:54:36:082] [thread 9580] [tempsensordisk_win.cpp#314] Checking drive Y:\
[2021-02-23 11:54:36:082] [thread 9580] [tempsensordisk_win.cpp#322] Drive is fixed
[2021-02-23 11:54:36:085] [thread 9580] [tempsensordisk_win.cpp#338] Phisical disk number: 4
[2021-02-23 11:54:36:085] [thread 9580] [tempsensordisk_win.cpp#355] Skipping USB drive
[2021-02-23 11:54:36:085] [thread 9580] [tempsensordisk_win.cpp#314] Checking drive Z:\
[2021-02-23 11:54:36:085] [thread 9580] [tempsensordisk_win.cpp#322] Drive is fixed
[2021-02-23 11:54:36:091] [thread 9580] [tempsensordisk_win.cpp#338] Phisical disk number: 3
[2021-02-23 11:54:36:091] [thread 9580] [tempsensordisk_win.cpp#355] Skipping USB drive
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#65] TemperatureSensorSMC::loadAvailableSensors
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC0c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC1c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC2c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC3c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC4c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC5c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC6c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#32] Using TC7c sensor for CPU Core average
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#82] InitialLoadThread: number of supported SMC sensors: 19
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#83] InitialLoadThread: number of supported DISK sensors: 1
[2021-02-23 11:54:36:091] [thread 9580] [tempsensorprovider.cpp#84] InitialLoadThread: number of supported GPU sensors: 1
[2021-02-23 11:54:36:117] [thread 9580] [service.cpp#511] Set fan 0 mode 1
[2021-02-23 11:54:37:666] [thread 9600] [sensorcontrol.cpp#387] Main: Setting fan speed to 1200
[2021-02-23 11:54:37:682] [thread 9600] [service.cpp#511] Set fan 0 mode 1
[2021-02-23 11:54:37:697] [thread 9600] [service.cpp#335] setFanRPM 1200 for F0Tg
[2021-02-23 11:54:57:270] [thread 9600] [sensorcontrol.cpp#103] Main: HALF INCREASE ON
[2021-02-23 11:54:57:270] [thread 9600] [sensorcontrol.cpp#108] Main: Tendency is set to TendencyIncrease, Temperature 49, RPM=1200
[2021-02-23 11:54:57:270] [thread 9600] [sensorcontrol.cpp#387] Main: Setting fan speed to 1366
[2021-02-23 11:54:57:286] [thread 9600] [service.cpp#511] Set fan 0 mode 1
[2021-02-23 11:54:57:302] [thread 9600] [service.cpp#335] setFanRPM 1366 for F0Tg
[2021-02-23 11:54:58:805] [thread 9600] [sensorcontrol.cpp#153] Main: Temperature DECREASED to 47
[2021-02-23 11:54:58:805] [thread 9600] [sensorcontrol.cpp#177] Main: Ignoring temperature change
[2021-02-23 11:54:58:805] [thread 9600] [sensorcontrol.cpp#202] Main: Tendency is set to TendencyIncrease
[2021-02-23 11:54:58:805] [thread 9600] [sensorcontrol.cpp#387] Main: Setting fan speed to 1368
[2021-02-23 11:54:58:821] [thread 9600] [service.cpp#335] setFanRPM 1368 for F0Tg
[2021-02-23 11:55:00:330] [thread 9600] [sensorcontrol.cpp#153] Main: Temperature DECREASED to 45
[2021-02-23 11:55:00:330] [thread 9600] [sensorcontrol.cpp#177] Main: Ignoring temperature change
[2021-02-23 11:55:00:330] [thread 9600] [sensorcontrol.cpp#202] Main: Tendency is set to TendencyIncrease
[2021-02-23 11:55:00:330] [thread 9600] [sensorcontrol.cpp#387] Main: Setting fan speed to 1370
[2021-02-23 11:55:00:345] [thread 9600] [service.cpp#511] Set fan 0 mode 1
[2021-02-23 11:55:00:360] [thread 9600] [service.cpp#335] setFanRPM 1370 for F0Tg
[2021-02-23 11:55:01:862] [thread 9600] [sensorcontrol.cpp#153] Main: Temperature DECREASED to 45
[2021-02-23 11:55:01:862] [thread 9600] [sensorcontrol.cpp#177] Main: Ignoring temperature change
[2021-02-23 11:55:01:862] [thread 9600] [sensorcontrol.cpp#202] Main: Tendency is set to TendencyIncrease
[2021-02-23 11:55:01:862] [thread 9600] [sensorcontrol.cpp#387] Main: Setting fan speed to 1372
[2021-02-23 11:55:01:877] [thread 9600] [service.cpp#335] setFanRPM 1372 for F0Tg
[2021-02-23 11:55:03:390] [thread 9600] [sensorcontrol.cpp#387] Main: Setting fan speed to 1200
[2021-02-23 11:55:03:405] [thread 9600] [service.cpp#511] Set fan 0 mode 1
[2021-02-23 11:55:03:421] [thread 9600] [service.cpp#335] setFanRPM 1200 for F0Tg
[2021-02-23 11:55:17:043] [thread 608] [service.cpp#647] getTemperature - skipping sensor TC0E with value of 200.43
[2021-02-23 11:55:17:059] [thread 608] [service.cpp#647] getTemperature - skipping sensor TC0F with value of 202.094
[2021-02-23 11:55:17:105] [thread 608] [service.cpp#647] getTemperature - skipping sensor TC0T with value of 255.957
[2021-02-23 11:55:17:261] [thread 608] [service.cpp#647] getTemperature - skipping sensor TC8c with value of 129.0
[2021-02-23 11:55:17:277] [thread 608] [service.cpp#647] getTemperature - skipping sensor TC9c with value of 129.0
[2021-02-23 11:55:17:308] [thread 608] [service.cpp#647] getTemperature - skipping sensor TCXR with value of 199.859
[2021-02-23 11:55:17:339] [thread 608] [service.cpp#647] getTemperature - skipping sensor TCXr with value of 199.859
[2021-02-23 11:55:17:433] [thread 608] [service.cpp#647] getTemperature - skipping sensor TG0T with value of 255.992
[2021-02-23 11:55:17:480] [thread 608] [service.cpp#647] getTemperature - skipping sensor TG0s with value of 0.0
[2021-02-23 11:55:17:572] [thread 608] [service.cpp#647] getTemperature - skipping sensor TG1T with value of 255.879
[2021-02-23 11:55:17:619] [thread 608] [service.cpp#647] getTemperature - skipping sensor TG1s with value of 0.0
[2021-02-23 11:55:17:729] [thread 608] [service.cpp#647] getTemperature - skipping sensor TH0c with value of 246.0
[2021-02-23 11:55:17:745] [thread 608] [service.cpp#647] getTemperature - skipping sensor TH0d with value of 246.0
[2021-02-23 11:55:17:760] [thread 608] [service.cpp#647] getTemperature - skipping sensor TH0p with value of 136.0
[2021-02-23 11:55:17:996] [thread 608] [service.cpp#647] getTemperature - skipping sensor TM0o with value of 0.0
[2021-02-23 11:55:18:323] [thread 608] [service.cpp#647] getTemperature - skipping sensor TS0o with value of 0.0
Screenshot of the main window of Macs Fan Control is highly appreciated as well.
-->

**Comment by kleuter** [comment] 2021-04-05 12:09
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/389

**Closed by kleuter** 2021-04-05 12:09 UTC
Labels: bug
