### ISSUE TITLE
DAMAGE - DONE

### ISSUE THREAD

**Issue by teamplayerinstress** [crystalidea/macs-fan-control#103] opened 2018-09-10 17:11 UTC
ATTENTION: All Issue reports should please contain a screenshot and the system Diagnostics text, as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

This morning:
Someone startet our mac on our reception.
Then person has to go away and the imac startet alone...

So far so bad...

In the evening in came in and saw the overheated & crashed imac. the whole room smells like melting electronic. Totally damaged, cause the fans run wild when the update reminder window will not be closed & the imac starts to overheat.

This is a free software, but this software killed our imac and whole system.

I lost a lot of money...

I wrote a lot of mails to crystal idea... but no response.

I am angry, more than the silly birds !

**Comment by kleuter** [comment] 2018-09-10 17:58
Duplicate of #101

**Closed by kleuter** 2018-09-10 17:58 UTC
