### ISSUE TITLE
No fans detected

### ISSUE THREAD

**Issue by faziumba** [crystalidea/macs-fan-control#107] opened 2018-09-18 16:50 UTC
I have this issue and additionally if I quit the app my Mac suffers from continuous crashes in every app.

![schermata 2018-09-18 alle 18 40 51](https://user-images.githubusercontent.com/43384212/45703076-9e85c480-bb73-11e8-887a-625e954acf55.png)
![schermata 2018-09-18 alle 18 41 29](https://user-images.githubusercontent.com/43384212/45703082-a2b1e200-bb73-11e8-9d7f-e44414d07f9d.png)

Macs Fan Control 1.4.11
iMac13,1
CPU: Intel(R) Core(TM) i5-3335S CPU @ 2.70GHz [100]
GPU: Intel HD Graphics 4000 [active], NVIDIA GeForce GT 640M
macOS 10.13.6

Fans:
Main-min{0}curr{-1}max{0}mode{INVALID}

TempSensors:
TA0P () - 21.375, 21.375
TA0V () - 35.9102, 35.9102
TA0p () - 41.375, 41.375
TC0E () - 221.895, 221.895
TC0F () - 223.676, 223.676
TC0J () - 1.78125, 1.78125
TC0P () - 60.75, 60.75
TC0T () - 255.676, 255.676
TC0c () - 59, 59
TC0p () - 60.75, 60.75
TC1c () - 59, 59
TC2c () - 59, 59
TC3c () - 59, 59
TCGc () - 59, 59
TCSc () - 60, 60
TCXR () - 214.703, 214.703
TCXc () - 61.7031, 61.7031
TCXr () - 214.703, 214.703
TG0D () - 60, 60
TG0E () - 59.4023, 59.4023
TG0F () - 60.9375, 60.9375
TG0J () - 1.53516, 1.53516
TG0T () - 0.00390625, 0.00390625
TG0d () - 54, 54
TG0p () - 55, 55
TH0A () - 129, 129
TH0B () - 129, 129
TH0C () - 129, 129
TH0F () - 129, 129
TH0O () - 9, 9
TH0P () - 129, 129
TH0R () - 129, 129
TH0a () - 129, 129
TH0b () - 129, 129
TH0c () - 129, 129
TH1A () - 129, 129
TH1B () - 129, 129
TH1C () - 129, 129
TH1F () - 129, 129
TH1O () - 9, 9
TH1P () - 129, 129
TH1R () - 129, 129
TH1a () - 129, 129
TH1b () - 129, 129
TH1c () - 129, 129
TL0P () - 31.3594, 31.3594
TL0p () - 44.8125, 44.8125
TL1P () - 44.1875, 44.1875
TL1V () - 38.582, 38.582
TL1p () - 44.1875, 44.1875
TL1v () - 38.5703, 38.5703
TM0P () - 56.25, 56.25
TM0V () - 59.4297, 59.4297
TM0p () - 56.25, 56.25
TMXP () - 56.25, 56.25
TPCD () - 73, 73
TS0V () - 45.6523, 45.6523
Tb0P () - 59.25, 59.25
Tb0p () - 59.25, 59.25
Tm0P () - 55.6875, 55.6875
Tm0p () - 55.6875, 55.6875
Tp2F () - 52.082, 52.082
Tp2H () - 52.125, 52.125
Tp2h () - 52.125, 52.125

Disk drives:

ATTENTION: All Issue reports should please contain a screenshot and the system Diagnostics text, as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/.github/CONTRIBUTING.md)

**Comment by os4834** [comment] 2018-09-20 01:18
reset the SMC on my iMac and now Macs Fan Control works as it always did, this issue is already reported in issue #15

**Comment by faziumba** [comment] 2018-09-20 07:53
Actually I already did reset SMC with no result. I used method suggested by Apple, just unplugged power cord for 15 seconds. Please also notice I am using a clean install os Mac OS. Any other suggestions?

**Comment by os4834** [comment] 2018-09-20 22:56
ummm.... did you reset the NVRAM(PRAM)? if not try this https://discussions.apple.com/docs/DOC-3603

**Comment by kleuter** [comment] 2018-09-24 18:11
It's duplicate of https://github.com/crystalidea/macs-fan-control/issues/15
Normally SMC reset helps.

**Closed by kleuter** 2018-09-24 18:12 UTC
