### ISSUE TITLE
Simply does not control fan speed at all

### ISSUE THREAD

**Issue by braxtonson** [crystalidea/macs-fan-control#715] opened 2023-10-31 12:00 UTC
This morning my computer started to blast the fan at full, so I downloaded this program. On my old Mac I used SMC fan control, and it worked great, and I know how to keep it at good operating temps.

However, this app simply does not seem to control my fan speed at all, and I have tried many settings including various low speeds of manual control. No matter what, it's well over 3300 rpm with 99F internal temp.

I gave the app accessibility permission in system settings (which doesn't seem required), restarted several times, nothing. Reset the SMC before doing any of this.

For what it's work, I downloaded TG Pro trial version, and it is similarly doing absolutely nothing.

Thanks for the help.

<details>
My "more" menu does not have "copy technical info"
Macs Fan Control 1.5.16 - Pro version
2020 IMac
Sonoma 14.1 (Also didn't work on 13.5 - upgraded to see if that was it)
3.8ghz 8-Core Intel i7

</details>
<img width="283" alt="Screenshot 2023-10-31 at 7 49 10 AM" src="https://github.com/crystalidea/macs-fan-control/assets/149487739/0b7df917-7846-4aed-a647-bf7ffa8accf6">

<img width="527" alt="Screenshot 2023-10-31 at 7 49 32 AM" src="https://github.com/crystalidea/macs-fan-control/assets/149487739/ddff4740-e07c-4ed6-9380-5be10bf42ba5">

<img width="488" alt="Screenshot 2023-10-31 at 7 59 17 AM" src="https://github.com/crystalidea/macs-fan-control/assets/149487739/3561fe71-e407-4b90-9bcb-d29160077694">

**Comment by braxtonson** [comment] 2023-10-31 20:09
To be fair, this could be another issue. Perhaps a faulty SMC

**Comment by kleuter** [comment] 2024-01-11 14:15
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by kleuter** [comment] 2024-11-20 16:57
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/785

**Closed by kleuter** 2024-11-20 16:57 UTC
Labels: need more info
