### ISSUE TITLE
High kernel_task CPU% on custom preset

### ISSUE THREAD

**Issue by Aazamandius** [crystalidea/macs-fan-control#313] opened 2020-04-14 18:15 UTC
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2,6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  Boot ROM Version:	1037.100.362.0.0 (iBridge: 17.16.14281.0.0,0)

Catalina

1. Set up a custom profile depended on CPU PECI
2. Make a load on the processor
3. Stop loading processor

Some time later (few minutes) a process called kernel_task begin to load mostly all cpu %
After closing "Macs fan control" in a few minutes all become normal

**Comment by kleuter** [comment] 2020-04-15 12:43
https://crystalidea.com/macs-fan-control/faq

Which means that your custom preset is not fine.

**Comment by Aazamandius** [comment] 2020-04-15 13:31
It starts from 50 Celcius and becomes max at 90 Celcius based on CPU PECI.  
Any suggestions?

**Comment by kleuter** [comment] 2020-05-14 11:32
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/332

**Closed by kleuter** 2020-05-14 11:32 UTC
