### ISSUE TITLE
Mac fan control no longer launching Error: Error initializing SMC interaction layer 

### ISSUE THREAD

**Issue by rexor400** [crystalidea/macs-fan-control#336] opened 2020-05-22 11:29 UTC
After several attempts to launch Mac fans control and uninstalling, re-installing, running as administrator I'm at a standstill. What would you recommend? 

[2020-05-22 13:23:32:646] [thread 30280] [g:\projects\macsfancontrol\app\app.cpp#270] Macs Fan Control 1.5.6
[2020-05-22 13:23:32:647] [thread 30280] [g:\projects\macsfancontrol\app\app.cpp#271] Windows 10 x64
[2020-05-22 13:23:32:647] [thread 30280] [g:\projects\macsfancontrol\app\app.cpp#272] MacPro5,1
[2020-05-22 13:23:32:647] [thread 30280] [g:\projects\macsfancontrol\app\app.cpp#273] Intel(R) Xeon(R) CPU X5670 @ 2.93GHz [6 cores]
[2020-05-22 13:23:32:647] [thread 30280] [g:\projects\macsfancontrol\app\app.cpp#274] Qt 5.13.2
[2020-05-22 13:23:32:647] [thread 30280] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#93] Using HAL
[2020-05-22 13:23:32:647] [thread 30280] [g:\projects\macsfancontrol\app\smc\platform_win_sys.cpp#86] ERROR: Failed to open standard port X (error 2), will try inpout32
[2020-05-22 13:23:32:647] [thread 30280] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#102] PlatformWin::open trying inpout32

**Comment by kleuter** [comment] 2020-05-28 16:56
Please try version 1.5.7 and post its log as well, thanks.

**Comment by gnawh** [comment] 2020-05-28 21:17
This was working fine before, but reinstalled bootcamp and it's no longer working.

```
[2020-05-28 14:15:39:395] [thread 10808] [g:\projects\macsfancontrol\app\app.cpp#269] Macs Fan Control 1.5.7
[2020-05-28 14:15:39:395] [thread 10808] [g:\projects\macsfancontrol\app\app.cpp#270] Windows 10 x64
[2020-05-28 14:15:39:395] [thread 10808] [g:\projects\macsfancontrol\app\app.cpp#271] MacBookPro16,1
[2020-05-28 14:15:39:395] [thread 10808] [g:\projects\macsfancontrol\app\app.cpp#272] Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz [8 cores]
[2020-05-28 14:15:39:395] [thread 10808] [g:\projects\macsfancontrol\app\app.cpp#273] Qt 5.13.2
[2020-05-28 14:15:39:424] [thread 10808] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#34] PlatformWin::open trying MMIO
[2020-05-28 14:15:39:424] [thread 10808] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#155] Trying to open SMC using with PNP driver
[2020-05-28 14:15:39:425] [thread 10808] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#82] ERROR: No interfaces found, driver doesn't seem to be not installed
[2020-05-28 14:15:39:425] [thread 10808] [g:\projects\macsfancontrol\app\smc\platform_win_sys_mmio.cpp#173] ERROR: Create file failed to open <no-interface>, error 0
```

**Comment by kleuter** [comment] 2020-05-29 07:20
This is a different problem. Please run AppleSMC.exe located in the program folder using /install option, e.g. 

AppleSMC.exe /install

**Comment by rexor400** [comment] 2020-05-29 09:21
The issue has been solved. Apparently a software called RIOT Vanguard was
deeming it as a fps hacking program.

**Comment by kleuter** [comment] 2020-05-29 10:15
@rexor400 
https://github.com/crystalidea/macs-fan-control/issues/325

**Comment by kleuter** [comment] 2020-06-02 20:47
Duplicate of #325

**Closed by kleuter** 2020-06-02 20:47 UTC
Labels: bug, need more info
