### ISSUE TITLE
Fancontrol does not start after update to 11.4

### ISSUE THREAD

**Issue by Fonliar** [crystalidea/macs-fan-control#527] opened 2021-07-13 20:09 UTC
After the install of 11.4 i am not able to start fan control. I downloaded it again and still not work. Apple M1 MacBook Pro. The fun fact on the M1 iMac ist runs after update to 11.4. 
Any ideas? 
Sorry for my bad english.

Cheers
Fonliar

**Comment by kleuter** [comment] 2021-07-20 13:36
Hi,

Duplicate of https://github.com/crystalidea/macs-fan-control/issues/500?

**Comment by kleuter** [comment] 2021-07-20 13:36
Duplicate of #500

**Closed by kleuter** 2021-07-20 13:36 UTC
Labels: bug
