### ISSUE TITLE
Initial thread crashed on MacBookPro15,1

### ISSUE THREAD

**Issue by AndyRugg** [crystalidea/macs-fan-control#677] opened 2023-03-20 17:52 UTC
![screen](https://user-images.githubusercontent.com/127977549/226425254-0659a5b7-363c-4f9f-a1ca-20b4d5c45039.png)

**Comment by AndyRugg** [comment] 2023-03-20 17:54
![Screen Shot 2023-03-20 at 10 24 18 AM](https://user-images.githubusercontent.com/127977549/226425644-775a1fab-8a46-49ac-9835-286b9a7e519e.png)
 
Macs fan control keeps crashing continuously.

**Comment by kleuter** [comment] 2023-03-21 08:10
Does it happen every time? 

Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by AndyRugg** [comment] 2023-03-22 15:48
It happened again today, in fact the app is not running at all right now.

**Comment by kleuter** [comment] 2023-03-30 07:35
I believe it was cause by the GPU discovery method we currently use. 
I removed it just to test, please let us know if it works for you.
Here's the test build:
[macsfancontrol.zip](https://github.com/crystalidea/macs-fan-control/files/11109012/macsfancontrol.zip)

**Comment by kleuter** [comment] 2023-06-19 22:16
We received the second crash report that happens on the same machine (MacBookPro15,1), currently - no fix 😢 unfortunately. If it happens for you again, please send us the crash log:

https://crystalidea.com/help/locating-mac-app-crash-logs

**Comment by kleuter** [comment] 2024-02-03 15:34
Duplicate of #677

**Comment by kleuter** [comment] 2024-02-03 15:39
Duplicate of #736

**Closed by kleuter** 2024-02-03 15:39 UTC
Labels: bug, Top priority
