### ISSUE TITLE
auto dark mode support

### ISSUE THREAD

**Issue by zhkong** [crystalidea/macs-fan-control#210] opened 2019-09-12 13:42 UTC
machine: 2019 macbook pro 15.4
OS: macOS Catalina 

![截屏2019-09-12下午9.38.28.png](https://i.loli.net/2019/09/12/Iq6HvxRFEcjCs5U.png)
when I choose the auto dark mode on macOS ,the color of Macs-fan-control can not change status bar color on the top, so I can not see anything about the infomations

**Comment by kleuter** [comment] 2019-09-22 20:24
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/189

**Closed by kleuter** 2019-09-22 20:24 UTC
