### ISSUE TITLE
Error -60006

### ISSUE THREAD

**Issue by Alejandrovt1** [crystalidea/macs-fan-control#392] opened 2020-09-06 01:44 UTC
YOUR TECH INFO I have been a Mac Fan Control user for many yeras, but yesterday I gave my macbook to a friend and when he returned to me, the app start to show me that they need to install a help tool to control the fan and they asked me for my password, when I write and I started to configure it the preferences, the app doesnt active the fan or it crashed, please help!

**Comment by kleuter** [comment] 2020-09-08 13:04
Duplicate of #391

**Closed by kleuter** 2020-09-08 13:04 UTC
