### ISSUE TITLE
Capability of disabling one of the fan

### ISSUE THREAD

**Issue by yitonggese** [crystalidea/macs-fan-control#635] opened 2022-08-03 05:11 UTC
I'm using the M1 pro MacBook pro.
Is it possible to disable one of the fan? Since one of my fan is malfunctioning, when it is on, it is making an annoying noise. I want to set the speed of it to constantly 0rpm.

**Comment by Huckies** [comment] 2022-08-19 02:42
I want this feature too, so I can keep my computer in the shield when not handling heavy works.

**Comment by kleuter** [comment] 2023-06-21 09:02
Duplicate of #582, to be implemented very soon

**Closed by kleuter** 2023-06-21 09:02 UTC
Labels: feature request
