### ISSUE TITLE
Macbook Pro - Add ability to add multiple sensor-based values for fan speed curve

### ISSUE THREAD

**Issue by mau5atron** [crystalidea/macs-fan-control#266] opened 2020-01-16 23:30 UTC
It would be cool if there was an option for adding multiple sensor-based values.
For example, I would like to keep track of both CPU PECI && GPU PECI sensors and set a threshold such that if either the CPU or GPU go over a certain temperature (lets say 40C) then my set fan curve starts.

Visual: sensor-based values - [CPU, GPU]  => [36C, 42C]
In the above visual, if the GPU goes above 40C (or vice versa the CPU) then my fan curve starts. 
Of course this would be set for separate fans in the current state of the app.

This would be a neat feature. Thank you!

**Comment by kleuter** [comment] 2020-01-18 16:55
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/3

**Closed by kleuter** 2020-01-18 16:55 UTC
Labels: feature request

**Comment by Trebuin** [comment] 2022-03-15 17:20
Yes, I would pay for this feature.  I can't use the product as either the GPU or the CPU is overheating depending on which I select.
