### ISSUE TITLE
Feature request: Profiles

### ISSUE THREAD

**Issue by FlytheFish** [crystalidea/macs-fan-control#69] opened 2018-06-11 17:18 UTC
Generally, I prefer sacrificing some silence if I know that my mac isn't quietly running at 88°C. 
Sometimes I switch back to the to the quieter automatic fan curve though, for example when I study in the library.
Every time I switch back to my preferred settings I have to reenter my values and from which temp sensor I wanna read. It would be nice to save be able to save those settings and create different profiles for different situations, like "home office" or "library".

// Thanks for a great app and giving me a little control back over my mac!

Macs Fan Control 1.4.10
MacBookPro8,2
CPU: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz [100]
GPU: Intel HD Graphics 3000, AMD Radeon HD 6490M
macOS 10.13.5

**Comment by kleuter** [comment] 2018-06-11 19:37
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/5

**Closed by kleuter** 2018-06-11 19:37 UTC
