### ISSUE TITLE
One-click switch between presets

### ISSUE THREAD

**Issue by silyevsk** [crystalidea/macs-fan-control#304] opened 2020-03-31 11:14 UTC
Currently it looks that the only way to apply custom preset is to go to the tray icon, then 'Preset - automatic', then select the preset, then click 'apply'.

It would be very useful to switch in one click, or even better with a configurable keyboard shortcut.

**Comment by zecanard** [comment] 2020-03-31 14:34
Similar to #281

**Comment by zecanard** [comment] 2020-04-01 05:33
My 2€: I don't see there being a need to Rename/Delete presets quickly from the Menu Bar item. A user would name or rename a preset once and be done with it, and I think Delete is a sufficiently dangerous action that requiring a bit of extra effort would be a good thing.

Do users often have many presets in place? It seems to me that as long as most users don’t have more than maybe 3 (for a total of 5 with the Auto and Full), we could just have all presets grouped together directly beneath "Show Macs Fan Control," with no separator between them. Maybe you'd want to group "Sensor Based" along with the presets as well.

So you'd have:
Show Macs Fan Control
———————————
Auto
Full
Preset 1
Preset 2
Preset 3
More ▶ (if more than 3 custom presets)
Sensor Based… (immediately opens the sensor/fan panel)
———————————
Preferences…
More ▶
———————————
Quit Macs Fan Control

**Comment by kleuter** [comment] 2020-06-16 13:18
Duplicate of #281

**Closed by kleuter** 2020-06-16 13:18 UTC
Labels: feature request
