### ISSUE TITLE
MFC cannot 'custom' access highest fan speed for CPU - MacOS

### ISSUE THREAD

**Issue by designguybrown** [crystalidea/macs-fan-control#659] opened 2022-12-23 12:35 UTC
![2022-12-23 07 29 49 am](https://user-images.githubusercontent.com/121296216/209336831-d51bda67-4bc6-4652-9b17-0b1272ddd1c5.jpg)
Only on 'CPU' fan, does MFC not acknowledge the actual max as shown in pic, and so cannot access it during 'custom'
MacOS10.12, iMac Pro < 2015

**Comment by kleuter** [comment] 2023-02-14 20:54
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by kleuter** [comment] 2023-02-14 20:54
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/464

**Closed by kleuter** 2023-02-14 20:54 UTC
Labels: bug
