### ISSUE TITLE
Change fan speed with keyboard shortcut

### ISSUE THREAD

**Issue by timothy20913** [crystalidea/macs-fan-control#372] opened 2020-07-24 11:48 UTC
Hello
this might already be a feature and if it is please let me know, but i think it would be useful if there was an option to set the fan speed with a keyboard shortcut. This would make it quicker than having to click on the menu bar icon

thank you for your consideration

**Comment by kleuter** [comment] 2020-07-26 21:08
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/348

**Closed by kleuter** 2020-07-26 21:08 UTC
Labels: feature request
