### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by niklas-246** [crystalidea/macs-fan-control#438] opened 2020-11-30 08:47 UTC

**Comment by niklas-246** [comment] 2020-11-30 08:48
<img width="811" alt="Bildschirmfoto 2020-11-30 um 09 45 51" src="https://user-images.githubusercontent.com/75244908/100587714-3acdb900-32f1-11eb-8c96-7733bf218a9e.png">
here the screenshot

**Comment by kleuter** [comment] 2020-11-30 10:38
Duplicate of #435

**Closed by kleuter** 2020-11-30 10:38 UTC
Labels: bug
