### ISSUE TITLE
Dual GPU mac pro sensor temps?

### ISSUE THREAD

**Issue by tonylasagna** [crystalidea/macs-fan-control#339] opened 2020-05-27 13:48 UTC
I'm not sure if this is a bug or a feature request, but I have two GPU's in my Mac Pro. Both are Apple branded MPX modules. Only the GPU that is in slot one will show up in the temperature sensors, even though both certainly have one. From the other apps I have also tried, this might just be an OS X limitation for displaying temps, which would be silly, but figured I'd point this out in case something can be done.

**Comment by kleuter** [comment] 2020-05-28 12:23
Hi, it's a duplicate of 
https://github.com/crystalidea/macs-fan-control/issues/209
Currently in progress

**Closed** 2020-05-28 12:23 UTC
Labels: feature request
