### ISSUE TITLE
No Fans detected on this computer.

### ISSUE THREAD

**Issue by iamxwilson** [crystalidea/macs-fan-control#90] opened 2018-08-21 14:55 UTC
Here are my specs

Macs Fan Control 1.4.10
MacBookAir7,2
CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz [100]
GPU: Intel HD Graphics 6000
macOS 10.12.6

Fans:

TempSensors:

Disk drives:
APPLE SSD SM0256G - 29

**Comment by kleuter** [comment] 2018-09-01 07:49
Duplicate of
https://github.com/crystalidea/macs-fan-control/issues/15

**Closed by kleuter** 2018-09-01 07:49 UTC
