### ISSUE TITLE
save preset

### ISSUE THREAD

**Issue by cyberdupont** [crystalidea/macs-fan-control#461] opened 2021-01-23 16:49 UTC
I am French and Mac user — is there possible to save preset in a file. I have 2 Macs on different houses and I bring the Main disk. Actually I cannot find the presets when I change machine. I have seen they are included in .plist file but it is not easy to change the plist item every time 
Thanks

**Comment by kleuter** [comment] 2021-01-25 21:29
It's a duplicate of https://github.com/crystalidea/macs-fan-control/issues/366

Currently, settings are saved to:
~/Library/Preferences/com.crystalidea.macsfancontrol.plist

**Closed by kleuter** 2021-01-25 21:29 UTC
Labels: feature request
