### ISSUE TITLE
Displaying temperature of RX 5500/5600/5700 XT and 6000X series via eGPU

### ISSUE THREAD

**Issue by pfk84** [crystalidea/macs-fan-control#410] opened 2020-10-07 08:36 UTC
If you could add support for this card as well it would be greatly appreciated! 👍 Thanks! :)

[output.txt](https://github.com/crystalidea/macs-fan-control/files/5339200/output.txt)
<img width="933" alt="Bildschirmfoto 2020-10-07 um 10 32 12" src="https://user-images.githubusercontent.com/18550587/95307410-e249e480-0888-11eb-8ea5-ae32054a7310.png">

**Comment by kleuter** [comment] 2020-10-07 14:53
Unfortunately, Apple driver doesn't give this information at the moment.
When you search "PerformanceStatistics" string inside ioreg output, you'll notice that it reports zero:
"Temperature(C)"=0

On Windows temperature display for these GPUs is supported though.

**Comment by kittonian** [comment] 2021-03-05 20:42
Is this the same issue running it natively (not eGPU) in Big Sur 11.2.2? Ever since I put a Sapphire Radeon 5700 XT in my Mac Pro 5,1 (about a year ago) Macs Fan Control has never shown me the temp. It's a bit of a problem because even though my machine has the pixlas mod, I am getting kernel panics (i.e. black screen and reboot out of nowhere) when performing certain tasks in Cinema 4D, and I'm trying to trouble-shoot.

**Comment by elasim** [comment] 2021-08-25 05:37
I'm facing same issue with 6900XT on eGPU enclosure.
perhaps there are same issue for 6800 and 6800XT which are they are announced the supports on BigSur.
If this come from amd driver, can we just report this to apple?

**Comment by kleuter** [comment] 2021-08-29 07:10
I personally don't think Apple cares about reporting temperature for 3rd party apps support, unfortunately.

**Comment by kleuter** [comment] 2022-06-14 15:40
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/608

**Closed by kleuter** 2022-06-14 15:40 UTC
Labels: enhancement, help wanted, eGPU
