### ISSUE TITLE
More optimal fan control.

### ISSUE THREAD

**Issue by Christopher-C-Robinson** [crystalidea/macs-fan-control#600] opened 2022-05-03 16:36 UTC
Hi, 

I just started using the Macs fan control application and realized that when you have a custom setting the fans never turn off when the temp is below the minimum temp setting. Can this be implemented? I feel it is not the best to keep the fan running all the time and can lead to some issues down the road. It would be ideal that the fans turn completely off if not needed rather than run at a low speed. 

Thanks!

**Comment by kleuter** [comment] 2022-05-04 07:54
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/582

**Closed by kleuter** 2022-05-04 07:54 UTC
Labels: feature request
