### ISSUE TITLE
I can't see CPU sensor on Temperature sensors list

### ISSUE THREAD

**Issue by Aquariurn** [crystalidea/macs-fan-control#753] opened 2024-05-23 07:34 UTC
I'm using 2023 Macbook Pro 14(M3 pro, 8 core CPU, 10 core GPU)
As you can see a sreenshot, I can't see CPU sensor on the sensors list.
<img width="933" alt="스크린샷 2024-05-23 오후 4 28 30" src="https://github.com/crystalidea/macs-fan-control/assets/98036736/e8d0bc9d-7a84-4668-9bc9-4a352cd70247">

**Comment by Aquariurn** [comment] 2024-05-23 07:39
[Mac15,6_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/15413344/Mac15.6_tech_info.zip)
This is my tech info and I'm using mac OS 14.5.

**Comment by JEMcats** [comment] 2024-09-30 01:15
Give this beta version a try [#721](https://github.com/crystalidea/macs-fan-control/issues/721)

**Comment by kleuter** [comment] 2024-11-22 10:43
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/716

**Closed by kleuter** 2024-11-22 10:43 UTC
Labels: bug
