### ISSUE TITLE
"Keep in Menu Bar"

### ISSUE THREAD

**Issue by stevek8** [crystalidea/macs-fan-control#495] opened 2021-04-20 16:18 UTC
I am doing narration for an audiobook and I need to turn Macsfan control off and on easily. When recording I need it off, to be as quiet as can be. Then I want to turn it back on, sometimes at full blast to cool things down before turning it off again, or back to sensor-based, or... It would be helpful if the program stayed active in the menubar so I wouldn't have to go into the finder to turn it back on.

**Comment by kleuter** [comment] 2021-04-21 13:43
I don't understand, the app does stays in the menu bar, doesn't it?
Switching between presets can be done from the menu bar menu.

**Comment by stevek8** [comment] 2021-04-21 14:31
I have been turning it off to make it quiet. I don’t have the paid version to save a reset that might be able to do something similar. Not sure if that’s possible or not. How many presets are possible?

**Comment by kleuter** [comment] 2022-05-04 21:18
Duplicate of #582 will be done soon

**Closed by kleuter** 2022-05-04 21:18 UTC
Labels: feature request
