### ISSUE TITLE
Memory leaks on Apple Silicon on Apple Silicon

### ISSUE THREAD

**Issue by fiwswe** [crystalidea/macs-fan-control#214] opened 2019-09-27 10:34 UTC
Macs Fan Control (MFC) is running for days and weeks at a time on my Mac mini server. I have noticed that it tends to accumulate a lot of memory over time. Quitting MFC and restarting it will restart the cycle.

The issue has existed with older versions of MFC as well. I had hoped that issue #185 would have fixed the memory problem. But while the number of Mach ports now seems stable, the memory leak persists.

For example:
After launch of MFC:
com.crystalidea.macsfancontrol.smcwrite: 644 KB, the app: 38.8 MB.
An hour later:
com.crystalidea.macsfancontrol.smcwrite: 644 KB, the app: 50.5 MB.
About 67:30 hours after launch:
com.crystalidea.macsfancontrol.smcwrite: 688 KB, the app: 1,010.1 MB.

During this time the configuration window was only open at the beginning (at most an hour or so). After that the machine was running without user interaction.

FWIW: I have not enabled fan related activities in iStat Menus so hopefully there should be no conflict.

<details>
Thanks for this tool and for supporting it!
 

Macs Fan Control 1.5.0 [Qt 5.13.1]
Macmini4,1
CPU: Intel(R) Core(TM)2 Duo CPU P8800 @ 2.66GHz [2 cores]
GPU: NVIDIA GeForce 320M
macOS 10.12.6

Fans:
Exhaust-min{1800}curr{5504}max{5500}mode{2,TC0D,37,47}

TempSensors:
TA0P (Ambient) - 29.875, 29.875
TC0D (CPU Diode) - 52.5, 52.5
TC0G () - 70, 70
TC0H (CPU Heatsink) - 44.875, 44.875
TC0P () - 44.1328, 44.1328
TC0p (CPU Proximity) - 44.375, 44.375
TCPG () - 73, 73
TH0G () - 60, 60
TH0P () - 29.5, 29.5
TH0p () - 29.5, 29.5
TM0G () - 75, 75
TM0P () - 45.75, 45.75
TM0p (Memory Proximity) - 45.75, 45.75
TN0D (MCP Diode) - 46.5, 46.5
TN0G () - 67, 67
TN0P () - 39.3711, 39.3711
TN0p (Northbridge Proximity) - 39.375, 39.375
TN1D () - 54, 54
TN1E () - 54, 54
TN1F () - 55.1914, 55.1914
TN1G () - 90, 90
TN1S () - 55.1914, 55.1914
TNPG () - 70, 70
TO0P () - 128, 128
TO0p () - 128, 128
TW0P (Airport Card) - 35.25, 35.25
Tm0P () - 38.625, 38.625
Tp0C (PSMI Supply AC/DC Supply 1) - 39.7031, 39.7031

Disk drives:
WDC WD10JFCX-68N6GN0 - 31
Samsung SSD 850 PRO 512GB - 35

Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

Potentially conflicted app: iStat Menus 6
/Library/Application Support/iStat Menus 6/bandwidth.db
/Library/Application Support/iStat Menus 6/cities.db
/Library/Application Support/iStat Menus 6/iStat Menus Status.app
/Library/Application Support/iStat Menus 6/iStat Menus Uninstaller.app
/Library/Application Support/iStat Menus 6/iStat Menus Updater.app
/Library/Application Support/iStat Menus 6/iStatMenusAgent.app
/Library/Application Support/iStat Menus 6/iStatMenusDaemon
/Library/Application Support/iStat Menus 6/iStatMenusFans
/Library/Application Support/iStat Menus 6/uptime.db
</details>

**Comment by kleuter** [comment] 2019-09-30 21:17
Issue located and fixed, thank you. Will be available in the upcoming update (1.5.1)

**Comment by fiwswe** [comment] 2019-09-30 21:27
Wow, that was fast. Thanks!

I'll let you know the results when the new version is out.

**Comment by kleuter** [comment] 2019-10-01 07:35
It's not the final 1.5.1, but you'd like you can [test](https://www.crystalidea.com/downloads/macsfancontrol_151.zip) the memory leak

**Comment by fiwswe** [comment] 2019-10-01 12:26
Thanks for letting me test this!

I have rebooted the Mac mini, quit the older (1.5.0.1) app, replaced it with the 1.5.1.2 (beta) app, launched the beta and…

- A few seconds after launch (after closing the main window) [2019.10.01 13:13:50]:
com.crystalidea.macsfancontrol.smcwrite: 668 KB, the app: **37.5 MB**. Mach ports: 27, 241 respectively.

- About 59 min. later [2019.10.01 14:12:50]:
com.crystalidea.macsfancontrol.smcwrite: 652 KB, the app: **53,2 MB**. Mach ports: 25, 253 respectively.

During this time I watched the memory for the app slow climb up. I did not interact with MFC at all during this time and mostly left the machine running without any interaction.

Neither the MFC settings nor anything else on the machine was (manually) modified since the original bug report.

Conclusion:

- Mach ports remain stable (the light increase during this time is probably just a fluctuation).
- The memory leak still exists (unfortunately).

Here are screen shots of Activity Monitor to illustrate the issue:
[2019.10.01 14:12:50]
<img width="954" alt="Bildschirmfoto 2019-10-01 um 13 13 50" src="https://user-images.githubusercontent.com/53953985/65961257-8028f900-e456-11e9-8216-7b0032f90750.png">
[2019.10.01 14:12:50]
<img width="946" alt="Bildschirmfoto 2019-10-01 um 14 12 50" src="https://user-images.githubusercontent.com/53953985/65961269-8919ca80-e456-11e9-9bcc-853bd1f95e1b.png">

And this is what the menu bar display is configured to be (in case that makes any difference):
<img width="78" alt="Bildschirmfoto 2019-10-01 um 14 14 10" src="https://user-images.githubusercontent.com/53953985/65961328-9e8ef480-e456-11e9-928a-a2ea8f8fc423.png">

**Comment by kleuter** [comment] 2019-10-01 14:51
I can confirm that, found only one memory leak, seem like there's another one. Will keep searching, thank you

**Comment by kleuter** [comment] 2019-10-05 16:31
Can you please try the [1.5.1 beta](https://github.com/crystalidea/macs-fan-control/issues/218)?

**Comment by fiwswe** [comment] 2019-10-05 17:00
Ok, I have started the test. I'll let you know shortly what the results are…

**Comment by fiwswe** [comment] 2019-10-05 17:59
Alright, it seems you are on the right track! The leak is getting smaller.

**Setup:**
I am running the 1.5.1.5 (beta, Sierra) version as my Mac mini uses macOS 10.12.6. Again nothing was changed manually on the machine from previous tests except for replacing MFC.

**Results:**
Here are the numbers (only for the app memory as all the other values seem normal):
- Very shortly after launch (after closing the main window): 34.9 MB
- ∆T: 00:08:44: 36.8 MB (ø leaks 3.71 KB/s for a total of 1.9 MB)
- ∆T: 00:17:51: 38.9 MB (ø leaks 3.82 KB/s for a total of 4.0 MB)
- ∆T: 00:27:57: 41.0 MB (ø leaks 3.72 KB/s for a total of 6.1 MB)
- ∆T: 00:47:29: 45,6 MB (ø leaks 3.85 KB/s for a total of 10.7 MB)
- ∆T: 00:59:53: 48,4 MB (ø leaks 3.85 KB/s for a total of 13.5 MB)

**For reference:**
The previously tested version 1.5.1.2 (beta) had leaked an average of 4.54 KB/s for a total of 15.7 MB after 59 min.. This went down to an average of 3.08 KB/s over 02:06:56:24 days for a total of 595.0 MB.

**Comment by kleuter** [comment] 2019-10-05 18:27
@fiwswe thank you very much for the feedback!

**Comment by fiwswe** [comment] 2019-10-07 23:19
Update:
After a runtime of 02:06:07:26 days the leak grew to 274.3 MB (ø1.44 KB/s).

That is considerably less than version 1.5.1.2 (beta) which leaked 595 MB (ø3.08 KB/s) after the comparable time of 02:06:56:24 days.

**Comment by kleuter** [comment] 2019-11-05 09:20
Please try the latest beta
https://github.com/crystalidea/macs-fan-control/issues/218

**Comment by fiwswe** [comment] 2019-11-05 11:09
Hi!

Same resting environment as before, only with the new version 1.5.1.5 beta, Sierra, you made available today:

• Very shortly after launch (after closing the main window): 36.1 MB
• ∆T: 01:22:00: 47.6 MB (ø leaks 2.39 KB/s for a total of  11.5 MB)

So while not perfect yet it looks like an ≈38% improvement on the memory leak issue. I'll keep it running and report more data later…

Thanks!

BTW: Not sure if this is an issue or not, but when quitting the app (using the menu command) the helper tool keeps running. I used Activity Monitor to quit the helper tool before running the new version.

**Comment by kleuter** [comment] 2019-11-06 07:40
Thank you, will keep searching.

> Not sure if this is an issue or not, but when quitting the app (using the menu command) the helper tool keeps running. I used Activity Monitor to quit the helper tool before running the new version.
It's totally normal.

**Comment by fiwswe** [comment] 2019-11-07 21:48
Here is the promised update:
• ∆T: 00:17:31:41: 174.9 MB (ø leaks 2.25 KB/s for a total of 138.8 MB)
• ∆T: 02:11:59:46: 253.8 MB (ø leaks 1.03 KB/s for a total of 217.7 MB)

**Comment by fiwswe** [comment] 2019-11-12 05:29
I have started testing version 1.5.1.6 (sierra) today. Here are the first results:

• Very shortly after launch (after closing the main window): 36.3 MB
• ∆T: 17:26:07: 179.6 MB (ø leaks 2.34 KB/s for a total of 143.3 MB)

This value seems to be slightly worse than the corresponding value from version 1.5.1.5 (beta, sierra dated Nov. 5th.). Although the difference is small enough to be considered a natural fluctuation.

**Comment by fiwswe** [comment] 2019-11-16 21:46
Update:
• ∆T: 00:23:33:23: 235.9 MB (ø leaks 2.41 KB/s for a total of 199.6 MB)
• ∆T: 05:09:45:53: 861.1 MB (ø leaks 1.81 KB/s for a total of 824.8 MB)

**Comment by kleuter** [comment] 2019-11-17 00:05
Thank you for the follow up, will keep digging!

**Comment by fiwswe** [comment] 2019-12-11 11:41
Final update for version 1.5.1.6 (sierra):
• ∆T: 09:09:45:40: 887.0 MB (ø leaks 1.07 KB/s for a total of 850.7 MB)
• ∆T: 11:14:25:08: 895.6 MB (ø leaks 0.88 KB/s for a total of 859.3 MB)
• ∆T: 29:20:55:23: 2,220 MB (ø leaks 0.87 KB/s for a total of 2,183.7 MB)

So clearly the average rate of the leaks goes down over time but given very long runtimes the accumulated leaks are still significant.


I have downloaded and installed version 1.5.3.9 and started testing:

• Very shortly after launch (after closing the main window): 36.9 MB
• ∆T: 00:27:28: 39.0 MB (ø leaks 1.28 KB/s for a total of 2.1 MB, lowest value for this runtime yet!)
• ∆T: 01:21:20: 43.4 MB (ø leaks 1.36 KB/s for a total of 6.5 MB, lowest value for this runtime yet!)
• ∆T: 02:44:21: 44.9 MB (ø leaks 0.83 KB/s for a total of 8.0 MB, lowest average value yet!)

Good work! Things seem to be improving on the memory leak front :-)

**Comment by kleuter** [comment] 2019-12-12 12:02
Thanks a lot for the follow up.

**Comment by grr** [comment] 2020-08-06 20:29
still leaking. version 1.5.7.20 is using 143MB and the `leaks` commands reports `1041271 leaks for 99961088 total leaked bytes`.

**Comment by zecanard** [comment] 2020-08-06 21:09
Hadn’t noticed this before. Macs Fan Control 1.5.8.21 Pro (iMac19,1).

```
Physical footprint:         1.1G
Physical footprint (peak):  1.1G
----

leaks Report Version: 4.0
Process 532: 14239605 nodes malloced for 1088844 KB
Process 532: 14100443 leaks for 1092767760 total leaked bytes.
```

<img width="1091" alt="Screenshot 2020-08-06 at 16 06 23" src="https://user-images.githubusercontent.com/25799849/89582998-312ebb80-d7ff-11ea-9125-4b1ec06dc75c.png">

**Comment by 1105420698** [comment] 2020-08-06 23:44
Just wonder what language is the app coded in, I understand memory leaks in the kernel since it's written in c and assembler.

**Comment by kleuter** [comment] 2020-08-30 21:09
I do need to know which settings are used. Sensor-based control? A screenshot of the app would be fine. Thanks.

**Comment by zecanard** [comment] 2020-08-30 21:25
At the time I was experiencing this issue, I was switching between the following two profiles.

<img width="821" alt="Screenshot 2020-08-30 at 16 21 07" src="https://user-images.githubusercontent.com/25799849/91669751-1c330880-eadd-11ea-83b3-f21146d4f321.png">
<img width="821" alt="Screenshot 2020-08-30 at 16 21 19" src="https://user-images.githubusercontent.com/25799849/91669754-1f2df900-eadd-11ea-8c48-13dced9d5e66.png">

Nowadays I stick to a single one and I have a scheduled job that automatically restarts Macs Fan Control, so I haven’t observed it. I will disable it and report back if I also encounter this issue using a single profile.

**Comment by kleuter** [comment] 2020-08-31 13:51
Please post the complete output of the **leaks** command. Thanks!

**Comment by zecanard** [comment] 2020-10-18 17:48
Sorry it’s taken so long. I’ve rebooted my computer more frequently lately, and Macs Fan Control wasn’t leaking memory even after several days. Weirdly enough, leaks has been reporting no leaks even when the app was taking 800+ MiB of memory at times. This time, it’s only sitting on 117 MiB.

<img width="1071" alt="Screenshot 2020-10-18 at 12 47 53" src="https://user-images.githubusercontent.com/25799849/96375715-32099500-1140-11eb-9cb0-3bef6ac16b24.png">
[leaks.txt.zip](https://github.com/crystalidea/macs-fan-control/files/5397913/leaks.txt.zip)

**Comment by kleuter** [comment] 2020-10-23 14:49
omg, thanks a lot, we found the leak! Will be fixing it asap

**Comment by kleuter** [comment] 2020-10-23 15:22
[Quick build ](https://crystalidea.com/downloads/macsfancontrol_dev.zip) with NSMutableParagraphStyle leak fixed.

**Comment by zecanard** [comment] 2020-10-23 18:45
Thanks a bunch! Will keep an eye on it.

**Comment by kleuter** [comment] 2022-05-30 10:35
please upload complete logs somewhere.

**Comment by fiwswe** [comment] 2022-06-03 23:47
While the leaks have decreased, thanks @kleuter, I have given up on getting them all fixed. I use this, launched once a day via user crontab:
```
#!/bin/bash
#
#	As a workaround for memory leaks in Macs Fan Control we restart the app on a schedule.
#

MFC_PROCESSNAME='Macs Fan Control'
#	NOTE: Modify the path if you put the app somwehre else:
MFC_APP='/Applications/Macs Fan Control.app'

/usr/bin/killall -u "$(/usr/bin/whoami)" -HUP "$MFC_PROCESSNAME"
if [ $? -eq 0 ];then
	/usr/bin/open "$MFC_APP"
fi

#
#	EOF.
#
```

(MFC 1.5.11 running on macOS 10.12.6 on an old 2010 Mac mini Server with a broken HD temp sensor connector, which can not be upgraded to a more modern OS.)

HTH
fiwswe

**Comment by Lewiscowles1986** [comment] 2023-05-06 16:02
Just rebooted MFC 1.5.15 for just this, was using nearly 1GB RAM; restarted it's <100MB

**Comment by kleuter** [comment] 2023-05-12 20:43
Please post the complete output of the **leaks** command in Terminal (when you experience leaks). Thanks!

**Comment by Lewiscowles1986** [comment] 2023-05-12 20:53
$ `leaks 500`

```
Process 500 is not debuggable. Due to security restrictions, leaks can only show or save contents of readonly memory of restricted processes.

Process:         Macs Fan Control [500]
Path:            /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control
Load Address:    0x102a10000
Identifier:      com.crystalidea.macsfancontrol
Version:         1.5.15 (55)
Code Type:       ARM64
Platform:        macOS
Parent Process:  ??? [1]

Date/Time:       2023-05-12 21:51:54.597 +0100
Launch Time:     2023-05-07 09:37:30.103 +0100
OS Version:      macOS 13.3.1 (22E261)
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         338.9M
Physical footprint (peak):  339.1M
Idle exit:                  untracked
----

leaks Report Version: 4.0
Process 500: 4476542 nodes malloced for 320638 KB
Process 500: 4424715 leaks for 318577936 total leaked bytes.
```

**Comment by Lewiscowles1986** [comment] 2023-05-12 20:57
After closing and restarting, I now have this

<img width="956" alt="Screenshot 2023-05-12 at 21 54 45" src="https://github.com/crystalidea/macs-fan-control/assets/2605791/812daf96-ad16-4d13-bf9c-2ba7b8875a8e">

Obviously PID is now different.

**Comment by Lewiscowles1986** [comment] 2023-05-13 06:04
Okay so it's more than doubled in 9 hours

<img width="956" alt="Screenshot 2023-05-13 at 07 02 25" src="https://github.com/crystalidea/macs-fan-control/assets/2605791/90f643af-0b8f-4b85-8cb9-3e363e9ae9f3">

Also trace (truncated again, as it's 80M and crashed my browser trying to add inline)

<details>
<summary>trace 88901 > log</summary>

```
Process:         Macs Fan Control [88901]
Path:            /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control
Load Address:    0x1008ec000
Identifier:      com.crystalidea.macsfancontrol
Version:         1.5.15 (55)
Code Type:       ARM64
Platform:        macOS
Parent Process:  ??? [1]

Date/Time:       2023-05-13 06:59:29.404 +0100
Launch Time:     2023-05-12 21:53:52.005 +0100
OS Version:      macOS 13.3.1 (22E261)
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         152.9M
Physical footprint (peak):  153.0M
Idle exit:                  untracked
----

leaks Report Version: 4.0
Process 88901: 1171912 nodes malloced for 87380 KB
Process 88901: 1121709 leaks for 80756816 total leaked bytes.

    1121709 (77.0M) << TOTAL >>
```

</details>

**Comment by Lewiscowles1986** [comment] 2023-05-13 06:05
[leaks-2022-05-13-0659.log.zip](https://github.com/crystalidea/macs-fan-control/files/11468982/leaks-2022-05-13-0659.log.zip)

**Comment by Lewiscowles1986** [comment] 2023-05-13 06:08
<img width="671" alt="Screenshot 2023-05-13 at 07 06 32" src="https://github.com/crystalidea/macs-fan-control/assets/2605791/0378f7df-6c23-4361-b55e-acf3c3e9c221">

<img width="671" alt="Screenshot 2023-05-13 at 07 06 56" src="https://github.com/crystalidea/macs-fan-control/assets/2605791/f439e771-45cf-4273-8573-7c78d5bd40c0">

<details>
<summary>Open Files and Ports</summary>

```
/
/Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control
/Applications/Macs Fan Control.app/Contents/Frameworks/QtMacExtras.framework/Versions/5/QtMacExtras
/Applications/Macs Fan Control.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
/Library/Preferences/Logging/.plist-cache.oM9kr99b
/System/Library/CoreServices/SystemVersion.bundle/en_GB.lproj/SystemVersion.strings
/Applications/Macs Fan Control.app/Contents/PlugIns/platforms/libqcocoa.dylib
/Applications/Macs Fan Control.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantDark.car
/Applications/Macs Fan Control.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
/Applications/Macs Fan Control.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
/Applications/Macs Fan Control.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
/private/var/db/timezone/tz/2023c.1.0/icutz/icutz44l.dat
/private/var/db/mds/messages/501/se_SecurityMessages
/Applications/Macs Fan Control.app/Contents/PlugIns/styles/libqmacstyle.dylib
/usr/lib/libobjc-trampolines.dylib
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Common.loctable
/Applications/Macs Fan Control.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
/usr/share/icu/icudt70l.dat
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAqua.car
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantDark.car
/System/Library/Extensions/NVMeSMARTLib.plugin/Contents/MacOS/NVMeSMARTLib
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/InputManager.loctable
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
/System/Library/Fonts/SFNS.ttf
/System/Library/Fonts/Menlo.ttc
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/MenuCommands.loctable
/System/Library/Fonts/Helvetica.ttc
/System/Library/PrivateFrameworks/SFSymbols.framework/Versions/A/Resources/CoreGlyphs.bundle/Contents/Resources/Assets.car
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLight.car
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLight.car
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/InfoPlist.loctable
/Library/Caches/com.apple.iconservices.store/415736E8-7021-3378-AE56-A1F600708C5E.isdata
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
/private/var/folders/7b/npjgl0711f154yjpn8g0f85m0000gn/C/com.apple.iconservices/store.index
/private/var/db/analyticsd/events.allowlist
/dev/null
/dev/null
/dev/null
/dev/urandom
->0xb1ec723cdbffdd7c
->0x776f5ed73414abf4
/private/var/folders/7b/npjgl0711f154yjpn8g0f85m0000gn/T/MACSFANCONTROL
->0xc94e7a8745425c8f
->0xc94e7a874542500f
/private/var/folders/7b/npjgl0711f154yjpn8g0f85m0000gn/T/MacsFanControl.log
->0x9b0c1540122463d
->0x61dded2aae0484ca
[ctl com.apple.netsrc id 8 unit 19]
->0xc94e7a8745429407
```

</details>

**Comment by kleuter** [comment] 2023-06-20 16:06
Issue located and fixed, thanks a lot, v1.5.16 beta will be published soon

**Comment by Lewiscowles1986** [comment] 2023-06-21 00:33
How cool. Thanks!

**Comment by kleuter** [comment] 2023-06-21 05:26
https://github.com/crystalidea/macs-fan-control/issues/693

**Comment by Lewiscowles1986** [comment] 2023-06-21 20:04
Beta is holding steady at 77MB RAM 👍

**Comment by kleuter** [comment] 2023-06-21 20:34
Perfect! Will try making making memory footprint even smaller.

**Comment by Lewiscowles1986** [comment] 2023-06-22 00:32
Honestly @kleuter I think <100mb is fine, live free 😂

**Closed** 2023-09-07 14:02 UTC
Labels: bug, Top priority, Done in beta, Apple Silicon
