### ISSUE TITLE
Temperature from eGPU card not being reported

### ISSUE THREAD

**Issue by 7ecapilot** [crystalidea/macs-fan-control#599] opened 2022-05-02 21:15 UTC
I have an eGPU (Mantiz Venus) that has an AMD Radeon RX 6600 XT installed. The eGPU is connected via Thunderbolt (eGPU TB3<--Apple TB3 to TB2 adapter-->Mac Pro 6,1 TB2 (port 6)). The GPU shows up in Macs Fan Control, but isn't reporting any temperature. See attachment.
![Screen Shot 2022-05-02 at 2 06 43 PM](https://user-images.githubusercontent.com/3740161/166328666-f08c68b9-3abe-4816-8a28-a77331ad0678.png)

I previously had an RX 580 in this same eGPU and that card reported temperature to Macs Fan Control. I'm not sure if there is something in the new video card that is incompatible, but I thought I would file a bug just in case.

**Comment by kleuter** [comment] 2022-05-04 20:56
Duplicate of #410

**Closed by kleuter** 2022-05-04 20:56 UTC
