### ISSUE TITLE
Macs Fan Control keeps crashing everytime I start my Mac.

### ISSUE THREAD

**Issue by iLandMac** [crystalidea/macs-fan-control#712] opened 2023-10-22 09:53 UTC
[MacPro5,1_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13062853/MacPro5.1_tech_info.zip)
[macsfancontrol.zip](https://github.com/crystalidea/macs-fan-control/files/13062861/macsfancontrol.zip)

Hi there!

I repaired my old Mac Pro 5,1 running Big Sur just fine, and installed Fan Control 3 days ago. It was also running great, and helped to reduce the heat of Core A and Northbridge Diode. Suddenly it crashed during booting the system. Everytime when the desktop opened, the fan control icon didn't show up in the task menu, as usual. And then the app crashed.

I hope you can help me. Thanks in advance.

**Comment by kleuter** [comment] 2024-02-03 15:39
Duplicate of #736

**Closed by kleuter** 2024-02-03 15:39 UTC
Labels: bug
