### ISSUE TITLE
No temperature for cMP 5,1 with RX6800

### ISSUE THREAD

**Issue by Daleyelama** [crystalidea/macs-fan-control#705] opened 2023-09-14 21:52 UTC
Hi there!
First: love your app. It's such a great and simple to use tool!
Changed from Vega 56 to RX6800 on my classic MacPro 5,1 with Monterey.
The Vega card showed the temperature.. the RX6800 does not.
Do you have any solution for that?

Here's what terminal shows:

macpro1@Pro-von-MacPro3 ~ % ioreg -l | grep '"PerformanceStatistics"' | sed -E "s/,/\\n/g;s/\"//g" | grep -E "(temp|power|Device Utilization|Fan|speed|GPU Activity)"
GPU Activity(%)=0
Fan Speed(%)=0
Device Utilization %=0
Fan Speed(RPM)=0

Thanks and best regards
Clemens

**Comment by kleuter** [comment] 2023-09-15 14:35
Duplicate of  https://github.com/crystalidea/macs-fan-control/issues/608

**Comment by kleuter** [comment] 2023-09-15 14:35
It's working in Ventura only unfortunatelly

**Closed by kleuter** 2023-09-15 14:35 UTC
Labels: eGPU
