### ISSUE TITLE
Fan control does not operate fans 

### ISSUE THREAD

**Issue by 9llawson** [crystalidea/macs-fan-control#778] opened 2024-09-24 20:54 UTC
Previous used fan control every day however since yesterday fan control does nothing other than present the value of 0. System hardware tested with both fans operational.

**Comment by VABorisov** [comment] 2024-09-24 21:14
dats true. i think cause sequoia

**Comment by 9llawson** [comment] 2024-09-25 13:34
100% since the update

**Comment by kleuter** [comment] 2024-09-25 13:36
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by jake765111** [comment] 2024-09-26 17:02
> Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

Kleuter, Do you think a workaround will be found for this issue?

**Comment by Slash25e** [comment] 2024-10-15 23:53
[MacBookPro20,2_tech_info.zip](https://github.com/user-attachments/files/17386976/MacBookPro20.2_tech_info.zip)

**Comment by kleuter** [comment] 2024-11-20 16:53
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/785

**Closed by kleuter** 2024-11-20 16:53 UTC
Labels: need more info
