### ISSUE TITLE
Multi-sensor fan control request

### ISSUE THREAD

**Issue by JohnD0406** [crystalidea/macs-fan-control#127] opened 2018-10-15 03:08 UTC
Feature request, for the next major version:

Please allow interactive sensor control.  My use-case example is I use the Northbridge temperature to control the INTAKE/EXHAUST fan speeds.  This works fine at idle, but when video encoding jumps all CPU's to 100%, the BOOST fans kick in accordingly.  BOOST-A (2010 Mac Pro) causes air to pass over the Northbridge heatsink, lowering the temperature, which causes Macs Fan Control to lower the INTAKE/EXHAUST speed, causing higher CPU temps, causing higher BOOST fan speeds, causing lower Northbridge temps - circle logic.

It would be nice to have dual sensor controls, where IF Northbridge is within X range, set fans to Y; AND IF CPU temps are with Z range, set fans to Y.

It was not a good design to have the Northbridge heatsink halfway under CPU-A, but that's what Apple did, causing this conundrum.

**Comment by kleuter** [comment] 2018-12-30 13:32
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/3

**Closed by kleuter** 2018-12-30 13:32 UTC
