### ISSUE TITLE
MacsFanControl for Linux Ubuntu .deb

### ISSUE THREAD

**Issue by juanpc2018** [crystalidea/macs-fan-control#518] opened 2021-06-09 02:53 UTC
fancontrol & lm_sensors
are too command line...

would be better a Linux version of MacsFanControl.

Linux has "the same problem" as OSX,
each version must be compiled for each version of OS.
very hard to make a Universal Compatible Installer for all OS versions.
example: 
4k Video downloader 4.15.1-1 works in 20.10 but Not 4.16.0-1

i´m using 20.10 Groovy Gorilla, but maybe i want to try another LTS.
some softwares i have require 16. LTS

similar to OSX versions:
OSX SnowLeopard 10.6
OSX Lion 10.7
OSX Mountain Lion 10.8
OSX Mavericks 10.9
OSX Yosemite 10.10
OSX El Capitan 10.11
OSX Sierra 10.12
OSX HighSierra 10.13 <--- Last OSX with 32-Bit Driver support.
OSX Mojave 10.14 
OSX Catalina 10.15 "improved Mojave" 100% 64-Bit.
OSX BigSur 11.x

in Linux..
8 and 10 was nice with old KDE v3,
Kubuntu Groovy Gorilla 20.10 has KDE v5
LTE = "Long Term Support" are versions of Linux that developers support more.

for Linux Kubuntu there was a nice software called KSensors but was never updated for KDE v4 nor v5
http://ksensors.sourceforge.net/

Now KSysGuard "System Monitor" allows to manually create a Tab with Sensors, but... Read Only.

i have:
Mac Mini 2014 Late, 
Mac Pro 5,1 2010

since OSX Mojave there is No Bootcamp,
since M1 there is No Windows.

No Windows8.1 for Newer Macs,
i don´t like W10, 
i´m Not gonna buy Windows10.
Win8,1 is superior.

but All Windows since 7, maybe XP too, have an anti-cloning feature that makes HDD drivers slow when cloned sector-by-sector with Clonezilla,
the only way to move Windows8.1 to a New hdd/sdd is with the Official Windows Restore USB,
moves Windows OK, asks to register again, but has another problem:
Windows8.1 installed for the 1st time in a Bios board, cannot be Moved to a New drive using an EFI Board.

OSX Sierra has a problem with mouse Scroll wheel, requires a 3rd party software to make mouse wheel work ok. 
= Too much troubles,
Linux = End of Story.

Kubuntu can look like Windows8.1 after a few tweaks.
Ubuntu looks like OSX, has a nice "Disks" benchmark tool, in Kubuntu requires to manually install the "gnome-disk-utility" package,
Xubuntu is another flavor with XFCE Desktop environment, Not KDE, Not Gnome, 
ESET NOD32 is a nice anti-virus for Linux, but installer requires to manually change properties to Executable,
etc...

**Comment by kleuter** [comment] 2021-06-14 06:59
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/425

**Closed by kleuter** 2021-06-14 06:59 UTC
Labels: feature request
