### ISSUE TITLE
Use more than one sensor

### ISSUE THREAD

**Issue by jds10011** [crystalidea/macs-fan-control#459] opened 2021-01-19 04:39 UTC
Sometimes my CPU gets too hot, and sometimes my SSD gets too hot -- it depends on the task.  If I set a threshold for the fans to kick on based on the CPU, I sometimes miss the SSD getting too hot, and if I set instead based on the SSD, I sometimes miss the CPU getting too hot.  I would love the ability to use both sensors -- essentially, to use both presets at once.  So, if the CPU passes a particular temp OR if the SSD passes another particular temp, turn the fans on/up.

**Comment by ecc521** [comment] 2021-01-19 05:07
Looks like a duplicate of #3. 

Other than that, it seems like an entirely logical feature. I was absolutely stunned that it didn't exist, although the reality is, the CPU is almost always the problem. Maybe the GPU if I'm running iMovie (crashes with eGPUs) and something else, but it's almost always a CPU turbo boost that sends the thing from 50C to 103C in 2 seconds, and moving the fans from "Apple Quiet" to "Max" means a 25% performance boost (due to less throttling).

**Comment by kleuter** [comment] 2021-01-30 11:29
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/3

**Closed by kleuter** 2021-01-30 11:29 UTC
