### ISSUE TITLE
On Windows 10 Pro the custom presets are not saved so are lost between restarts

### ISSUE THREAD

**Issue by percychris** [crystalidea/macs-fan-control#321] opened 2020-04-28 15:07 UTC
On Windows 10 Pro (Running on a iMac 27 Inch EMC 2390) The custom presets are not saved so are lost between restarts. 
After restart the fans return to Auto and the custom presets are lost.
These should be saved to disk and the last selected preset should be reenabled after restart.

**Comment by percychris** [comment] 2020-04-29 07:11
this is a Haox from me. The first few times after reboot these settings where lost but miraculously (Or maybe because the last time I did not choose a fixed RPM but controlled by) the last time it did remember my setting after reboot.
So that is good enough for me for now.

**Comment by NTraub01** [comment] 2020-04-29 15:19
Same thing happening here. Very frustrating as it takes a while to balance out all of the fans and have confidence that the software will keep my machine from melting down when doing 3D modeling.  Windows 10 Pro (Running on MacPro 5,1)  Please help or provide some sort of work around while fixing bug.  Thank you

**Comment by percychris** [comment] 2020-04-29 15:25
Yes on some reboots the settings are kept but most of the time they are lost. Its a bit random behaviour!

**Comment by kleuter** [comment] 2020-05-12 09:38
I'm working on it now, thank you, please stay tuned.

**Comment by kleuter** [comment] 2020-05-19 20:01
Damn, I reproduced it only once. Can you please help with reproducing the problem? 
Ideally, I need a way to reproduce it with 100% probability. Because of its random behavior, it's very difficult to fix it.

**Comment by percychris** [comment] 2020-05-20 08:25
Yes I know that that is a problem. Sometimes the settings gets lost, sometimes not and that is hard to solve.

On top of that I use it on an iMac which was reinstalled purely with Windows 10 Pro (not a trace of apples Linux mess-up left) and I had to install your app to tame the vents which otherwise would go full speed which made the iMac resemble an F18 on takeoff.

Where are you storing the settings (registry or in some dedicated file on the filesystem) how do you start your program (as service (Located in the registry under Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services) or as a normal program from the 

“Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run” Key or the 

or “Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run”

**Comment by kleuter** [comment] 2020-05-20 09:20
Please try this build for now, it can probably contain a fix:
https://crystalidea.com/downloads/macsfancontrol_setup_beta.exe

**Comment by percychris** [comment] 2020-05-20 10:00
I will try it as soon as possible.

Its for an iMac of a friend and due to lockdown restrictions its not so easy for me to get there.

On top of it he is an absolute computer analphabet so I cannot trust him with the installation of the application (as easy as it is, he barley knows how to start the PC)

I will let you know ASAP as I see the opportunity to go to him.

Meanwhile thanks already for your involvement

 

Yours sincerely,

 

Percy Christian

Dascottelei 150 B8

2100 Deurne (Antwerpen)

Belgium

TEL:    +32.3.366.45.66

GSM:  +32.484.904.589

mailto: info@percychris.be

mailto: percy@skynet.be

**Comment by kleuter** [comment] 2020-05-20 14:22
I've made an update to the beta build, so please make sure to use the latest:
https://crystalidea.com/downloads/macsfancontrol_setup_beta_2.exe

**Comment by percychris** [comment] 2020-05-20 15:39
This URL links ends in a 404

**Comment by kleuter** [comment] 2020-05-20 15:50
Fixed.

**Comment by percychris** [comment] 2020-05-20 15:52
Thanks,

I will try it out as soon as I can and let you know

**Comment by kleuter** [comment] 2020-05-28 16:41
Fixed in 1.5.7

**Closed by kleuter** 2020-05-28 16:41 UTC
Labels: In progress, Top priority, bug, v1.5.7

**Comment by percychris** [comment] 2020-05-29 06:11
Thanks a lot
