### ISSUE TITLE
Inpoutx64.sys needed to run Macsfancontrol, but vanguard always stop it.

### ISSUE THREAD

**Issue by Nxccraft** [crystalidea/macs-fan-control#370] opened 2020-07-16 11:36 UTC
Unless vanguard is not running, the error that it stopped something from loading is frustrating , and it didn't happen before resetting the mac

</[2020-07-16 14:34:22:844] [thread 7488] [g:\projects\macsfancontrol\app\app.cpp#269] Macs Fan Control 1.5.7
[2020-07-16 14:34:22:844] [thread 7488] [g:\projects\macsfancontrol\app\app.cpp#270] Windows 10 x64
[2020-07-16 14:34:22:844] [thread 7488] [g:\projects\macsfancontrol\app\app.cpp#271] iMac18,2
[2020-07-16 14:34:22:844] [thread 7488] [g:\projects\macsfancontrol\app\app.cpp#272] Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz [4 cores]
[2020-07-16 14:34:22:844] [thread 7488] [g:\projects\macsfancontrol\app\app.cpp#273] Qt 5.13.2
[2020-07-16 14:34:22:845] [thread 7488] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#93] Using HAL
[2020-07-16 14:34:22:845] [thread 7488] [g:\projects\macsfancontrol\app\smc\platform_win_sys.cpp#86] ERROR: Failed to open standard port X (error 2), will try inpout32
[2020-07-16 14:34:22:845] [thread 7488] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#102] PlatformWin::open trying inpout32
>

**Comment by kleuter** [comment] 2020-07-18 19:49
Duplicate of #325

**Closed by kleuter** 2020-07-18 19:49 UTC
Labels: bug
