### ISSUE TITLE
RPM maxed out, even after SMC reset

### ISSUE THREAD

**Issue by gWOLF3** [crystalidea/macs-fan-control#464] opened 2021-02-04 19:34 UTC
OS: MacOS Catalina 10.15.6
Hardware: Macbook Pro 2015 Retina

So my mac's fans for some reason just starting going full blast 100% of the time. I was happy to find this project, but cannot get it to work. I try setting constant speed, but the "current" speed of the fan never adjusts or changes. Am I missing some permission or other etc that I need to make this work properly? 

I have already ran a SMC reset, and confirmed that SMC did reset, however, this has not fixed the issue.

<img width="774" alt="Screen Shot 2021-02-04 at 1 27 12 PM" src="https://user-images.githubusercontent.com/34167140/106945640-abc48f00-66ed-11eb-86c8-303316500b5b.png">

**Comment by gWOLF3** [comment] 2021-02-04 21:12
Just wanted to also point out that all the temperature sensors appear to be in working order. Do you have any ideas or suggestions? My thought is that my macbook is forcing full fan speed because of some hardware issue, but I would have hoped that this program could override that. Anybody else similar experience or recommendations? 
![Screen Shot 2021-02-04 at 3 10 26 PM](https://user-images.githubusercontent.com/34167140/106955832-64dd9600-66fb-11eb-8697-5d569e56aec9.png)

**Comment by M0D87** [comment] 2021-02-06 11:31
Hey, I have exactly the same issue. A workaround would be really nice.

**Comment by kleuter** [comment] 2021-02-26 10:24
Is is 13" model? 
Please post tech info as described at #407

**Comment by JovanJaimes** [comment] 2021-05-08 18:36
Hi! I have the exact same problem. Constant RPMs around 7300, 13" model, temperature goes from 35º to maybe 55º (not really overheating). Heres my technical info. Any help would be appreciated

![Captura de Pantalla 2021-05-08 a la(s) 13 29 11](https://user-images.githubusercontent.com/83881926/117549854-56f12700-b002-11eb-902a-6414734dbe2e.png)

![Captura de Pantalla 2021-05-08 a la(s) 13 29 16](https://user-images.githubusercontent.com/83881926/117549868-6b352400-b002-11eb-93e0-034538264bb3.png)

**Comment by kleuter** [comment] 2021-05-12 08:19
Older report:
```
I am not sure what triggers this event, but several times now I have come home to my fans running full speed even though none of the sensor input warrants that behavior. I am unable to reduce the speed manually or "automatically" and the system must be reset for the fans to return back under control of the app.
App has work flawlessly for years, now having an issue. Not sure if it coincides with "Mac Fan Control" update for not.

Running on iMac (Mid 2011)
macOS High Sierra, V 10.13.6 (computer can not be updated higher eg, no 10.14)
```

**Comment by kleuter** [comment] 2021-05-12 08:20
One more similar report from a user

--------------------------------
> HDD sensor randomly shifts to max RPM even though it was set to activate at a temp range of 42-70.  HDD rarely climbs above 30.  When I restart my computer, it goes back to normal.  However, this is a persistent issue that requires frequent restarting of the computer. Technical details are below.
[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/4130812/tech_info.txt)

**Comment by kleuter** [comment] 2022-10-21 11:17
Another report
![4-fan speed wrong](https://user-images.githubusercontent.com/2600624/197183982-452adcab-298e-4b6b-a0b3-8dad35d6480f.png)

**Comment by kleuter** [comment] 2023-02-14 20:54
Another report

![image](https://user-images.githubusercontent.com/2600624/218860927-b4810818-6ec1-4fac-9265-d61ec201675c.png)

**Comment by kleuter** [comment] 2023-02-16 08:55
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/66

**Closed by kleuter** 2023-02-16 08:55 UTC
Labels: help wanted, need more info
