### ISSUE TITLE
Change minimum fan speed

### ISSUE THREAD

**Issue by jlehrer1** [crystalidea/macs-fan-control#364] opened 2020-07-05 01:29 UTC
On the new models, the fans often sit at 0, not 1200. This needs to be added in order to not risk damaging the new line of computers, as using the fans excessively will strain the bearings unnecessarily.

**Comment by kleuter** [comment] 2020-07-26 21:07
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/1

**Closed by kleuter** 2020-07-26 21:07 UTC
Labels: feature request
