### ISSUE TITLE
Feature request: fan speed presets

### ISSUE THREAD

**Issue by hellojole** [crystalidea/macs-fan-control#97] opened 2018-09-02 08:22 UTC
Title. It'd be awesome to get to use presets ("silent mode", "full blow" etc.) from the menu bar to quickly set the fans instead of having to open the app and use the sliders.

**Comment by kleuter** [comment] 2018-09-03 14:07
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/5

**Closed by kleuter** 2018-09-03 14:07 UTC
