### ISSUE TITLE
Can't Hide Menu Bar Icon

### ISSUE THREAD

**Issue by RyderCragie** [crystalidea/macs-fan-control#614] opened 2022-06-15 23:38 UTC
Just installed the latest version of Macs Fan Control on a clean install of macOS Monterey and I cannot hide the Menu Bar icon. Selecting "None" does nothing. Installed via this link: https://crystalidea.com/macs-fan-control/download

Logs:

```
Macs Fan Control 1.5.12 [Qt 5.15.8]
MacBookPro15,4 [AC]
CPU: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz [4 cores]
GPU: Intel Iris Plus Graphics 645
RAM: 8 GB
macOS 12.4.0

Fans:
Right side-min{1200}curr{2987}max{7200}mode{1,3000}

SMC sensors:
2B7UW+Lxv6xIRYH8MdV9PBnlM+Kv35Z84Dsa647ZPmo9Wu/4MxJ13Xr5pn2cZh3ItHkb2peFzzkCY9Hf9OufJr+6GTZD8M3HRLuPNr0NNdxrAdInVwTrJYRY
PPJ1ZKvHyl+eNKWThqZ06zhIs6hpAiK5dw+pVJP51E1j8bejWLSdt9CEL0dpwzs7dS4L4WWtYUOGZvvAp2r/zd/E8sGR39Fyg12hARlI5RSksuwmBl5K08xA
nOIngeT/NYjp2Fsj3WQQ4yjVaGNoVgdCZy1x/cYoFDyzw7PFK138im8nK9qewympF7fIrN0CtbRFJOnV9CZZn15Mp9HTEpdQKkE/jkzfBWdOpbh2xhnePI6e
ZHCI+a4qCXSBY7CJMvOecTd/Y8l/O73US8v9YK+UqGrLM2YYse6RvnJykEW3jQkISYYTCaYxe5Xm/7e45jLn1PxKZJMQUTz/SJ6xJUtKXMt6EYY5sAanv0QE
oPiqzPipoS/u9w787DalNc/g0HRd/Tv52PN2Hetqv0AfL4n4mB+2LnGxVKEAoNeUN8JawIygH66gDCa42Mq2WnaU5nviHfpKffG4JHecWksFpxYrBzSgu9UZ
65qNDk5NdgTd/c1UEJrfDYZHQDsLFYe5RB6deENM578EgZh/UxwBmhqMKJ9aVI6oF4T9wgypA9nhkayVvRir25zLENchthHwssOxsdpoP0O/UWrmHH072X58
E0F6cVxq56PdY0dYBMYjbovZGd4Dlav9oJcJL7ZnO9/yV0bcCpsCD2ZjYd/Tzmosb9UrCf7hdXUxujoxOgcL0gZCwppvvlh6Dl/ly+AaCgDb99XveA1E/Ga0
qSUI0lGNSnhsnwzBNe4e7Cd8blrTGYV//4Q7OI9BmfAy7CHxq+K5EbfTvCPUeohdkHemWZ6CS6FJCcTuElO43L7/lvcy708xebTJpN84wi78Fbq/lf/fMAGB
SROR1uvqpivt+btlatTU92VGGna3naYzSiL9NdJpvti4bsXOOvwaQ7r0GovbLORAm89X4Eo5q4qsn9ltZ4zR4FMbRJ01ll/9SnNl2qv+eshBrCYcdwaJBADV
S/rFBdoBaSxnCiBww9ng5RoGd8zGwEH+kJ7ZGYb9cVHUmzRLFab84VQlURQRHsrmfSuL5bt0KrLCDuxpam7HB0G5jENuTNuJu1X0Xf1XxmE/yfph17Jo1xPr
Gzon/2Ud6k2/hDJZECToccdme2MHwH9AxlEZEkxUzIqLbb2nn20piZ4Ek0b+vfRkIzgfsB6QuuRh+wDZa/tDUXg98YUWkkrl7K8BexHgoTIUjTLMBJIhzA6E
gqt8moI4o6wAV1arJ6YCkxL0NeEyyKNu2sSFbrXdi397CHBkatWNlRK9SGaey0ybQt26kwdfj7ARhvdJPPaNEk6RmsKU8JiDBnuFnLrsJqifwmH6xH0y5vt6
us87JDG7xM2Hz4H3hHvAzx9nO9+trx3E

GPUs:
Intel Iris Plus Graphics 645 - 84

Disk drives:
APPLE SSD AP0128N - 56

Log:

[2022-06-16 00:34:16:840] [thread 46360] [app.cpp#305] Macs Fan Control 1.5.12
[2022-06-16 00:34:16:840] [thread 46360] [app.cpp#306] macOS 12.4.0
[2022-06-16 00:34:16:840] [thread 46360] [app.cpp#307] MacBookPro15,4
[2022-06-16 00:34:16:840] [thread 46360] [app.cpp#308] Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz [4 cores]
[2022-06-16 00:34:16:840] [thread 46360] [app.cpp#309] Qt 5.15.8
[2022-06-16 00:34:16:854] [thread 46360] [smcWriteInstaller.mm#69] Helper installed (version 1.0.2)
[2022-06-16 00:34:16:854] [thread 46360] [smcWriteInstaller.mm#70] Helper file path: /Library/PrivilegedHelperTools/com.crystalidea.macsfancontrol.smcwrite
[2022-06-16 00:34:16:854] [thread 46360] [smcWriteInstaller.mm#71] Helper file size: 189712 bytes
[2022-06-16 00:34:16:855] [thread 46360] [smcWriteInstaller.mm#85] Current version - 1.0.2
[2022-06-16 00:34:16:855] [thread 46360] [Platform_mac_smcwrite.mm#79] open XPC connection to com.crystalidea.macsfancontrol.smcwrite
[2022-06-16 00:34:16:856] [thread 46360] [Platform_mac_smcwrite.mm#150] process_command_open: OK
[2022-06-16 00:34:16:856] [thread 46360] [Service.cpp#93] detectSmcFanKeySize KeyType flt 
[2022-06-16 00:34:16:856] [thread 46360] [Service.cpp#94] detectSmcFanKeySize KeyLen 4
[2022-06-16 00:34:16:857] [thread 46360] [Platform_mac.mm#188] getKeyInfo, the key FS!  doesn't likely exist
[2022-06-16 00:34:16:929] [thread 46360] [UpdateChecker.cpp#589] UpdateChecker: check (force = false)
[2022-06-16 00:34:16:941] [thread 46377] [FanControl.cpp#206] initialLoadThread
[2022-06-16 00:34:16:941] [thread 46377] [FanControl.cpp#162] QFanControl::loadFansFromSMC
[2022-06-16 00:34:16:942] [thread 46377] [FanControl.cpp#168] Fans count - 1
[2022-06-16 00:34:16:942] [thread 46377] [FanControl.cpp#185] Fan 0: Right side
[2022-06-16 00:34:16:943] [thread 46377] [FanControl.cpp#61] checkFansControlModeFromSMC
[2022-06-16 00:34:16:944] [thread 46377] [TempSensorProvider.cpp#68] TemperatureSensorProvider::loadAvailableSensors
[2022-06-16 00:34:16:945] [thread 46377] [Service.cpp#62] getSMCKeysCount: 1174601728 838
[2022-06-16 00:34:16:954] [thread 46377] [Service.cpp#564] Locating temperature SMC keys
[2022-06-16 00:34:16:968] [thread 46377] [Service.cpp#610] 36 keys found
[2022-06-16 00:34:16:976] [thread 46377] [Provider_mac.mm#268] discoverGPUs started
[2022-06-16 00:34:16:983] [thread 46377] [Provider_mac.mm#351] addGPU Intel Iris Plus Graphics 645 with MTLDevice
[2022-06-16 00:34:16:983] [thread 46377] [Provider_mac.mm#22] Device hold Intel(R) Iris(TM) Plus Graphics 645
[2022-06-16 00:34:16:985] [thread 46377] [Provider_mac_watcher.mm#82] eGPUWatcher started
[2022-06-16 00:34:16:985] [thread 46377] [TempSensorGPU.cpp#75] Integrated GPU: Intel Iris Plus Graphics 645, matching SMC - yes
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#37] Using TC1C sensor for CPU Core (average)
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#37] Using TC2C sensor for CPU Core (average)
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#37] Using TC3C sensor for CPU Core (average)
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#37] Using TC4C sensor for CPU Core (average)
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#54] Adding virtual sensor 'cpucoreavg' as CPU Core (average)
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#121] InitialLoadThread: number of supported SMC sensors: 17
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#122] InitialLoadThread: number of supported DISK sensors: 1
[2022-06-16 00:34:16:987] [thread 46377] [TempSensorProvider.cpp#132] InitialLoadThread: number of supported GPU sensors: 1
[2022-06-16 00:34:16:987] [thread 46377] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:34:16:987] [thread 46377] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:34:17:028] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:34:17:028] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:34:17:028] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:34:17:029] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:34:18:533] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:34:18:533] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:34:20:034] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:34:20:034] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:34:20:035] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:34:20:035] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:34:21:538] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:34:21:538] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:34:23:040] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:34:23:040] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:34:23:040] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:34:23:040] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:34:38:057] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:34:38:057] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:34:38:058] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:34:38:058] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:34:51:584] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:34:51:584] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:34:51:585] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:34:51:585] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:35:09:618] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:35:09:618] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:35:09:619] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:35:09:619] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:35:36:655] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:35:36:655] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:35:36:655] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:35:36:655] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:35:41:162] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:35:41:162] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:35:41:163] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:35:41:163] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:37:53:394] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Md 01 OK
[2022-06-16 00:37:53:395] [thread 46388] [Service.cpp#517] Set fan 0 mode 1
[2022-06-16 00:37:53:396] [thread 46388] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey F0Tg 00803b45 OK
[2022-06-16 00:37:53:396] [thread 46388] [Service.cpp#341] setFanRPM 3000 for F0Tg
[2022-06-16 00:37:56:266] [thread 46360] [Service.cpp#688] getTemperature - skipping sensor TC0T with value of 255.746
[2022-06-16 00:37:56:271] [thread 46360] [Service.cpp#688] getTemperature - skipping sensor TH0c with value of 129.0
[2022-06-16 00:37:56:271] [thread 46360] [Service.cpp#688] getTemperature - skipping sensor TH0d with value of 129.0
```

**Comment by kleuter** [comment] 2022-06-16 08:48
No supported yet.
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/394

**Closed by kleuter** 2022-06-16 08:48 UTC

**Comment by RyderCragie** [comment] 2022-06-16 09:40
After 2 years?

**Comment by kleuter** [comment] 2022-06-16 09:42
We're not yet sure if it's safe.

**Comment by willbchang** [comment] 2022-09-08 02:00
@kleuter  I'm just curious, what is the reason to be unsafe for hiding the menu bar icon?
