### ISSUE TITLE
I did a factory reset on my computer and now i get an error SMC interaction layer

### ISSUE THREAD

**Issue by neeebs** [crystalidea/macs-fan-control#355] opened 2020-06-13 07:45 UTC
I recently bought the pro version for macs fan control but now when i try to open the application i get an error:
[2020-06-13 15:39:39:925] [thread 4496] [g:\projects\macsfancontrol\app\app.cpp#269] Macs Fan Control 1.5.7
[2020-06-13 15:39:39:926] [thread 4496] [g:\projects\macsfancontrol\app\app.cpp#270] Windows 10 x64
[2020-06-13 15:39:39:926] [thread 4496] [g:\projects\macsfancontrol\app\app.cpp#271] iMac14,2
[2020-06-13 15:39:39:926] [thread 4496] [g:\projects\macsfancontrol\app\app.cpp#272] Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz [4 cores]
[2020-06-13 15:39:39:926] [thread 4496] [g:\projects\macsfancontrol\app\app.cpp#273] Qt 5.13.2
[2020-06-13 15:39:39:926] [thread 4496] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#93] Using HAL
[2020-06-13 15:39:39:926] [thread 4496] [g:\projects\macsfancontrol\app\smc\platform_win_sys.cpp#86] ERROR: Failed to open standard port X (error 2), will try inpout32
[2020-06-13 15:39:39:926] [thread 4496] [g:\projects\macsfancontrol\app\smc\platform_win.cpp#102] PlatformWin::open trying inpout32

Can someone help me with this problem please?

**Comment by kleuter** [comment] 2020-06-13 10:03
Looks like one of those #350 #325 ?

**Comment by neeebs** [comment] 2020-06-14 12:09
yeap im guessing its riot vanguard blocking the mac fan control from running

**Comment by kleuter** [comment] 2020-06-14 12:21
Duplicate of #325

**Closed by kleuter** 2020-06-14 12:21 UTC
Labels: need more info
