### ISSUE TITLE
Menubar display/ Icon

### ISSUE THREAD

**Issue by friemelpiemel** [crystalidea/macs-fan-control#429] opened 2020-11-16 08:04 UTC
'Preferences/ menubar display/ icon' has 3 settings, the setting 'none' does not work.

<img width="455" alt="Screen Shot 2020-11-16 at 14 59 54" src="https://user-images.githubusercontent.com/74531119/99226820-fc2dfe00-281c-11eb-8b43-c02431684a48.png">

**Comment by zecanard** [comment] 2020-11-16 09:42
Works for me on macOS Catalina and Big Sur.

**Comment by kleuter** [comment] 2020-11-16 14:24
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/394

**Closed by kleuter** 2020-11-16 14:24 UTC
Labels: bug
