### ISSUE TITLE
Macs Fan Control crashes on launch, GUI does not load

### ISSUE THREAD

**Issue by khammo01** [crystalidea/macs-fan-control#284] opened 2020-02-10 20:51 UTC
Immediately crashes on launch. Sometimes I can see main window start to draw but immediately destroys itself. 
Have uninstalled / cleared plist and reinstalled. Macs Fan Control had previously worked on this same machine a week prior. 

Crash info attached.  
Catalina 10.15.3
[crash.txt](https://github.com/crystalidea/macs-fan-control/files/4182978/crash.txt)

**Comment by kleuter** [comment] 2020-02-10 20:56
Thank you. It's a very uncommon and strange crash.
Please try [this build](https://www.crystalidea.com/downloads/macsfancontrol_crash_test_1.zip)
When it crashes, please post a log file located on your desktop.

**Comment by kungfutennis** [comment] 2020-02-18 05:22
[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/4217443/MacsFanControl.log)

I get the crash too.  GUI pops open for a second then crashes.

**Comment by kleuter** [comment] 2020-02-18 09:39
Crash report, please?
https://bjango.com/help/crashlogmac/

**Comment by khammo01** [comment] 2020-02-18 10:44
Sorry, was apparently due to Hackintosh and fakesmc kext support for Z390 chipset/Catalina. The crash goes away with virtualsmc kext but with only partial support for the chip on the mainboard. Here is the crash in case you wanted to put a warning message instead of a crash. 
[MacsFanControl.log](https://github.com/crystalidea/macs-fan-control/files/4218731/MacsFanControl.log)

**Comment by kleuter** [comment] 2020-02-18 10:50
It's a log, not a crash report. Please find the crash report at:
~/Library/Logs/DiagnosticReports/

**Comment by khammo01** [comment] 2020-02-18 10:52
[Crash.txt](https://github.com/crystalidea/macs-fan-control/files/4218767/Crash.txt)

**Comment by kleuter** [comment] 2020-02-18 13:42
Please try [this build](https://www.crystalidea.com/downloads/macsfancontrol_crash_test_2.zip)
When it crashes, please post a log file located on your desktop + crash report

**Comment by kungfutennis** [comment] 2020-02-18 15:12
Will do.  Thanks.

**Comment by kungfutennis** [comment] 2020-02-19 09:39
[Macs Fan Control_2020-02-19-013605_mandark.crash.txt](https://github.com/crystalidea/macs-fan-control/files/4224233/Macs.Fan.Control_2020-02-19-013605_mandark.crash.txt)

I wonder if it's because I've got 64gb of RAM in my iMac 5k 2017?  Works fine on my iMac Pro 2017, but that has 32gb.  Same version of catalina 10.15.3

**Comment by kleuter** [comment] 2020-02-19 13:42
I'm sorry I didn't check build 2. Please try [this build](https://www.crystalidea.com/downloads/macsfancontrol_crash_test_3.zip)
When it crashes, please post a log file located on your desktop + crash report

**Comment by khammo01** [comment] 2020-02-19 19:42
No crash for me this time. I see GUI and a notice "no fans detected, please try to reset SMC" which is expected behavior for this configuration . Thanks

**Comment by kleuter** [comment] 2020-02-19 20:47
Please post the log file located on your desktop, it's very important, thanks.

**Comment by kungfutennis** [comment] 2020-02-19 20:50
Will do.  Am at work at the moment and can't test stuff.

**Comment by kleuter** [comment] 2020-02-19 20:51
Thank you!

**Comment by kleuter** [comment] 2020-02-20 10:00
Just a friendly reminder not to forget the log file 😉

**Comment by kungfutennis** [comment] 2020-02-21 05:44
[Macs Fan Control_2020-02-20-214208_mandark.crash.txt](https://github.com/crystalidea/macs-fan-control/files/4234450/Macs.Fan.Control_2020-02-20-214208_mandark.crash.txt)

**Comment by kleuter** [comment] 2020-02-21 10:37
I really asked for the log fille located on the desktop, not the crash report.

**Comment by kungfutennis** [comment] 2020-02-21 10:53
The weird thing is no log file on the desktop.  I will look again

**Comment by kungfutennis** [comment] 2020-02-22 06:59
Confirmed no log file on the desktop.

Am I missing something basic?  Is there a FAQ with what security
permissions are required for the app in the privacy section of the
preferences?

When I used the published version, it prompts to be moved to the
Applications folder, which if I agree, causes a crash.  If I don't agree to
move, crash and creation of the crash log, but again no desktop log.

That makes it feel like a permissions issue of some kind.

I booted in single mode and did a fsck.

Everything came up clean.

Same for running the built in diagnostics.

**Comment by kleuter** [comment] 2020-02-29 12:06
Please post the technical information (+log) available from the menu More -> Copy technical info

**Comment by kleuter** [comment] 2020-03-02 14:28
One more build, should work fine
https://www.crystalidea.com/downloads/macsfancontrol_crash_test_4.zip

**Comment by kleuter** [comment] 2020-03-16 10:43
Fixed in 1.5.5

**Closed by kleuter** 2020-03-16 10:43 UTC
Labels: Hackintosh, Top priority, bug
