### ISSUE TITLE
Selectively stop one fan at a time for a few seconds.

### ISSUE THREAD

**Issue by sgbotsford** [crystalidea/macs-fan-control#691] opened 2023-06-20 14:17 UTC
I just upgraded my mac pro to Catalina, and *some* fan is making more noise than it did.  Which makes me think that my newly inherited machine has a fan about to go south.

It would be cool if we could shut a fan down for just a few seconds to see if the noise changes.  Of course we could do this by making custom settings, but if the phone rings when the fan is reduced to 1/3 speed, it could be bad.  

I'm thinking a button to click that would stop a fan for X seconds or for the time it took for the temp to climb Y degrees,  Clicking it a second time, resumes.

**Comment by kleuter** [comment] 2023-06-26 11:41
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/582

**Closed by kleuter** 2023-06-26 11:41 UTC
Labels: feature request
