### ISSUE TITLE
When Mac goes to sleep fan runs at full speed

### ISSUE THREAD

**Issue by BigLewbowski** [crystalidea/macs-fan-control#612] opened 2022-06-11 21:59 UTC
When I updated my Mac to ver 11.6.6 when my computer goes to sleep the fan runs at top RPM until I wake it up. I am worried about the life of my fan as it runs like that all the time when not using it. I have started shutting down my Mac while not is use which is not ideal. 

Any help would be appreciated.

**Comment by chortick** [comment] 2022-06-14 02:39
Similar/same? I invoke Sleep, everything sleeps as expected. Some time later, I come back to find the computer frozen, but running fans at full blast. Nothing will shut it down except holding the power button.

Changing the sensor from the Apple HD to the WDC second drive just delays the problem. I still frequently come back to find a computer which I set to Sleep instead locked up and blasting the fan.

Quitting Macs Fan Control solves the problem.
Shutting down (vs Sleeping) the computer solves the problem.
Neither of those are particularly exciting options.

Log:

Macs Fan Control 1.5.13 [Qt 5.15.9]
iMac12,2
CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz [4 cores]
GPU: Intel HD Graphics 3000, AMD Radeon HD 6970M
RAM: 16 GB
macOS 10.13.6

Fans:
ODD-min{1150}curr{1147}max{2700}mode{0}
HDD-min{1100}curr{4330}max{5500}mode{0}
CPU-min{940}curr{940}max{2600}mode{0}

SMC sensors:
ShbgXCy2v6VrUBEmkdKv6LiAQ5M2/FcN4zBaQhqSXCB9Bjyz8s9HP0b8y0huT4VTHy4UfnuC1YNLZePTQ5mc7rFxGjAbeKKNkSVCXFS5NH32u+ukzNggCXu4
8mZBaXKoFU2HN8ca4rH0vfS5zZFtott0Tiz3qmVeIunxmnx3kPPLYeo3K8bgaoyoBTKOnr7gMpMAQuV6LGmqiCXM19b+LQmXTypZIRGBMKMhKpoMwUfoG86O
03adRqXwtlN/GDM25nYGMqX5NyKid/sUPR2VQvQbFlFkoOOtPZl43lLSRphcpM37LUwUnAS4KEiu+MwgJpzUkM158M21C9c+ApWu2Dpsb+VpXL4KM4OE2Ag4
MJFesF40xNbhCZUkNee6Q89UsGsUda9YcYwXBTQer66bURuQWDqTOWJQ6vDxvhp9AbIOlhfng6mw5A0xfHxAYFGINYFIyFl8fPhX6OXJAvR1UwP2LFWYy6ax
Yf3koa0wBfbAZc13+SprUZhKSG8os2FWqDYb+gi62jXv+vEiALpz3dMObG9jw65rwVgHJgxRYre09BSQyv6QESU/WklhdL0HcLyecPl1Q6JLvHl75/Tk9ano
EhzrusLoF05wDlVqPtXxuPg+STcbRU6SeXfhLc64EdK/EODsrbxurWVJbMVHGBNGpAVJzuye2gvGcLU3OW04c/zbtuK3PBvAnl6t3eqOIdNfNkAcnL59X3gp
UEnjLgvs+5CarPZcv/+vc6YHE82LKv5CEus+dKYp8nBRfZva4BXQvvyQlYC6CI1OJa83wm0wXpLS1vATYhziaNBzz0YIaaBgT8ywks3EPniW/UiidxSnE6+u
PyvSLVsFpsDlDZSBnI/KBw2JLwpK3YuV33mbmrfNNASxWmOwSuy5M9wH15gwSHoVBCE3dIi4KQM6uzilD3n68qfs4fB0CZNlCVGbLKkJs5M4NdT5cMYF11J1
GVYiIl8H7VM6cpv8QAlRF+DUHoeSdgKUkd5CMcpKU7Cvi4jlT7fJEv3ngwKi0YuLLHSY2/QTgrcHKYfE2yW/6hX0v1i0CMsPvIkjtDKUqukWtvB0h5JgvHN0
FYXV9qj1HvBogz+WMFdvQvfc392hNuHQd1t7XIuVd78tHUGzT8kia0oQv3FvqEKDHsmpG93TesR4JiI03opmTIe2Hzv6pXmxiR75sezoajLehp2LtRvEIlCY
kHGras1K1CNKOVdEDzL4liuAtJUW1OjqhBZ5FPAVNv8VEm4f24dPZIW3fsQbBXuAw/nvXdmxK0ovJy7seFKRuatYmHcyZ2AzagcoiG0oGV8wvWTNLaRqP/3b
C04BSkiWq+GbQ1Qv9MzcAM+3/53wJ1c8DT7FUSVmK6HGqqd9G5AxsN347m3QEi+I9kMC3RdTDu428gxeP6qAaJWScMwnlJbvUd2DK5FfY+PdQFIMT7ibjzr1
E1758wuKUs8AlhJG2RqluCm/l/zy7BPh4096gxyNSkoPK7H1EMo8ElO9aIXrH9Qqalb7KIhj48wsPLl6dtooKTC3bOKoPe/1N5i2FrfWjb13FZ2M3w7FxK37
UPVDDLxaox3MDTkHMjWad1pSx+QuF2HgKkb1KiW0+HD+FNjJxcb007Gwc+fBtwWGhAzrtdlaJvKq8b6WUDnVv/7Py5M3jaGwPfP3xS+F2wWXfsYE7XpsIPq0
yaGVRX4a4aAT7tGQKwuwlU5pRQmhIT/nB6/5scFDxiwG3ZUWwTxgSqwIG2P14efUi7fgm/ell++4HM/NoZ0KQS44uuvuqZLC1gIT2025VVGqgXh1

GPUs:
Intel HD Graphics 3000 - 49
AMD Radeon HD 6970M - 51.125

Disk drives:
APPLE SSD TS256C - 32
WDC WD4004FZWX-00GBGB0 - 40

Log:

[2022-06-13 22:24:41:727] [thread 85441] [app.cpp#305] Macs Fan Control 1.5.13
[2022-06-13 22:24:41:727] [thread 85441] [app.cpp#306] macOS 10.13.6
[2022-06-13 22:24:41:727] [thread 85441] [app.cpp#307] iMac12,2
[2022-06-13 22:24:41:727] [thread 85441] [app.cpp#308] Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz [4 cores]
[2022-06-13 22:24:41:727] [thread 85441] [app.cpp#309] Qt 5.15.9
[2022-06-13 22:24:41:743] [thread 85441] [smcWriteInstaller.mm#69] Helper installed (version 1.0.2)
[2022-06-13 22:24:41:743] [thread 85441] [smcWriteInstaller.mm#70] Helper file path: /Library/PrivilegedHelperTools/com.crystalidea.macsfancontrol.smcwrite
[2022-06-13 22:24:41:743] [thread 85441] [smcWriteInstaller.mm#71] Helper file size: 189712 bytes
[2022-06-13 22:24:41:743] [thread 85441] [smcWriteInstaller.mm#85] Current version - 1.0.2
[2022-06-13 22:24:41:744] [thread 85441] [Platform_mac_smcwrite.mm#79] open XPC connection to com.crystalidea.macsfancontrol.smcwrite
[2022-06-13 22:24:41:745] [thread 85441] [Platform_mac_smcwrite.mm#150] process_command_open: OK
[2022-06-13 22:24:41:745] [thread 85441] [Service.cpp#93] detectSmcFanKeySize KeyType fpe2
[2022-06-13 22:24:41:745] [thread 85441] [Service.cpp#94] detectSmcFanKeySize KeyLen 2
[2022-06-13 22:24:41:818] [thread 85441] [UpdateChecker.cpp#589] UpdateChecker: check (force = false)
[2022-06-13 22:24:41:823] [thread 86573] [FanControl.cpp#240] initialLoadThread
[2022-06-13 22:24:41:823] [thread 86573] [FanControl.cpp#194] QFanControl::loadFansFromSMC
[2022-06-13 22:24:41:825] [thread 86573] [FanControl.cpp#200] Fans count - 3
[2022-06-13 22:24:41:827] [thread 86573] [FanControl.cpp#217] Fan 0: ODD
[2022-06-13 22:24:41:833] [thread 86573] [FanControl.cpp#217] Fan 1: HDD
[2022-06-13 22:24:41:841] [thread 86573] [FanControl.cpp#217] Fan 2: CPU
[2022-06-13 22:24:41:845] [thread 86573] [FanControl.cpp#64] checkFansControlModeFromSMC
[2022-06-13 22:24:41:847] [thread 86573] [TempSensorProvider.cpp#68] TemperatureSensorProvider::loadAvailableSensors
[2022-06-13 22:24:41:849] [thread 86573] [Service.cpp#62] getSMCKeysCount: 1275133952 332
[2022-06-13 22:24:41:870] [thread 86573] [Service.cpp#564] Locating temperature SMC keys
[2022-06-13 22:24:41:931] [thread 86573] [Service.cpp#610] 49 keys found
[2022-06-13 22:24:41:997] [thread 86573] [Provider_mac.mm#268] discoverGPUs started
[2022-06-13 22:24:41:998] [thread 86573] [Provider_mac.mm#357] No matching MTLDevice for Intel HD Graphics 3000
[2022-06-13 22:24:41:999] [thread 86573] [Provider_mac.mm#357] No matching MTLDevice for AMD Radeon HD 6970M
[2022-06-13 22:24:42:001] [thread 86573] [Provider_mac_watcher.mm#82] eGPUWatcher started
[2022-06-13 22:24:42:001] [thread 86573] [TempSensorGPU.cpp#75] Integrated GPU: Intel HD Graphics 3000, matching SMC - yes
[2022-06-13 22:24:42:001] [thread 86573] [TempSensorGPU.cpp#92] Discrete GPU: GPU AMD Radeon HD 6970M, matching SMC - yes
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#37] Using TC0c sensor for CPU Core (average)
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#37] Using TC1c sensor for CPU Core (average)
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#37] Using TC2c sensor for CPU Core (average)
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#37] Using TC3c sensor for CPU Core (average)
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#54] Adding virtual sensor 'cpucoreavg' as CPU Core (average)
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#121] InitialLoadThread: number of supported SMC sensors: 18
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#122] InitialLoadThread: number of supported DISK sensors: 2
[2022-06-13 22:24:42:006] [thread 86573] [TempSensorProvider.cpp#132] InitialLoadThread: number of supported GPU sensors: 2
[2022-06-13 22:24:42:007] [thread 86573] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey FS!  0000 OK
[2022-06-13 22:24:42:007] [thread 86573] [Service.cpp#484] Set fans mode 0
[2022-06-13 22:24:42:078] [thread 86579] [TempSensorGPU.cpp#27] Reading of GPU temperature failed
[2022-06-13 22:24:42:079] [thread 86579] [TempSensorGPU.cpp#32] Trying SMC instead

**Comment by kleuter** [comment] 2022-06-16 21:07
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/596

**Closed by kleuter** 2022-06-16 21:07 UTC
