### ISSUE TITLE
iMac Pro - current RPM is higher than max RPM

### ISSUE THREAD

**Issue by worldpoop** [crystalidea/macs-fan-control#574] opened 2022-02-08 08:00 UTC
I've been having overheating issues for a while now.  I recently discovered that the Full Blast preset (reaching 2500 rpm) that I've been relying on during intensive tasks is actually much slower than what Automatic can achieve.  

I can't list Automatic's top speed right now as my iMac Pro's not overheating at the moment -- just don't remember, lame, apologies.  But it's numerically and audibly much faster than Full Blast.  Maybe 2900+ rpm?  Dunno.  Anyway, in the short time since my discovery, so far I've _not_ had the Mac spin down in "survival mode" when hitting 100 deg, which has occurred several times during Full Blast.  Doesn't mean it won't... stay tuned on that one.  

Cheers

![image](https://github.com/crystalidea/macs-fan-control/assets/2600624/6fca9a57-d790-47d1-b198-edcf228bd4b0)

**Comment by worldpoop** [comment] 2023-05-29 05:02
Well, it's taken me a year to respond.  Attached is what happens and it's
enough to make a difference -- when the computer is hot, it will reach
overheating and shutdown if I leave it on "Full Blast" -

**Comment by kleuter** [comment] 2023-06-21 08:14
On some Apple computers current RPM can sometimes be higher than maximum (when running on auto), the reason for that is currently unknown, it can be a bug or a feature

**Comment by kleuter** [comment] 2023-06-21 08:45
Duplicate of #66

**Comment by kleuter** [comment] 2023-06-21 08:45
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/66

**Closed by kleuter** 2023-06-21 08:45 UTC

**Comment by worldpoop** [comment] 2023-06-23 01:54
> On some Apple computers current RPM can sometimes be higher than maximum (when running on auto), the reason for that is currently unknown, it can be a bug or a feature

It must be a feature -- or perhaps Apple's problem solving "hack" -- b/c "Full Blast" is not fast enough to prevent shutdown.  It would be a welcome "bug" if so!  'cept MFC presents a danger in the face of it and I can't use it :(

Apologies for the dupe!

**Comment by worldpoop** [comment] 2023-07-21 09:55
Discovered something.  Using iStat menus to control fan speed, and it is _possible_ max the speed out (in my case, 2800+ rmp, rather being capped like MFC at 2500rpm).  I'm using it and it's working to steer clear of overheating.  So it is possible in the coding :/

**Comment by worldpoop** [comment] 2023-07-21 09:59
Just discovered something. I'm using iStat menus now to control fan speed,
and it *is* possible max the speed out (in my case the system's true 2800+
rmp, rather capped with MFC at 2500rpm). I'm using it and it's working to
steer clear of overheating. Thought you'd be interested in that -- it is
possible to code for it.  Somehow.... :/
