### ISSUE TITLE
M3 chips temperature sensors support

### ISSUE THREAD

**Issue by MysticalOS** [crystalidea/macs-fan-control#716] opened 2023-11-08 01:57 UTC
[Mac15,9_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13291131/Mac15.9_tech_info.zip)
Using M3 max 40 Core

**Comment by kleuter** [comment] 2023-11-08 11:57
Thanks a lot

**Comment by MysticalOS** [comment] 2023-11-10 07:50
Hopefully we see a beta soon because I'd certainly love to be able to monitor these temps and setup fan curves. even the basic "full blast" and half blast don't work

**Comment by kleuter** [comment] 2023-11-10 20:49
I will soon get my hands on M3 laptops, stay tuned.

**Comment by sebolio** [comment] 2023-11-13 19:51
+1

hoping for a working version soon :) it works sometimes and others not

**Comment by samdenty** [comment] 2023-11-18 16:02
putting them on full blast only seems to work when they're already running (not in the orange zero state)

**Comment by kleuter** [comment] 2023-11-20 14:36
I think it works, but after a delay of couple of seconds

**Comment by kaorihinata** [comment] 2023-11-20 17:55
It doesn't, at least not on my M3 Pro. I would also note that even if I set it as @samdenty describes (while the fans are on), once the temperature drops down low enough it will still return to 0 speed mode even if set to full blast, so I'm assuming that the method used to disable automatic no longer works either.

**Comment by kleuter** [comment] 2023-11-21 00:07
Here's a test build, works on both M3/M3 Pro (displays sensors and controls fan speed). Not tested on M3 max yet (tech info welcome).
[macsfancontrol.zip](https://github.com/crystalidea/macs-fan-control/files/13420422/macsfancontrol.zip)

**Comment by kaorihinata** [comment] 2023-11-21 00:27
Can confirm that I can now see all of my sensors, but neither setting Full blast, nor setting a custom sensor based fan curve engages the fans. This is the base 16 inch MacBook Pro. Waited a good 5 minutes. Do you need something for debugging?

**Comment by kleuter** [comment] 2023-11-21 00:36
Please first try setting full blast, wait 1 minute and post tech info as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by kaorihinata** [comment] 2023-11-21 00:57
See attached. I set the settings back to Automatic, shut down Macs Fan Control, opened it again, set it to Full blast, waited one minute, then exported tech info.

[MacBookPro20,5_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13420625/MacBookPro20.5_tech_info.zip)

**Comment by kleuter** [comment] 2023-11-21 01:00
Is there any difference when using the MacBook on battery (AC off)?

**Comment by kaorihinata** [comment] 2023-11-21 01:05
Nothing visible or audible. Fans still off. I repeated the reset, close the software and open it again on battery power. Tech info attached.

[MacBookPro20,5_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13420675/MacBookPro20.5_tech_info.zip)

**Comment by piceapungens** [comment] 2023-11-21 04:43
Same issue, 16" m3 mbp, the app and the test app do nothing. 

[MacBookPro20,5_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13421804/MacBookPro20.5_tech_info.zip)

**Comment by MysticalOS** [comment] 2023-11-21 08:27
> Please first try setting full blast, wait 1 minute and post tech info as described [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md?rgh-link-date=2023-11-21T00%3A36%3A52Z).

The way it works for my testing, on M3, fan control only controls the fan speed but NOT whether or not they should be on or not. Basically half and full blast work, but only if the fans would be on in automatic. if automatic/default curve has decided fans should not be on, then fan control does absolutely nothing.

So in short, it seems the software is controlling the fan speed but not the on/off state of the fans. I can reproduce this 100% of time. As long as the fans aren't 0rpm in automatic, the manual settings work. if the automatic is in 0rpm, manual does absolutely nothing.

**Comment by PPinnate** [comment] 2023-11-21 11:15
The same case I am experiencing with the 16" M3 Max MacBook Pro. (App not controlling fan on/off, but it does control speed) 
I am also noticing on my Mac, only 8 performance cores is showing and the temperature for GPU Core Average is displaying 7C/45F and stay still.

[MacBookPro20,7_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13425350/MacBookPro20.7_tech_info.zip)

Step I did before generating log for your reference.

1. Open the apps
2. Full Blast
3. Wait for ~30seconds
4. Open Handbrake to encode a video with CPU
5. Wait until fan automatically kick in(Setting still in full blast)
6. Manually adjust the fan to 3500RPM(left, then right), it does able to control
7. Stop handbrake
8. Fan stopped automatically(Setting still in full blast)

**Comment by MysticalOS** [comment] 2023-11-22 10:44
Can confirm PP finding as well, gpu temp stick at 7, several cpu cores missing.

**Comment by kleuter** [comment] 2023-11-24 17:10
Just ordered M3 Pro 16", will be delivered in 2 weeks (customized keyboard).

**Comment by kleuter** [comment] 2023-11-29 19:17
Current status: problem confirmed

**Comment by picinko** [comment] 2023-12-02 09:53
Hello guys, I wish this could be solved soon. I own MacBook Pro 16 M3 Max 14C 30GPU and facing the same problem that can't control macs fan. I render videos in premiere pro quite often and my MacBook gets very hot every time. I don't trust to system controled fans. Over time it can cause battery degrading in my opinion. Good luck.

**Comment by MysticalOS** [comment] 2023-12-02 09:56
If you use beta, you can control the fans in heavier loads, you just can't really control them in light loads because it only controls fan speed not fan activation and apple seems to kick fans on (at all) near the 70C mark, sometimes 60, not sure what makes apple choose 60 or 70. but once they are on you can control them. i have a temperature curve and everything setup and it works, just not til 70C. Ideally I'd like them to kick in around 55-60 (at low rpm) but that'll come later.

but during your rendering, yeah you'll activate the fans (and THEN fan control will take over).

Just use beta from https://github.com/crystalidea/macs-fan-control/issues/721

**Comment by kleuter** [comment] 2023-12-04 13:44
Currently there's no way to force turn on the fan(s) on 16" M3 MacBook Pro 😢

**Comment by Mastertherm** [comment] 2023-12-04 14:23
What would you (@kleuter) say are the average temperatures MacBook Pro can run on long-term not to sustain long-term damage on internal components? Temperatures on CPU, GPU or on the Chasis, whichever is fine. I want to play some games on it since it packs quite the punch - i.e. awaiting the launch of Death Stranding. I tried World of Tanks but the laptop gets quite hot, yet the fans never turn on. I have been using mine for over a month and so far, I had never heard the fans to turn on...

**Comment by picinko** [comment] 2023-12-04 14:31
I found that many users even on older macs are facing the similiar issue. https://discussions.apple.com/thread/255184490
Is there any chance @kleuter that you could send request to solve this direct to apple support ? As you are a developer of an app they could maybe fix this in next update or allow to developers overrun system settings. When I use TG Pro the message is popping out about hardware disable fan control . -https://www.tunabellysoftware.com/support/tgpro_tutorial/#fan_control_t2

**Comment by MysticalOS** [comment] 2023-12-06 02:33
Fortunately, it does work in sense of kicking in fans as i need them when I most need them. when it IS warm enough to turn on fans, it turns them on higher as I need.

At this point just need remaining temp sensors and such fixed.

**Comment by n1ckfra** [comment] 2023-12-07 09:29
Thanks guys for the hingsight I was getting mad troubleshooting this issue as I wasn't able to understand what was going on. Pretty clear now, hoping for some walk around but still manageable. For record it worked flawlessly on M1 Pro I had before but now on M3Max I'm having this issue

**Comment by Ender-Wang** [comment] 2023-12-17 22:55
M3 Max 14", 16 CPU cores, 40 GPU cores. It works as expected, other than I cannot set fan speed based on CPU pack ATM, a compatibility update is required.
[Mac15,8_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/13698038/Mac15.8_tech_info.zip)

**Comment by MysticalOS** [comment] 2023-12-17 22:56
I hope to see temp on gpu package fixed, and missing cores added. complete the sensor data basically.

**Comment by PPinnate** [comment] 2023-12-20 10:33
> I hope to see temp on gpu package fixed, and missing cores added. complete the sensor data basically.

Just updated macOS to 14.2.1, found the GPU Core Average now show the correct temperature, likely due to some software bug in the older release of macOS.(14.2 still shows 7C).

Other(missing cores, fan kick in) unchange.

**Comment by MysticalOS** [comment] 2023-12-31 03:59
@PPinnate 14.2.1 didn't actually fix GPU temperature, just changed invalid value. now it's always 28 instead of 7, but it's never anything other than 28 so it's still wrong.

**Comment by PPinnate** [comment] 2023-12-31 06:15
> @PPinnate 14.2.1 didn't actually fix GPU temperature, just changed invalid value. now it's always 28 instead of 7, but it's never anything other than 28 so it's still wrong.

I was too excited to see the number changed and thought that it is "fixed" 😢 
But I do notice that the temp of GPU was jumping around, however this happened very rarely and stay at 28.4 after relaunch the apps, hard to replicate.

**Comment by picinko** [comment] 2024-01-05 15:45
Hello guys, is there any news about this case ? I am suprised that nobody except this thread is talking about neither on youtube or somewhere related to MacsFanControl.

**Comment by jake765111** [comment] 2024-01-08 21:36
I am also hoping for an update on this. Can't see all my sensors and cannot really control fan speeds on my Mac Pro m3 pro 14in. Hoping this is resolved soon or a workaround is found!

**Comment by Mastertherm** [comment] 2024-01-12 15:11
Hi fellas, M3 Pro MacBook Pro 16":
The app shows a higher current RPM than the "maximum" says it can be.

Screenshot was taken a second after it went away 🙃

![CleanShot 2024-01-12 at 16 09 02@2x](https://github.com/crystalidea/macs-fan-control/assets/135116593/fef619fd-376c-43cc-998e-f874fd6ea312)

**Comment by jcrate** [comment] 2024-01-13 06:22
I've downloaded the 1.5.17 beta and run it on my new M3 Max 16" MacBook Pro. The GPU core average often stops updating until the computer is restarted. Controlling the fan via sensor-based value is erratic. For example, if I control by CPU core average, starting at 45C with max 65C, the fans may not turn on at all until 75-80C.

**Comment by MysticalOS** [comment] 2024-01-13 06:27
As already discoveed above, apple blocks controling when fans turn on, only how hard they spin once they do, so they'll not turn on until about 75-80 because that's apple restriction, but once they do THEN they'll use your curve until temp falls below that mark then shut off. basically we can't keep it at 60C anymore if we wanted, all we can do is keep it from thermal throttling or sitting at 90C. we make sure that it does this cycle

fans off til apple decides to turn em on.
they go full blast til apple decides they turn off
repeat

my experience I can at least keep it under 80C now, better than default curve which does in fact let it hit 100C and throttle under a long heavy load.

**Comment by jcrate** [comment] 2024-01-13 07:54
Ahh...sorry I missed that above about not being able to turn the fans on at all. 

Is the automatic setting the same as Apple's default? Or is it also full blast once the fans turn on, until Apple decides to turn them off? 

If automatic is full blast until Apple turns them off, does setting a sensor-based value curve do anything? It sounds like you might run them full blast until the low temp is reached?

**Comment by MysticalOS** [comment] 2024-01-13 07:56
The curve does work, to an extent, it'll just kick in once apple turns on. apple controls turn on and turn off, the curve just desides how hard they turn on based on temp. like mine don't go full blast when they turn on at like 75C, usually cool to 70-60 then turn off. i rarely hear them full blast unless I am doing something super intensive

**Comment by kaorihinata** [comment] 2024-01-13 17:35
> Hi fellas, M3 Pro MacBook Pro 16": The app shows a higher current RPM than the "maximum" says it can be.
> 
> Screenshot was taken a second after it went away 🙃

I've seen this too and those readings are directly from the SMC without any changes. If you pull out the old `smc` tool you can see Apple reporting those very same values in `F0Mx`/`F0Mn`/`F0Ac` (as well as the `F1` variants.) Macs Fan Control isn't misreading them. I'm assuming that `F0Mx`/`F1Mx` are simply the maximum target value (think `F0Tg`/`F1Tg`) and not the maximum speed electrically possible. The SMC will try to maintain a speed somewhere around the target speed.

**Comment by isantiago95** [comment] 2024-03-01 22:19
Hey community!

I recently bought a MBP 16" M3 Pro, and in my previous laptop (MBP 14" M2 Pro) the mac fans control app worked fine, I have downloaded the app from [here](https://crystalidea.com/macs-fan-control/download) but I can't make it work, here's my laptop information:

<img width="392" alt="image" src="https://github.com/crystalidea/macs-fan-control/assets/18353644/68d9a5d9-761a-42ae-9098-9c5060eb9802">

<img width="841" alt="image" src="https://github.com/crystalidea/macs-fan-control/assets/18353644/0c29dbe5-bc24-4568-ba0d-cde1b37a52b3">

Does anyone has any update on this?

**Comment by MysticalOS** [comment] 2024-03-02 03:27
You won't be able to turn fans on and off yourself, only set speed when apple decides to turn them on.

14.4 beta 5 though has a firmware update that from my testing kinda changes this. This software still can't turn the fans on or off and it still only controls fan speed, but the threshold for when APPLE turns fans on changed from 85C to 58C and threshold for where they turn them off changed from 58C to 50C

This is what i was able to conclude from my testing. So before
No fans until about 85C, then they kick in at speed I have set in this software. and they'd stay on until temp fell below about 58 then stay off til next time i hit 85C
New behavior in 14.4 beta 5. They kick on at 58C now (but before then still stay off regardless of software settings). and kick off at 50C now

it's a huge improvement since apple basically recognized their own curve was SUPER bad. Basically apple didn't remove restrictions for controlling on and off after all, but since they made default fan curve better, they at least kick in at a meaningful time now which still makes this software WAY more useful in controlling fan speed.

**Comment by vlbosch** [comment] 2024-03-05 10:11
Unfortunately, the fan curve on my system (Mac15,9 M3 Max 16C-40C, firmware 10151.101.3 running the macOS Sonoma 14.4 RC) appears to still be the same. The fans only turn on at around 85ºC for a given sensor (GPU for example) and as soon as the system thinks the workload dropped or the temp goes below 75ºC, they are switched of again. 

I was very hopeful after reading this thread, but it appears in the 14.4 RC they either changed it back or were maintaining the absurd setting they've always had on M3-systems all along.

**Comment by MysticalOS** [comment] 2024-03-05 22:02
I can confirm they reverted it in RC 1 :\
it was literally fine in beta 5, and RC1 was like "just kidding"

**Comment by runenilsenoe** [comment] 2024-03-07 13:10
Following this, performance dips way before fan kicks in

**Comment by Katesonlin** [comment] 2024-03-08 03:37
> 您将无法自行打开和关闭风扇，只能在苹果决定打开风扇时设置速度。
> 
> 14.4 beta 5 虽然有一个固件更新，但根据我的测试，它有点改变了这一点。该软件仍然无法打开或关闭风扇，仍然只能控制风扇速度，但APPLE打开风扇的阈值从85C更改为58C，关闭风扇的阈值从58C更改为50C
> 
> 这是我从测试中得出的结论。因此，在 大约 85C 之前没有风扇，然后它们会按照我在该软件中设置的速度启动。它们会一直保持打开状态，直到温度低于 58 左右，然后保持关闭状态，直到下次我达到 85C 14.4 beta 5 中的新行为。它们现在在 58C 处启动（但在此之前，无论软件设置如何，它们仍然保持关闭状态）。现在在 50C 开始
> 
> 这是一个巨大的进步，因为苹果基本上认识到自己的曲线非常糟糕。基本上苹果毕竟没有取消控制打开和关闭的限制，但由于他们使默认风扇曲线更好，它们至少在一个有意义的时间启动，这仍然使该软件在控制风扇速度方面更有用。

So the current test version still cannot control the speed of the custom fan well? Is this related to the setting of Sonoma's underlying architecture calling fans?

**Comment by a-k-holod** [comment] 2024-03-21 13:22
I think it's been fixed now as on Macbook M3 Pro i can set constant RPM value as well as sensor based.

Testing auto based on eg. Airport proxmity 40-50C with docker building in bkg, works well, temps go lower and turn off.
 Changing values to lower 30-40C and as it never goes lower, you get constant light breeze.

**Comment by Katesonlin** [comment] 2024-03-27 06:32
OK,Thanks

Angela ***@***.***> 于2024年3月21日周四 21:23写道：

**Comment by hithot2008** [comment] 2024-03-28 06:41
I use a 2024 macbook pro 16" m3 max. It only runs when I turn it on. Once I manually adjust it, it doesn't work anymore and it can't display the CPU temperature.
<img width="273" alt="截圖 2024-03-28 下午2 38 46" src="https://github.com/crystalidea/macs-fan-control/assets/24997129/c747518b-886a-4926-b3bd-a38a01f743c2">
<img width="817" alt="截圖 2024-03-28 下午2 39 02" src="https://github.com/crystalidea/macs-fan-control/assets/24997129/79cbe7f2-6692-4e98-a623-a9cae69d5210">

**Comment by Doyal** [comment] 2024-04-01 03:56
+1 on the same issues.  MBP 16 M3 and see only the limited sensors here (https://github.com/crystalidea/macs-fan-control/issues/716#issuecomment-2024506519) and the same fan issue - After applying any kind of custom fan will result in the same picture in that post: Fans are turning and easily audible yet the app reports 0rpm.

**Comment by PPinnate** [comment] 2024-06-12 23:55
<img width="933" alt="screenshot-fancontrol-macOS15" src="https://github.com/crystalidea/macs-fan-control/assets/102272223/90206ac3-cdad-4c5f-b2d0-61e52934e893">
[MacBookPro20,7_tech_info.zip](https://github.com/user-attachments/files/15812047/MacBookPro20.7_tech_info.zip)

A quick test with macOS 15 beta 1, the behavior is very similar to the previous version macOS

**Comment by TopScrech** [comment] 2024-06-13 10:26
Same behavior on M3 Max

**Comment by danieltsoftware** [comment] 2024-06-25 01:38
> I'm having the same issue with my M3. It only shows the following temperatures.
> 
> <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/21032419/341044488-59fc37ff-0984-41e4-a78a-02072f6453e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzk3NDIsIm5iZiI6MTcxOTI3OTQ0MiwicGF0aCI6Ii8yMTAzMjQxOS8zNDEwNDQ0ODgtNTlmYzM3ZmYtMDk4NC00MWU0LWE3OGEtMDIwNzJmNjQ1M2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxMzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NGIwZmM5MzdlMGE5NWIxYzkwZDdkMDk2OTdkZTI4NjdjZTZkOGRjMzYyZDc2MTM2Mzg3YmNlOWM2ZDg4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KjvFG5Mzq-K2tsflSDcKRG4HGapJdmKO3Oe0ZXa8QF4">
> Edit:
> 
> Now the fans is always showing 0, which is not true.

Download the beta from the thread above. [beta](https://github.com/crystalidea/macs-fan-control/issues/721)

**Comment by ajp2024-mac** [comment] 2024-07-12 08:35
> Here's a test build, works on both M3/M3 Pro (displays sensors and controls fan speed). Not tested on M3 max yet (tech info welcome). [macsfancontrol.zip](https://github.com/crystalidea/macs-fan-control/files/13420422/macsfancontrol.zip)

I can confirm this also works for my 14 inch Macbook pro m3 max thank you very much, very appreciative of you to create this.

**Comment by h4jahmad** [comment] 2024-08-01 11:00
Have any fixes been released for this issue? Facing the same thing on the MacBook Pro M3 max 14 inch.
<img width="813" alt="Screenshot 2024-08-01 at 14 59 26" src="https://github.com/user-attachments/assets/3765b543-8651-4997-bee2-723d683fce20">

**Comment by aprilmintacpineda** [comment] 2024-08-01 22:32
> > I'm having the same issue with my M3. It only shows the following temperatures.
> > <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/21032419/341044488-59fc37ff-0984-41e4-a78a-02072f6453e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzk3NDIsIm5iZiI6MTcxOTI3OTQ0MiwicGF0aCI6Ii8yMTAzMjQxOS8zNDEwNDQ0ODgtNTlmYzM3ZmYtMDk4NC00MWU0LWE3OGEtMDIwNzJmNjQ1M2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxMzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NGIwZmM5MzdlMGE5NWIxYzkwZDdkMDk2OTdkZTI4NjdjZTZkOGRjMzYyZDc2MTM2Mzg3YmNlOWM2ZDg4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KjvFG5Mzq-K2tsflSDcKRG4HGapJdmKO3Oe0ZXa8QF4">
> > Edit:
> > Now the fans is always showing 0, which is not true.
> 
> Download the beta from the thread above. [beta](https://github.com/crystalidea/macs-fan-control/issues/721)

The beta fixed the temperature monitor but not the fans monitor. Seems it cannot control it or cannot detect the actual RPM.  Screenshot below you can see I set it to full blast but it's still on 0 and I cannot hear or feel the fans going -- though I'm sure it works because I have heard it go when I conducted a hardware test.

<img width="819" alt="image" src="https://github.com/user-attachments/assets/8317360a-3ed9-40cd-9452-730a7c3a3745">

**Comment by MysticalOS** [comment] 2024-08-01 22:47
scrolling up would answer why that is. apple doesn't let the app control whether fans are on or off, only what speed they are once apple decides to turn them on.

it's reporting RPM correctly, it is at 0 because the fans aren't on. when they turn on it would set them to full blast per your settings.

**Comment by runenilsenoe** [comment] 2024-08-07 12:27
> scrolling up would answer why that is. apple doesn't let the app control whether fans are on or off, only what speed they are once apple decides to turn them on.
> 
> it's reporting RPM correctly, it is at 0 because the fans aren't on. when they turn on it would set them to full blast per your settings.

Guess they are afraid of battery life by setting the threshold for turning on fans lower. Only reasonable explanation. Still a bit annoying, i get frame drops before the fans turn on - M3 Pro

**Comment by h4jahmad** [comment] 2024-08-21 18:35
> scrolling up would answer why that is. apple doesn't let the app control whether fans are on or off, only what speed they are once apple decides to turn them on.
> 
> it's reporting RPM correctly, it is at 0 because the fans aren't on. when they turn on it would set them to full blast per your settings.

@MysticalOS that's my bad. I meant the issue that I couldn't see the CPU's temperature. And if the same case applies here, which of the sensors do you think gives the closest temperature to the CPU's?

**Comment by Doyal** [comment] 2024-08-21 21:52
Even if Apple is controlling the fans on/pff state, that doesn’t really cover why M3 base chips can get the same temp readings we used to and the M3 Max only gets a few. (See prior screenshots)

On Aug 21, 2024, at 1:35 PM, Ahmad Reza Enshaee ***@***.***> wrote:

﻿

scrolling up would answer why that is. apple doesn't let the app control whether fans are on or off, only what speed they are once apple decides to turn them on.

it's reporting RPM correctly, it is at 0 because the fans aren't on. when they turn on it would set them to full blast per your settings.

@MysticalOS<https://github.com/MysticalOS> that's my bad. I meant the issue that I couldn't see the CPU's temperature. And if the same case applies here, which of the sensors do you think gives the closest temperature to the CPU's?

**Comment by MysticalOS** [comment] 2024-08-21 21:56
oh that's probably just a bug in this program. it feels like author has all but given up on it after last beta release. didn't fix remaining sensor bugs and never did a non beta release. disappointing in that regard.

**Comment by aprilmintacpineda** [comment] 2024-08-22 04:37
For anyone looking for a great alternative that works really well even on M3 chip. Here it is https://www.tunabellysoftware.com/tgpro/ I've been using it since I encountered issues with MFC and it works really well, however, like MFC, it also cannot turn on the fans by itself, however, on times when it is on, you can actually still see the RPMs (I just haven't tried controlling it's speed, in my observation, it doesn't turn on that much until the temp is 70 degrees or higher which doesn't happen a lot even when I'm building Android and iOS apps simultaneously). It has better menu bar UI and can display 2 temperatures of your choosing simultaneously, it can also track more stuff.

<img width="324" alt="image" src="https://github.com/user-attachments/assets/631fbcc4-7d28-486a-a2eb-59a840e06ede">

<img width="796" alt="image" src="https://github.com/user-attachments/assets/3c4f9744-94d0-41c1-956d-2384104fdb27">

It's really really good for only 10 USD!

**Comment by kleuter** [comment] 2024-08-22 08:52
@MysticalOS 
Sorry, didn't given up yet, will fix the sensors (had lots of other priorities)

**Comment by io-Arsam** [comment] 2024-09-03 19:46
So Still there isn't any way/app to turn on m3 pro 16 fans manually?

**Comment by alb9k** [comment] 2024-09-29 10:28
Same to my MacBook Pro M3 Pro 18GB/1TB...not work anymore after upgraded Sonoma to 14.7 
[MacBookPro20,2_tech_info.zip](https://github.com/user-attachments/files/17178868/MacBookPro20.2_tech_info.zip)

**Comment by kleuter** [comment] 2024-11-27 16:54
M3 max is supported as well now in the latest beta

**Comment by picinko** [comment] 2024-11-27 21:27
> M3 max is supported as well now in the latest beta

Where I can download that beta for M3 Max Support ? Thanks

**Closed** 2024-12-16 13:15 UTC
Labels: enhancement, Done in beta
