### ISSUE TITLE
Fan at high speed but no Control at all

### ISSUE THREAD

**Issue by lucholeg** [crystalidea/macs-fan-control#661] opened 2023-01-15 15:19 UTC
I recently replace the SSD on a MacBook Air, using the MacFan Control Software I can identify the fan is running at 8750 rpm high from the limit, I have try to use the different options of the software but none is working. Any ideas on how to put this fan in control the Mac is very noisy.

**Comment by kleuter** [comment] 2023-01-16 17:11
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by lucholeg** [comment] 2023-01-17 02:41
Hello,

Attached please find the screenshots requested.

Notice Fan is over speeding… but no control with the software.  Hope you can help in finding the right solution.

Gracias y saludes,

Luis Eduardo Gonzalez Ch
Cel 310 5751150

From: Kleuter ***@***.***>
Date: Monday, 16 January 2023, 12:11 PM
To: crystalidea/macs-fan-control ***@***.***>
Cc: lucholeg ***@***.***>, Author ***@***.***>
Subject: Re: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)

Please post tech info and app screenshot as described at here<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcrystalidea%2Fmacs-fan-control%2Fblob%2Fmaster%2Fhow-to-post-tech-info.md&data=05%7C01%7C%7Ce51531d177a24891c93d08daf7e4be87%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638094859083807592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mBJ3z9I%2BZYrNwRi6lNHhNNn8Lruo%2FcPWIf9Sk%2F8JpBE%3D&reserved=0>.

**Comment by lucholeg** [comment] 2023-01-20 13:21
Hello,

Had you have the opportunity to review the issue? Any additional recommendations to manage the noisy fan?

Thanks.

Gracias y saludes,

Luis Eduardo Gonzalez Ch
310-5751150

De: Luis Eduardo Gonzalez Ch ***@***.***>
Enviado el: Monday, January 16, 2023 9:42 PM
Para: crystalidea/macs-fan-control ***@***.***>; crystalidea/macs-fan-control ***@***.***>
CC: Author ***@***.***>
Asunto: Re: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)

Hello,

Attached please find the screenshots requested.

Notice Fan is over speeding... but no control with the software.  Hope you can help in finding the right solution.

Gracias y saludes,

Luis Eduardo Gonzalez Ch
Cel 310 5751150

From: Kleuter ***@***.******@***.***>>
Date: Monday, 16 January 2023, 12:11 PM
To: crystalidea/macs-fan-control ***@***.******@***.***>>
Cc: lucholeg ***@***.******@***.***>>, Author ***@***.******@***.***>>
Subject: Re: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)

Please post tech info and app screenshot as described at here<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcrystalidea%2Fmacs-fan-control%2Fblob%2Fmaster%2Fhow-to-post-tech-info.md&data=05%7C01%7C%7Ce51531d177a24891c93d08daf7e4be87%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638094859083807592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mBJ3z9I%2BZYrNwRi6lNHhNNn8Lruo%2FcPWIf9Sk%2F8JpBE%3D&reserved=0>.

-

**Comment by lucholeg** [comment] 2023-02-07 01:23
Good moring,

I´m checking if you have reviewed the issue with my fan. It is very noisy, over speeding and no control at all.


Gracias y saludes,

Luis Eduardo Gonzalez Ch
Cel 310 5751150

From: Luis Eduardo Gonzalez Ch ***@***.***>
Date: Friday, 20 January 2023, 8:21 AM
To: crystalidea/macs-fan-control ***@***.***>, crystalidea/macs-fan-control ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)
Hello,

Had you have the opportunity to review the issue? Any additional recommendations to manage the noisy fan?

Thanks.

Gracias y saludes,

Luis Eduardo Gonzalez Ch
310-5751150

De: Luis Eduardo Gonzalez Ch ***@***.***>
Enviado el: Monday, January 16, 2023 9:42 PM
Para: crystalidea/macs-fan-control ***@***.***>; crystalidea/macs-fan-control ***@***.***>
CC: Author ***@***.***>
Asunto: Re: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)

Hello,

Attached please find the screenshots requested.

Notice Fan is over speeding… but no control with the software.  Hope you can help in finding the right solution.

Gracias y saludes,

Luis Eduardo Gonzalez Ch
Cel 310 5751150

From: Kleuter ***@***.******@***.***>>
Date: Monday, 16 January 2023, 12:11 PM
To: crystalidea/macs-fan-control ***@***.******@***.***>>
Cc: lucholeg ***@***.******@***.***>>, Author ***@***.******@***.***>>
Subject: Re: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)

Please post tech info and app screenshot as described at here<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcrystalidea%2Fmacs-fan-control%2Fblob%2Fmaster%2Fhow-to-post-tech-info.md&data=05%7C01%7C%7Ce51531d177a24891c93d08daf7e4be87%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638094859083807592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mBJ3z9I%2BZYrNwRi6lNHhNNn8Lruo%2FcPWIf9Sk%2F8JpBE%3D&reserved=0>.

**Comment by lucholeg** [comment] 2023-04-11 10:14
Good morning,

I´m still waiting some support about the issue with my MAcbook air fan.  As reported it is overspeeding and no control at all.

Thanks

Gracias y saludes,

Luis Eduardo Gonzalez Ch
Cel 310 5751150

From: Luis Eduardo Gonzalez Ch ***@***.***>
Date: Friday, 20 January 2023, 8:21 AM
To: crystalidea/macs-fan-control ***@***.***>, crystalidea/macs-fan-control ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)
Hello,

Had you have the opportunity to review the issue? Any additional recommendations to manage the noisy fan?

Thanks.

Gracias y saludes,

Luis Eduardo Gonzalez Ch
310-5751150

De: Luis Eduardo Gonzalez Ch ***@***.***>
Enviado el: Monday, January 16, 2023 9:42 PM
Para: crystalidea/macs-fan-control ***@***.***>; crystalidea/macs-fan-control ***@***.***>
CC: Author ***@***.***>
Asunto: Re: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)

Hello,

Attached please find the screenshots requested.

Notice Fan is over speeding… but no control with the software.  Hope you can help in finding the right solution.

Gracias y saludes,

Luis Eduardo Gonzalez Ch
Cel 310 5751150

From: Kleuter ***@***.******@***.***>>
Date: Monday, 16 January 2023, 12:11 PM
To: crystalidea/macs-fan-control ***@***.******@***.***>>
Cc: lucholeg ***@***.******@***.***>>, Author ***@***.******@***.***>>
Subject: Re: [crystalidea/macs-fan-control] Fan at high speed but no Control at all (Issue #661)

Please post tech info and app screenshot as described at here<https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md>.

**Comment by kleuter** [comment] 2023-06-21 08:49
Duplicate of #66

**Closed by kleuter** 2023-06-21 08:49 UTC
