### ISSUE TITLE
App stopped responding after macOS Big Sur upgrade (e.g. 11.2->11.3)

### ISSUE THREAD

**Issue by sumoblatt66** [crystalidea/macs-fan-control#500] opened 2021-05-02 18:31 UTC
Hello,

When I try to start up Macs Fan Control the program don't show up and on the activity monitor shows that the program don't response on my M1 Mac Book Pro. I tried to reinstall the program but I don't help. 

best regards,

Lukas Maier

**Comment by kleuter** [comment] 2021-05-02 18:43
Dear,

Are you using the latest version of the app? (1.5.9)
https://crystalidea.com/downloads/macsfancontrol.zip

**Comment by sumoblatt66** [comment] 2021-05-02 18:50
hello, 

yes, I use the last version, I downloaded it from the official site. I tried it again with the link from you but it won't will work.

**Comment by kleuter** [comment] 2021-05-02 18:52
If it crashes, please post the crash log
https://bjango.com/help/crashlogmac/

**Comment by sumoblatt66** [comment] 2021-05-02 19:00
it don't crashes directly, but it don't work and on the activity monitor the program didn't response. I can't upload the file

**Comment by kleuter** [comment] 2021-05-02 19:14
Please post a screenshot of the app not responding

**Comment by sumoblatt66** [comment] 2021-05-02 19:50
I can't post a picture, because the app don't show up, I can only see in the activity monitor that the app is running and not response

**Comment by mwkolosov** [comment] 2021-05-05 11:06
I have the same bug. The program don't response after update to Big Sur 11.3/11.3.1

on previous version of Big Sur latest version worked fine

**Comment by kleuter** [comment] 2021-05-05 11:32
Can you please record a video?

**Comment by mwkolosov** [comment] 2021-05-05 11:39
https://drive.google.com/file/d/1dnbAMv3jcwE242HMi4d-NEpos_xuvLQC/view?usp=sharing

**Comment by kleuter** [comment] 2021-05-05 11:49
Thank you. Please attach this file:
~/Library/Preferences/com.crystalidea.macsfancontrol.plist

**Comment by mwkolosov** [comment] 2021-05-05 11:55
https://drive.google.com/file/d/1t8zsGJdtqOguNlmRBZLqtjR1WoeYmAov/view?usp=sharing

**Comment by kleuter** [comment] 2021-05-05 12:03
Thank you. Clearing preferences doesn't help?

killall "Macs Fan Control"
rm ~/Library/Preferences/com.crystalidea.macsfancontrol.plist
killall -u `id -u -n` cfprefsd

**Comment by mwkolosov** [comment] 2021-05-05 12:09
1. Unfortunately, it didn’t help. After updating the BigSur, I also tried to reinstalled the application
2. MacBook Pro M1

**Comment by kleuter** [comment] 2021-05-05 12:42
Thank you. Now.

Please send us these two files (zipped)
/Library/LaunchDaemons/com.crystalidea.macsfancontrol.smcwrite.plist
/Library/PrivilegedHelperTools/com.crystalidea.macsfancontrol.smcwrite

**Comment by mwkolosov** [comment] 2021-05-05 12:51
[Archive.zip](https://github.com/crystalidea/macs-fan-control/files/6427151/Archive.zip)

After `sudo launchctl unload /Library/LaunchDaemons/com.crystalidea.macsfancontrol.smcwrite.plist` program will launched - https://tppr.me/n8lhG

But not working correctly. Full blast not working

**Comment by kleuter** [comment] 2021-05-05 13:39
```
sudo launchctl load /Library/LaunchDaemons/com.crystalidea.macsfancontrol.smcwrite.plist
```

**Comment by mwkolosov** [comment] 2021-05-05 14:10
@kleuter It works now. Thank u

**Comment by kleuter** [comment] 2021-05-05 14:11
It's not a solution for most users though... can you please tell me
The app was working in macOS 11.2 and stopped working after upgrade to 11.3? Thank you.

**Comment by mwkolosov** [comment] 2021-05-05 14:18
Yes, exactly

**Comment by kleuter** [comment] 2021-05-05 15:13
I've just reproduce this problem after updating from 11.3 to 11.3.1, but it began to work after I renamed the app file name ("Macs Fan Control.app"). This is really strange.

**Comment by mwkolosov** [comment] 2021-05-05 18:00
Really very strange 🤔

**Comment by nathanphotographer** [comment] 2021-05-08 22:16
Macs fan control crashes after every restart or boot up on Mac 11.3.1, version 1.5.9. Runs fine after I run it. But upon boot up it crashes.

**Comment by kleuter** [comment] 2021-05-09 06:51
> Really very strange 🤔

I think it's because you had installed previously version (which is incompatible with M1) - 1.5.8, right?

@nathanphotographer
[crash report](https://bjango.com/help/crashlogmac/)?

**Comment by mwkolosov** [comment] 2021-05-09 07:16
No. 1.5.9 it’s first version of app on my Mac

**Comment by kleuter** [comment] 2021-05-10 12:44
@mwkolosov 
Actually, the smcwrite helper (com.crystalidea.macsfancontrol.smcwrite, you posted previously) is from version 1.5.8, 53904 bytes, new smcwrite in version 1.5.9 is 189712 bytes. 1.5.9 didn't upgrade it, but should have I suppose.

**Comment by kleuter** [comment] 2021-05-28 19:48
Should be fixed in 1.5.10 now I believe.

**Comment by mwkolosov** [comment] 2021-05-31 15:05
I just updated to v1.5.10

working fine

but in the beginning, I received this warning:

![Google Chrome_2021-05-31 6-00-52 PM@2x](https://user-images.githubusercontent.com/28948000/120212378-97774580-c23a-11eb-914e-33940864c5e8.jpg)

But after reopen all works great

**Comment by kleuter** [comment] 2021-05-31 20:11
@mwkolosov did you also have the initial issue with app that hangs?

**Comment by mwkolosov** [comment] 2021-06-01 06:21
@kleuter no, I didn't have

**Comment by FelixFalkovsky** [comment] 2021-08-28 11:49
<img width="332" alt="Снимок экрана 2021-08-28 в 14 48 34" src="https://user-images.githubusercontent.com/56316435/131216851-20013f04-7114-4229-bae6-a262dfea3aaa.png">
Хотел купить , но даже скачав якобы для ARM64 программа не работает , версия OS 11.5.2 Apple M1 Pro

**Comment by kleuter** [comment] 2021-08-29 07:07
Our main download is a universal app which is M1 compatible:
https://crystalidea.com/downloads/macsfancontrol.zip

**Closed** 2021-10-08 13:05 UTC
Labels: bug, Top priority, Done in beta, In progress, Apple Silicon
