### ISSUE TITLE
Temperature monitor stuck without power plug

### ISSUE THREAD

**Issue by GreenSug4r** [crystalidea/macs-fan-control#224] opened 2019-10-26 23:40 UTC
Hi, first thing first thank you for your excellent job on this program, second i have a very annoying issue on my MBP 2015 13", if i am using battery the monitor temperature is stock, isn't constantly updating like always, when i plug in the power cable it start updating temperature as always.
So the program is working fine until i have the power cable connected, otherwise is useless.

Do you know how can i solve this problem? Thank you in advance

<img width="822" alt="Schermata 2019-10-27 alle 01 34 30" src="https://user-images.githubusercontent.com/57050604/67627320-33b8b980-f85a-11e9-90d3-880cf8d8758d.png">

Macs Fan Control 1.5.0 [Qt 5.13.1]
MacBookPro12,1
CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz [2 cores]
GPU: Intel Iris Graphics 6100
macOS 10.15.0

Fans:
Right Side-min{1299}curr{0}max{6199}mode{0}

TempSensors:
TA0P (Ambient) - 34.25, 34.25
TB0T (Battery Max) - 28.1992, 28.1992
TB1T (Battery Sensor 1) - 28.2969, 28.2969
TB2T (Battery Sensor 2) - 27.0977, 27.0977
TBXT () - 28.1992, 28.1992
TC0C (CPU Core 1) - 54, 54
TC0E () - 67.8906, 67.8906
TC0F () - 67.8906, 67.8906
TC0P (CPU Proximity) - 49, 49
TC1C (CPU Core 2) - 55, 55
TCGC (GPU PECI) - 57, 57
TCSA () - 0, 0
TCXC (CPU PECI) - 67.8906, 67.8906
TH0A () - 35.875, 35.875
TH0B () - 34.625, 34.625
TH0C () - 34.625, 34.625
TH0F () - 246, 246
TH0R () - 206.625, 206.625
TH0V () - 34.0547, 34.0547
TH0a () - 35.875, 35.875
TH0b () - 34.625, 34.625
TH0c () - 34.625, 34.625
TH0x () - 34.625, 34.625
THSP () - 129, 129
TM0P (Memory Proximity) - 41.625, 41.625
TMLB () - 129, 129
TPCD (Platform Controller Hub Die) - 50, 50
TW0P () - 129, 129
Th1H (Heatsink Proximity) - 39.75, 39.75
Ts0P (Palm Rest) - 28.75, 28.75
Ts0S () - 129, 129
Ts1P () - 27.6875, 27.6875
Ts1S () - 129, 129
Ts2S () - 32.3359, 32.3359

Disk drives:
APPLE SSD SM0512G - 34

Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

Potentially conflicted app: iStat Menus 6
/Library/Application Support/iStat Menus 6/cities.db
/Library/Application Support/iStat Menus 6/bandwidth.db
/Library/Application Support/iStat Menus 6/iStat Menus Status.app
/Library/Application Support/iStat Menus 6/iStatMenusFans
/Library/Application Support/iStat Menus 6/uptime.db
/Library/Application Support/iStat Menus 6/iStatMenusAgent.app
/Library/Application Support/iStat Menus 6/iStatMenusDaemon
/Library/Application Support/iStat Menus 6/iStat Menus Updater.app
/Library/Application Support/iStat Menus 6/iStat Menus Uninstaller.app

**Comment by kleuter** [comment] 2019-11-04 20:48
Did you try to uninstall the iStat Menus 6 app?

**Comment by GreenSug4r** [comment] 2019-11-18 19:57
> Did you try to uninstall the iStat Menus 6 app?

Tried but same problem, and i have the same problem on iStat Menus 6, only intelPowerGadget displays the right display temperatures even when power plug isn't attached.

**Comment by kleuter** [comment] 2021-05-12 08:08
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/433

**Closed by kleuter** 2021-05-12 08:08 UTC
Labels: need more info
