### ISSUE TITLE
Discrete GPU temperature is not being read [fixed in v.1.5.8.1 beta, download here]

### ISSUE THREAD

**Issue by Rossh51** [crystalidea/macs-fan-control#400] opened 2020-09-27 00:52 UTC
### Download [version 1.5.8.1.26 beta](https://crystalidea.com/downloads/macsfancontrol_beta.zip)

Previously reported in 1.58 beta but not fixed in release. When Discrete GPU checked in Preferences there is no Temp reading for 5700XT GPU. Unchecking gives all readings as in previous versions. See screen shots with and without check box active.

 
![Screen Shot 2020-09-27 at 10 40 53 am](https://user-images.githubusercontent.com/44332031/94352994-7bba0f00-00af-11eb-8c20-974b16b1d95a.jpg)
![Screen Shot 2020-09-27 at 10 41 55 am](https://user-images.githubusercontent.com/44332031/94353000-8379b380-00af-11eb-9d61-e198cdda105b.jpg)

**Comment by kleuter** [comment] 2020-09-27 14:52
Looks like 5700XT temperature should be read using the SMC sensor GPU Die. Will do that, thanks for the follow up.

**Comment by deejaykris** [comment] 2020-09-29 15:48
Same thing on my MacBook Pro late 2013.

<img width="889" alt="MacsFanControl" src="https://user-images.githubusercontent.com/72092768/94581869-e3bd5080-027b-11eb-89ab-5774c5719dee.png">

**Comment by kleuter** [comment] 2020-09-30 09:29
**deejaykris**, 
Please run the complete command 
`ioreg -l > output.txt`
and post here output.txt (using the browser)

**Comment by Rossh51** [comment] 2020-09-30 09:47
[output.txt](https://github.com/crystalidea/macs-fan-control/files/5304585/output.txt)

**Comment by deejaykris** [comment] 2020-09-30 19:02
[output.txt](https://github.com/crystalidea/macs-fan-control/files/5307704/output.txt)

**Comment by kleuter** [comment] 2020-10-02 08:59
If possible, send a screenshot as well, please

**Comment by ikonkere** [comment] 2020-10-02 09:05
Same on mbp10,1 (late-2012):
<img width="817" alt="Screenshot 2020-10-02 at 12 04 11" src="https://user-images.githubusercontent.com/11472129/94906632-7db51100-04a7-11eb-8e79-9a5e58fc8d0a.png">
[output.txt](https://github.com/crystalidea/macs-fan-control/files/5316944/output.txt)

**Comment by eggicusroundplumpius** [comment] 2020-10-02 12:35
[output.txt](https://github.com/crystalidea/macs-fan-control/files/5317930/output.txt)
Same on 16 Inch MacBook Pro with 5600M graphics - it will not read either the Intel HD 630 or AMD 5600M directly, though GPU PECI still works when the option is disabled.

**Comment by pfk84** [comment] 2020-10-02 14:51
<img width="903" alt="screenshot mbp16" src="https://user-images.githubusercontent.com/18550587/94937071-6427bf80-04cf-11eb-8f0e-3f7fc51ccbf1.png">

**Comment by pfk84** [comment] 2020-10-02 14:52
<img width="1004" alt="Bildschirmfoto 2020-10-02 um 16 51 53" src="https://user-images.githubusercontent.com/18550587/94937234-9a653f00-04cf-11eb-9cb4-febca7780380.png">

**Comment by kleuter** [comment] 2020-10-02 21:52
Please try this test build and post your screenshot, thank you!
[macsfancontrol_beta.zip](https://github.com/crystalidea/macs-fan-control/files/5320478/macsfancontrol_beta.zip)

**Comment by Rossh51** [comment] 2020-10-03 02:24
Yes, this works with EGU option on or off. Thank you for this. Great work. 

There is now no ability to see individual GPU sensors however. Is it possible to have the option to toggle as we did before? 

Screen shots below.

![Screen Shot 2020-10-03 at 12 13 36 pm](https://user-images.githubusercontent.com/44332031/94981142-21b7be80-0573-11eb-8b0b-ac8cbdacf0b7.jpg)
![Screen Shot 2020-10-03 at 12 14 03 pm](https://user-images.githubusercontent.com/44332031/94981147-27150900-0573-11eb-97c7-d1b46e97d707.jpg)

**Comment by kleuter** [comment] 2020-10-03 10:52
Basically GPU Die has now more meaningful gpu model. Previous sensors people used will be displayed again in 1.5.8.1

**Comment by kleuter** [comment] 2020-10-03 11:00
### Download [version 1.5.8.1.25 beta](https://crystalidea.com/downloads/macsfancontrol_beta.zip) 
and post here your screenshots, thanks.

**Comment by Rossh51** [comment] 2020-10-03 12:10
Better again with some GPU information. I assume the GPU reading is what was listed as the GPU Diode?
![Screen Shot 2020-10-03 at 10 03 56 pm](https://user-images.githubusercontent.com/44332031/94991241-1f7e5000-05c5-11eb-85ac-fe428c0141d3.jpg)

**Comment by eggicusroundplumpius** [comment] 2020-10-03 12:15
![image](https://user-images.githubusercontent.com/15807103/94991331-5713da80-057a-11eb-8ee2-a45b7bbafa74.png)
Still no reading on the 5600M, but we now have a reading on the HD 630. I did try disabling auto-graphics switching to see if it just needed to have that GPU selected but it didn't do anything.

**Comment by kleuter** [comment] 2020-10-03 13:22
> Still no reading on the 5600M
Please post tech info as described at #407

**Comment by kleuter** [comment] 2020-10-03 13:23
> I assume the GPU reading is what was listed as the GPU Diode?
Exactly.

**Comment by lokmac** [comment] 2020-10-04 07:01
This fixed it for my MBP Late-2013 with GeForce GT 750M.

**Comment by pfk84** [comment] 2020-10-04 08:22
Intel UHD works now, thanks! However, it still cannot read the Radeon Pro 5500M; going to try my eGPU next week as well.
<img width="1004" alt="Bildschirmfoto 2020-10-04 um 10 20 45" src="https://user-images.githubusercontent.com/18550587/95010658-6868ef80-062b-11eb-9d49-d7c70d8cc88b.png">

**Comment by kleuter** [comment] 2020-10-04 19:30
All macbook pro users (16,1, 15,1) please try the update, it will display discrete GPU temperature, but please run also the [Valley benchmark](https://benchmark.unigine.com/valley) to make sure the temperature rises properly.
### Download [version 1.5.8.1.26 beta](https://crystalidea.com/downloads/macsfancontrol_beta.zip)

**Comment by eggicusroundplumpius** [comment] 2020-10-04 20:44
Okay, it seems to work but the temperature doesn’t report “accurately” - it’s always rounded to the nearest degree, which isn’t a problem and may be by design but worth nothing, I guess.

**Comment by deejaykris** [comment] 2020-10-04 20:50
This Beta Version works for my MacBook Pro 15" Late 2013

<img width="889" alt="MacsFanControl Beta" src="https://user-images.githubusercontent.com/72092768/95026754-ed87ef00-0693-11eb-82c9-528a5c483ce7.png">

**Comment by kleuter** [comment] 2020-10-05 08:39
@eggicusroundplumpius did you run the Valley benchmark? What was the max temp for 5600M?

**Comment by eggicusroundplumpius** [comment] 2020-10-05 08:49
The max was something like 79°, if I remember correctly.

**Comment by kleuter** [comment] 2020-10-05 08:50
Thanks

**Comment by pfk84** [comment] 2020-10-05 10:42
Works now, great! The highest temp I'd seen was 96°C, matches what other tools are saying. Also the eGPU works just fine...

**Comment by kleuter** [comment] 2020-10-05 11:30
Thanks! Which eGPU did you connect? Thanks.

**Comment by pfk84** [comment] 2020-10-05 12:58
Radeon RX 580
<img width="1004" alt="Bildschirmfoto 2020-10-05 um 12 26 22" src="https://user-images.githubusercontent.com/18550587/95082307-25864500-071b-11eb-8b99-536bb8bd1591.png">

**Comment by kleuter** [comment] 2020-10-05 13:43
Perfect, thanks!

**Comment by kleuter** [comment] 2020-10-05 13:43
Fixed in 1.5.8.1

**Closed by kleuter** 2020-10-05 13:43 UTC
Labels: Top priority, bug
