### ISSUE TITLE
launch at system boot

### ISSUE THREAD

**Issue by thomasonlineva** [crystalidea/macs-fan-control#564] opened 2021-12-04 15:39 UTC
my computer overheats and goes into safe mode with in a few moments after boot.  if i gert distracted for a few minutes or mistype my password my machine can lock, is there.  a way to launch at system boot?, rather than login?

**Comment by kleuter** [comment] 2021-12-20 16:12
Duplicate of 
https://github.com/crystalidea/macs-fan-control/issues/2

**Closed by kleuter** 2021-12-20 16:12 UTC
