### ISSUE TITLE
Ability to set fan speed with a Terminal command

### ISSUE THREAD

**Issue by Arcrammer** [crystalidea/macs-fan-control#531] opened 2021-07-23 18:02 UTC
It looks like there are a few commands available when launching the app through Terminal, but it would be nice to be able to set the fan speed through Terminal commands rather than point-and-click. Would this be possible in a future release?

**Comment by kleuter** [comment] 2021-08-04 05:13
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/162

**Closed by kleuter** 2021-08-04 05:13 UTC
Labels: feature request
