### ISSUE TITLE
Change Presets via command line / AppleScript / URI?

### ISSUE THREAD

**Issue by orchetect** [crystalidea/macs-fan-control#341] opened 2020-05-28 06:11 UTC
It would be great if we could interact with Macs Fan Control externally. The most useful feature to control would be changing the active preset.

Possible methods:

- command line utility that can accept the preset name as an argument
- adding a Scripting Bridge dictionary to the app so that AppleScript can tell Macs Fan Control to do things, like change the active preset
- adding a custom URI handler, such as macsfancontrol://setactivepreset/_PresetName_/

Any of those solutions would be fine, or all of them would be great.

Use case: during the day, I want a more moderate preset because I work in a quiet studio so I want the fans to run slower, but when the screen saver turns on or the computer is left idle overnight, I want a more aggressive fan preset to engage to cool certain components more.

Those system event triggers can be handled in a 3rd party macro app like Keyboard Maestro, but it needs a way to communicate with Macs Fan Control to tell it to change a preset.

**Comment by kleuter** [comment] 2020-10-02 09:25
Duplicate of #373

**Closed by kleuter** 2020-10-02 09:25 UTC
Labels: feature request
