### ISSUE TITLE
Mac Fan Control pop up at every log in on Ventura

### ISSUE THREAD

**Issue by jodyel** [crystalidea/macs-fan-control#656] opened 2022-12-16 22:19 UTC
How can I get this Mac Fan Control pop up to stop coming up every time I start my Mac? This only started with Ventura.

I'd like to disable it otherwise I will just have to get rid of Mac Fan Control but I'd like to keep it.

Currently I have it uninstalled and have noticed that it still appears in my login items even though uninstalled.

Can someone help me with this? Thanks.

P.S. Am not able to take a screenshot of it because it is overlaid on everything even webpages. Nothing gets rid of it unless I click on cancel or enter my password.

**Comment by Schnuff007** [comment] 2022-12-24 09:08
Have exactly the same problem!

**Comment by kleuter** [comment] 2022-12-24 09:40
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

If you record a video, that would be even better.

**Comment by jodyel** [comment] 2022-12-24 12:30
I already stated a pop up could not be done. And no idea how to record a screen.

I currently have this uninstalled and it is still showing in my login items. Why does it not completely uninstall? How do I get it out of my login items for good?

If there is no way to disable this password pop up for every start up, then this will remain uninstalled and I won't use it anymore. Why in the world would you design it to be so intrusive like that? Can that not be changed?

It's a real shame as it is a good product and I have liked using it. But there are other options that don't intrude on the user so will have to consider using one of them.

**Comment by jodyel** [comment] 2022-12-24 12:54
I figured out how to get it out of my login items and won't be installing it again unless you do something to remove the need for the helper login with password at every start up.

And in case anyone else would like to know how to get rid of it in their login items too, here is the answer for that.

https://www.droidwin.com/remove-deleted-apps-from-background-login-items-in-ventura/

**Comment by kleuter** [comment] 2023-03-04 10:28
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/667

**Closed by kleuter** 2023-03-04 10:28 UTC
