### ISSUE TITLE
Fans keep running during sleep

### ISSUE THREAD

**Issue by MaximumBlast** [crystalidea/macs-fan-control#282] opened 2020-02-04 21:46 UTC
Hi Using Macs Fan Control 1.5.4 on a 2014 iMac.
A few days ago the fans started to keep running when 
i send the computer to sleep. They used to not do that
in the past. Wondering what has caused this..

Heres the Tech Data.

Do you have an idea whats wrong?

<img width="1125" alt="Bildschirmfoto 2020-02-04 um 22 42 57" src="https://user-images.githubusercontent.com/60583831/73790067-2b98e000-47a0-11ea-84e4-0f1d32e7b765.png">

<img width="610" alt="Bildschirmfoto 2020-02-04 um 22 43 51" src="https://user-images.githubusercontent.com/60583831/73790118-39e6fc00-47a0-11ea-8381-86cf50e10ef7.png">

[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/4337372/tech_info.txt)

**Comment by MaximumBlast** [comment] 2020-02-04 21:50
I should mention i am using a non OEM Apple HDD in that machine, thats why i am using Macs Fan Control in the first place.

**Comment by kleuter** [comment] 2020-03-16 10:48
Duplicate of #208

**Closed by kleuter** 2020-03-16 10:48 UTC
Labels: bug, need more info
