### ISSUE TITLE
App looses control

### ISSUE THREAD

**Issue by PreciselyNothing** [crystalidea/macs-fan-control#272] opened 2020-01-25 20:06 UTC
I am not sure what triggers this event, but several times now I have come home to my fans running full speed even though none of the sensor input warrants that behavior.  I am unable to reduce the speed manually or "automatically" and the system must be reset for the fans to return back under control of the app.
App has work flawlessly for years, now having an issue. Not sure if it coincides with "Mac Fan Control" update for not.

Running on iMac (Mid 2011)
macOS High Sierra, V 10.13.6 (computer can not be updated higher eg, no 10.14)

**Comment by kleuter** [comment] 2020-01-29 21:29
Can you please post technical information? Menu More -> Copy Technical info

**Comment by kleuter** [comment] 2020-01-29 21:33
One more similar report from a customer
Hello,

> HDD sensor randomly shifts to max RPM even though it was set to activate at a temp range of 42-70.  HDD rarely climbs above 30.  When I restart my computer, it goes back to normal.  However, this is a persistent issue that requires frequent restarting of the computer. Technical details are below.
[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/4130812/tech_info.txt)

**Comment by kleuter** [comment] 2021-05-12 08:20
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/464

**Closed by kleuter** 2021-05-12 08:20 UTC
Labels: Top priority, bug, need more info
