### ISSUE TITLE
Macs Fan Control.app Latest Version

### ISSUE THREAD

**Issue by k-inali** [crystalidea/macs-fan-control#668] opened 2023-02-19 10:29 UTC
Macs Fan Control.app Latest Version User, the Windows version is a trial version of the latest version.

In case of Radeon RX5700XT, GPU temperature is displayed when booted on Windows, but not when booted on Mac.
On the Radeon RX580, the GPU temperature is displayed on both Windows and Mac.

I don't know the cause of this.

**Comment by kleuter** [comment] 2023-02-19 14:15
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/608

**Closed by kleuter** 2023-02-19 14:15 UTC
