### ISSUE TITLE
Can't detect temperature of CPU

### ISSUE THREAD

**Issue by Kennnnn7** [crystalidea/macs-fan-control#750] opened 2024-05-20 09:01 UTC
Hi,

Why "Macs Fan Control" can't detect temperature of CPU? Any setting should be noticed? Thanks.
Using macOS 14.1 M3 Max, app version: 1.5.16

![2024-05-20 17 00 59](https://github.com/crystalidea/macs-fan-control/assets/141208404/28c69d45-2131-4e48-8ec5-0031ddc3a1f3)
![2024-05-20 17 01 19](https://github.com/crystalidea/macs-fan-control/assets/141208404/3faa8a96-2890-4d77-a88f-3c47b111f3d2)

**Comment by Kennnnn7** [comment] 2024-06-07 11:29
hello, any ideas?

**Comment by kleuter** [comment] 2024-11-22 10:45
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/716

**Closed by kleuter** 2024-11-22 10:45 UTC
Labels: bug
