### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by BarathPA** [crystalidea/macs-fan-control#738] opened 2024-02-17 10:12 UTC
The fans are not turning on from the app. I throttled the device to see if it works, and the fans turn on. Once fans are on, I can control via app. But if device goes to sleep or fans are left at auto, app looses control and regains access to fan only if I fully throttle device again. 

[MacBookPro18,1_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/14318432/MacBookPro18.1_tech_info.zip)

<img width="864" alt="Screenshot 2024-02-17 at 3 35 45 PM" src="https://github.com/crystalidea/macs-fan-control/assets/52395520/8b623489-b0c3-421f-a1e9-8679bb8770f2">

**Comment by kleuter** [comment] 2024-02-19 09:08
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/733

**Closed by kleuter** 2024-02-19 09:08 UTC
Labels: bug
