### ISSUE TITLE
Empty window after upgrade to v1.5.8 (macOS 10.12 Sierra)

### ISSUE THREAD

**Issue by lucoflove** [crystalidea/macs-fan-control#402] opened 2020-09-27 20:14 UTC
Good evening, I updatetp Mac Fan Control as notice. Nothing works after the upgrade. You can't see anything. You can't access the program. I've been set up and cleaned up from the old files. After the reistallation of version 1.4.3, which used to work, now on sees only the attached image and nothing else. All settings have been lost and fan controls are also lost. I also bought the Pro version which no longer works. Now I don't see anything. I have delete the program.
Let me know. Thank you

![PHOTO 2](https://user-images.githubusercontent.com/33143588/94374716-7809a500-010e-11eb-8ff9-b271b2ac2429.png)
![PHOTO1- ACTUAL PAGE](https://user-images.githubusercontent.com/33143588/94374721-7fc94980-010e-11eb-8701-714e54fdc0b2.png)

**Comment by kleuter** [comment] 2020-09-27 21:04
SMC reset should help.

**Comment by kleuter** [comment] 2020-09-27 21:04
https://support.apple.com/en-us/HT201295

**Comment by npglambert** [comment] 2020-09-28 20:10
I just down graded to 1.5.7 as I had the same problem with 1.5.8. No SMC reset, just deleted the update & re-installed the older version from a backup.

**Comment by mihhhy** [comment] 2020-09-28 20:21
Same thing here. Went from 1.4.something to 1.5.8 just now (late 2013 iMac 27'', os x 10.12.6) and the thing doesn't even open; MFC is sitting in my Applications folder and in the Dock, but nothing happens when I try to run it... Did the SMC reset - nothing.

**Comment by mihhhy** [comment] 2020-09-28 20:33
Just went back to 1.5.6.19 and works like a charm

**Comment by npglambert** [comment] 2020-09-28 21:46
Glad you got it sorted mihhhy, I hope they find the cause & issue another update.

**Comment by lucoflove** [comment] 2020-09-29 10:31
> Good evening, I updatetp Mac Fan Control as notice. Nothing works after the upgrade. You can't see anything. You can't access the program. I've been set up and cleaned up from the old files. After the reistallation of version 1.4.3, which used to work, now on sees only the attached image and nothing else. All settings have been lost and fan controls are also lost. I also bought the Pro version which no longer works. Now I don't see anything. I have delete the program.
> Let me know. Thank you
> 
> ![PHOTO 2](https://user-images.githubusercontent.com/33143588/94374716-7809a500-010e-11eb-8ff9-b271b2ac2429.png)
> ![PHOTO1- ACTUAL PAGE](https://user-images.githubusercontent.com/33143588/94374721-7fc94980-010e-11eb-8701-714e54fdc0b2.png)

I have delete the 1.5.8 version and the others, and re installed from backup like you did.
Unfortunately the icon is back in the traybar but no longer shows any fan speed, nor the temperatures as seen before. At this point I also doubt how it works.

**Comment by kleuter** [comment] 2020-09-29 11:04
This happens because a problem with SMC, not the app.

**Comment by kleuter** [comment] 2020-09-29 14:45
Please send us the technical data copied from the More menu.

**Comment by lucoflove** [comment] 2020-09-29 17:03
I have reset SMC more, and more times, without change nothing. Hi
[Data tecnical info.txt](https://github.com/crystalidea/macs-fan-control/files/5300690/Data.tecnical.info.txt)

**Comment by kleuter** [comment] 2020-09-29 17:31
So 1.5.7 works, but 1.5.8 doesn't right?

**Comment by lucoflove** [comment] 2020-09-29 17:34
No, absolutely not. It was just after the update to 1.5.8 that the soft went into tilt.

**Comment by kleuter** [comment] 2020-09-29 17:35
Thanks, working on a fix right now. Need a couple of hours. Please stay tuned.

**Comment by lucoflove** [comment] 2020-09-29 18:35
Ah! I had forgotten that I also tried installing a version earlier than the one that is installed now. If I'm not mistaken it was the 1.5.6 and after booting I returned this image; above is written: fan control not available.
Mac fan control couldn't connect with the app to enable fan control or speed adjustment.
![Schermata 2020-09-29 alle 13 33 48](https://user-images.githubusercontent.com/33143588/94601147-5685f600-0293-11eb-9d10-ee3e83d6dbef.png)

**Comment by kleuter** [comment] 2020-09-29 22:21
Anything related to Macs Fan Control in Utilities -> Console upon starting the app?

**Comment by lucoflove** [comment] 2020-09-30 04:23
Yes, I have only this:
default	06:21:23.309675 +0200	Macs Fan Control	Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"

**Comment by lucoflove** [comment] 2020-09-30 04:32
I have to serch SIMBL.osax and I open it: this is the image
![Schermata 2020-09-30 alle 06 30 39](https://user-images.githubusercontent.com/33143588/94643269-b35ecc00-02e6-11eb-8c80-7a3e04c94145.png)

**Comment by lucoflove** [comment] 2020-09-30 04:49
you see asks to insert a symbol: but what symbol?
default	06:21:23.309675 +0200	Macs Fan Control	Performance: **Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"**

**Comment by kleuter** [comment] 2020-09-30 10:29
No, it's all not related. please stay tuned, working on a fix

**Comment by kleuter** [comment] 2020-09-30 14:43
Finally installed macOS 10.12 (big issue in 2020) and reproduced the bug. Will be fixed soon

**Comment by kleuter** [comment] 2020-09-30 19:29
Here's the fixed version (need to do some more checks before release)
[macsfancontrol.zip](https://github.com/crystalidea/macs-fan-control/files/5307846/macsfancontrol.zip)

 Displaying of discrete GPU temperature is available on macOS 10.13 and later now.

**Comment by lucoflove** [comment] 2020-09-30 19:46
Sorry, but we're not there at all. In fact, things have gotten worse. Immediately I made a simple copy paste into the folder, then replacing the previous soft, and did not give any indication of fan turns and temperatures in the tray bar. PHOTO1 
So I unseated everything and reinstalled your latest version. At startup it only gave me the ability to monitor but not control.
I'm sorry, but it's not working.
![Schermata 2020-09-30 alle 21 33 26](https://user-images.githubusercontent.com/33143588/94732283-560a5f80-0366-11eb-8f61-ffd620753e81.png)
![Schermata 2020-09-30 alle 21 36 37](https://user-images.githubusercontent.com/33143588/94732294-59055000-0366-11eb-99a9-d610488195ee.png)

**Comment by kleuter** [comment] 2020-09-30 19:48
1. Quit the app
2. run these commands in Terminal:
`sudo launchctl unload /Library/LaunchDaemons/com.crystalidea.macsfancontrol.smcwrite.plist 
sudo rm /Library/LaunchDaemons/com.crystalidea.macsfancontrol.smcwrite.plist 
sudo rm /Library/PrivilegedHelperTools/com.crystalidea.macsfancontrol.smcwrite `
3. Start the app again

**Comment by lucoflove** [comment] 2020-09-30 19:54
I launched in Terminal ONE ONLY RIGO at a time, not both. At the first I entered the passw. Ok?

**Comment by lucoflove** [comment] 2020-09-30 19:54
RIGO is LINE

**Comment by kleuter** [comment] 2020-09-30 19:55
One line is a command, enter the password when needed.

**Comment by lucoflove** [comment] 2020-09-30 20:03
The fan in manual, is OK. But NO INFO IN TRAYBAR
Sorry
Maybe I messed up writing the three commands in the Terminal. I entered them twice.

**Comment by kleuter** [comment] 2020-09-30 20:08
> NO INFO IN TRAYBAR
Use the preferences window to adjust which menubar info to display.

**Comment by lucoflove** [comment] 2020-09-30 20:12
Sorry Kleuter: what preferences window? Mac Preference o Macs Fan?

**Comment by kleuter** [comment] 2020-09-30 20:13
![image](https://user-images.githubusercontent.com/2600624/94734913-34ab7280-036a-11eb-9d37-3cc23ef2c0db.png)

**Comment by lucoflove** [comment] 2020-09-30 20:17
FANTASTIC. NOW WORK FINE. SORRY BUT I DIDN'T REMEMBER THE BAR MENU. Sorry

**Comment by lucoflove** [comment] 2020-09-30 20:18
NOW WORK FINE NOW JOIN GREAT, AND TO THANK YOU I WANT TO BUY THE PRO LICENSE, EVEN IF I DON'T USE IT. THANK YOU SO MUCH YET

**Comment by lucoflove** [comment] 2020-09-30 20:22
But I have a question for you; but it was not possible to create a .pref installation file, in order to install this very useful soft in System Preferences?

**Comment by kleuter** [comment] 2020-10-01 08:21
https://github.com/crystalidea/macs-fan-control/issues/10

**Comment by kleuter** [comment] 2020-10-01 09:43
Fixed

**Closed by kleuter** 2020-10-01 09:43 UTC
Labels: Top priority, bug, need more info
