### ISSUE TITLE
A question: Will the fan speed increases if set based on GPU, while the CPU surges?

### ISSUE THREAD

**Issue by siaomingjeng** [crystalidea/macs-fan-control#142] opened 2018-12-12 05:26 UTC
Not an issue, but question!
Since we can only set the fan based on one sensor, I want to know how the fun speed acts when the sensor we set is not high, while the other sensors we don't set go very high?
Does the default/auto rule still apply on not-set sensors?
Thanks very much!

**Comment by kleuter** [comment] 2018-12-30 13:32
"Does the default/auto rule still apply on not-set sensors?"
No if you use custom fan curve. 
Duplicate of #3

**Comment by kleuter** [comment] 2018-12-30 13:32
Duplicate of #3

**Closed by kleuter** 2018-12-30 13:32 UTC
