### ISSUE TITLE
Mac M3 Pro (Apple Chip) updated with macOS Sequoia 15.0 App not working now

### ISSUE THREAD

**Issue by mortix003** [crystalidea/macs-fan-control#776] opened 2024-09-18 20:29 UTC
I was using Macs Fan Control for months without an issue. Yesterday I updated the operating system to Sequoia 15.0 and now the app doesn't turn on the fans at any configuration. Not with custom speed and not with max speed.

I deleted and reinstalled the app and still nothing.

Thanks for your help.

Mat

**Comment by demtsev** [comment] 2024-09-19 18:57
Same for me! Need the fix asap

**Comment by Suharichek** [comment] 2024-09-19 22:00
Same thing... Please repair it 🙏🏼

**Comment by G-r-i-n-c-h** [comment] 2024-09-20 14:52
yeap just updated to Sequoia and its dead

**Comment by kleuter** [comment] 2024-09-20 17:57
Tech info, please
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by Suharichek** [comment] 2024-09-20 18:20
Here's my tech info 
[Mac15,6_tech_info.zip](https://github.com/user-attachments/files/17079183/Mac15.6_tech_info.zip)

**Comment by Suharichek** [comment] 2024-09-20 18:21
Here's my tech info and app screenshot
[Mac15,6_tech_info.zip](https://github.com/user-attachments/files/17079189/Mac15.6_tech_info.zip)
![CleanShot 2024-09-20 at 21 20 36@2x](https://github.com/user-attachments/assets/1b202f58-b9e1-4d25-a434-53c32227aa30)

**Comment by Suharichek** [comment] 2024-09-20 18:26
Here's my tech info 
[Mac15,6_tech_info.zip](https://github.com/user-attachments/files/17079233/Mac15.6_tech_info.zip)

**Comment by Suharichek** [comment] 2024-09-20 18:29
Here's my tech info 
[Mac15,6_tech_info.zip](https://github.com/user-attachments/files/17079267/Mac15.6_tech_info.zip)

**Comment by mortix003** [comment] 2024-09-20 18:37
Here's my tech info
[Mac15,6_tech_info.zip](https://github.com/user-attachments/files/17079696/Mac15.6_tech_info.zip)

**Comment by Suharichek** [comment] 2024-09-20 19:14
Now it's working. I don't know did you do smth, but thanks 😊

**Comment by jake765111** [comment] 2024-09-20 21:33
Same here! It seemed to work for a bit, Now I can't control at all!
Please fix! I would even pay for a fix or donate! This is very important to me!
Thankyou!

**Comment by cigsz** [comment] 2024-09-21 17:08
Looks like this is not just MacOS 15 Sequoia issue as it also stopped working for me after updating to MacOS 14.7 Sonoma

**Comment by G-r-i-n-c-h** [comment] 2024-09-22 09:24
Here's my tech info
[MacBookPro20,2_tech_info.zip](https://github.com/user-attachments/files/17088979/MacBookPro20.2_tech_info.zip)

**Comment by Valencia-28** [comment] 2024-09-23 15:01
It looks like the Sequoia 15.0 just killed Mac Fan app. Once it launched suddenly in full blast, but after restarting it's dead.

[Mac15,6_tech_info.zip](https://github.com/user-attachments/files/17099549/Mac15.6_tech_info.zip)

**Comment by Valencia-28** [comment] 2024-09-23 15:03
> Looks like this is not just MacOS 15 Sequoia issue as it also stopped working for me after updating to MacOS 14.7 Sonoma

I kept from installing Sequoia for long, and Mac Fan worked with Sonoma perfectly.

**Comment by cigsz** [comment] 2024-09-23 15:55
> > Looks like this is not just MacOS 15 Sequoia issue as it also stopped working for me after updating to MacOS 14.7 Sonoma
> 
> I kept from installing Sequoia for long, and Mac Fan worked with Sonoma perfectly.

Pretty sure this has to be MacOS issue because I can't even control fans with iStat. 2 different apps not working.

**Comment by Juanse9418** [comment] 2024-09-24 02:17
I also have the same problem, do you know who is in charge of solving this? Apple or the app? Maybe there is a solution or Apple will no longer let you manage the fans, hopefully it will be solved soon.
Do you know what other means we have to deliver these damages?

**Comment by Valencia-28** [comment] 2024-09-24 17:50
> I also have the same problem, do you know who is in charge of solving this? Apple or the app? Maybe there is a solution or Apple will no longer let you manage the fans, hopefully it will be solved soon. Do you know what other means we have to deliver these damages?

apple always doesn't care about your problems. Do not expect a reaction from apple. Basically, if you have problems, apple doesn't care about you. This is the company's position

**Comment by Aquariurn** [comment] 2024-09-25 04:53
I have same issue after update my Macbook Pro 14(M3 Pro).
This is  my tech info.
[MacBookPro20,2_tech_info.zip](https://github.com/user-attachments/files/17125187/MacBookPro20.2_tech_info.zip)

**Comment by Valencia-28** [comment] 2024-09-27 17:14
> > I also have the same problem, do you know who is in charge of solving this? Apple or the app? Maybe there is a solution or Apple will no longer let you manage the fans, hopefully it will be solved soon. Do you know what other means we have to deliver these damages?
> 
> apple always doesn't care about your problems. Do not expect a reaction from apple. Basically, if you have problems, apple doesn't care about you. This is the company's position

100% agree!
Microsoft, Adobe, Apple and many more - just spend your money and get out, regular company policy...

**Comment by Valencia-28** [comment] 2024-09-27 17:29
> I also have the same problem, do you know who is in charge of solving this? Apple or the app? 

It looks like Apple made some changes to Sequoia and now Mac Fan Control cant actually CONTROL fans if you decide to run them. I see that I can use Full Blast only when I use Lightroom import more (100% usage of CPU) then after 45C macbooks starts its fans, in this momen Mac Control can control the fans.

Please, don't expect that Apple will fix it, they did it for purpose.  Another thing if Mac Fan Control developers can fight this problem (I hope they can, otherwise the app became pretty much useless)

**Comment by JEMcats** [comment] 2024-09-29 20:11
I’m having the same problem, and I can’t see my CPU core temperatures either. If anyone knows how to fix this, please let me know!

**Comment by JEMcats** [comment] 2024-09-30 01:07
if you are looking for the CPU core temperatures for the MacBookPro20,2, the solution is to download the beta. [#721](https://github.com/crystalidea/macs-fan-control/issues/721)

**Comment by G-r-i-n-c-h** [comment] 2024-09-30 08:36
Still no beta or any workaround ?

**Comment by qvantyy** [comment] 2024-09-30 17:20
developers when will the update come out it's just horrible in games at 90+ temperature

**Comment by Aquariurn** [comment] 2024-09-30 19:48
After I added comment this issue, I can't wait for update. So I'm downgrading macOS 15 to 14.7, but it still don't work >:(
It's so funny Apple. My hands and macbook are burning. >>>:(((

Please give me the update ToT

[MacBookPro20,2_tech_info.zip](https://github.com/user-attachments/files/17195723/MacBookPro20.2_tech_info.zip)

**Comment by jake765111** [comment] 2024-10-02 01:21
I worry apple is locking down their devices more, If you want your option to be heard about users wanting to be able to control their fans, I suggest submitting feedback to apple. 
Hopefully it's just a bug. 
https://www.apple.com/feedback/

**Comment by OstapStad** [comment] 2024-10-02 07:13
Same problem here. Seems to be a problem with Macs Fan Control temperature monitoring system. Other apps (e.g. TG Pro) works normally. Can't wait to get an update from the team.
<img width="731" alt="Screenshot 2024-10-02 at 09 01 14" src="https://github.com/user-attachments/assets/874188d9-f7ac-49e3-b64a-2911771bbd34">
<img width="996" alt="Screenshot 2024-10-02 at 09 02 49" src="https://github.com/user-attachments/assets/60227c86-eac4-496f-a5e3-c824cf0d4b0e">

**Comment by cigsz** [comment] 2024-10-02 13:51
> Same problem here. Seems to be a problem with Macs Fan Control temperature monitoring system. Other apps (e.g. TG Pro) works normally. Can't wait to get an update from the team. <img alt="Screenshot 2024-10-02 at 09 01 14" width="731" src="https://private-user-images.githubusercontent.com/48406325/372763935-874188d9-f7ac-49e3-b64a-2911771bbd34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzcxODYsIm5iZiI6MTcyNzg3Njg4NiwicGF0aCI6Ii80ODQwNjMyNS8zNzI3NjM5MzUtODc0MTg4ZDktZjdhYy00OWUzLWI2NGEtMjkxMTc3MWJiZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzY1NjgxOWFjN2JmZDc5NDM2NjdkMjBlNzU1YjAyZjBiZTY0MDBhODIyZDdjYTI5ZWU3YzQ1ZTBiZDJjNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._oVDl66Q-tRoqH0YbL3jlsmdvURzau7kppllJVzxh5A"> <img alt="Screenshot 2024-10-02 at 09 02 49" width="996" src="https://private-user-images.githubusercontent.com/48406325/372763940-60227c86-eac4-496f-a5e3-c824cf0d4b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzcxODYsIm5iZiI6MTcyNzg3Njg4NiwicGF0aCI6Ii80ODQwNjMyNS8zNzI3NjM5NDAtNjAyMjdjODYtZWFjNC00OTZmLWE1ZTMtYzgyNGNmMGQ0YjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyN2ZkZjI5OWZjMmI5OTA4ZDM2MDEyZGY4OWY4YTIyNjNlYzk3MDljZjg3OTExMDllNDdhNGQwYjliNWI4MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xVp4xBuMu5K_wrWhBVjz3rvy8BHTZawYFXVSHYc3VPA">

TG Pro doesn't work for me either. Sensors work but not a chance to manually start fans. 
It's 3rd app that can't start fans to spin. 
Apple did break something (or they did that on purpose) with 14.7 Sonoma and Sequoia.

**Comment by OstapStad** [comment] 2024-10-02 13:53
It will unlock the fans when you hit 90 degrees C.

**Comment by qvantyy** [comment] 2024-10-03 19:18
heyyyyyyyyyyyyyyyyy bro

**Comment by masfahru** [comment] 2024-10-04 01:44
Confirmed to work on macOS Sequoia 15.0.1

**Comment by jake765111** [comment] 2024-10-04 15:32
Someone said 15.0.1 fixed it, but deleted their comment, can anyone confirm or deny?

**Comment by G-r-i-n-c-h** [comment] 2024-10-04 15:35
Just updated to 15.0.1. same still does not work.

**Comment by Suharichek** [comment] 2024-10-04 19:42
Confirm

**Comment by mortix003** [comment] 2024-10-05 04:43
Updated to 15.0.1 and still not working here

**Comment by G-r-i-n-c-h** [comment] 2024-10-10 19:20
Still nothing ?

**Comment by jake765111** [comment] 2024-10-10 22:26
> Since things are still the same for about three weeks now, is there a similar app that still works with Sequoia 15.0.1 and that someone here can recommend? 

Nothing else works that I've tried. I think apple broke it intentionally, because lots of fans noise is "unprofessional" and indicates a low quality laptop. 
Apple is overly obsessed with their image and has always chosen over-heating and throttling, rather than running their fans.

**Comment by OstapStad** [comment] 2024-10-10 22:50
Seems like there's no news on that topic

**Comment by Valencia-28** [comment] 2024-10-11 15:43
> Since things are still the same for about three weeks now, is there a similar app that still works with Sequoia 15.0.1 and that someone here can recommend?

I hav tried:
- Istat Menus
- TG Pro
Nothing works as it should.

**Comment by Valencia-28** [comment] 2024-10-11 15:50
Thanks to Apple - now my work in Lightroom looks the following.

Dead fans bellow 77C degree, than fans starting rapidly, 8seconds of noise and fans are done with cooling :)

Its so ridicules!  A way better to run two fans on M3 Pro at 4200 RPM you hardly can hear them. 
But Apples knows it better :)

When I use patch tool in the Lightroom I experience fans running on their maximum for 4-6seconds and then they are off again. Amazing!

**Comment by OstapStad** [comment] 2024-10-11 15:51
>   Nothing works as it should.

TG Pro works as it should, but you have to wait until the CPU reaches ~90 degrees C. Also, I created a custom temperature curve, so the fans don't turn off after 20 seconds of "jet mode" cooling.

**Comment by Valencia-28** [comment] 2024-10-11 15:53
> TG Pro works as it should, but you have to wait until the CPU reaches ~90 degrees C

Then it doesnt work as it Should!
If I cant control fans manually - it means app doesnt work.

**Comment by Juanse9418** [comment] 2024-10-11 16:34
I have a 14-inch MacBook with the M3 Pro, and I haven’t updated to the new one yet. Luckily, the app still works. If you can downgrade to a previous system, it might work. In my case, on Sonoma 14.4, the fan control app runs smoothly.

**Comment by jake765111** [comment] 2024-10-11 21:07
> I have a 14-inch MacBook with the M3 Pro, and I haven’t updated to the new one yet. Luckily, the app still works. If you can downgrade to a previous system, it might work. In my case, on Sonoma 14.4, the fan control app runs smoothly.

I downgraded to 14.4.1, It still does not work. Im guessing apple bricked something in the SMC. This is a big enough issue to cause me not to get another Mac, as it drives me nuts that apple would rather throttle the CPU, rather than run the fans. 

Once again, Leaving feedback may help apple realize that users care about this issue. 
https://www.apple.com/feedback/

**Comment by Valencia-28** [comment] 2024-10-17 15:20
> Once again, Leaving feedback may help apple realize that users care about this issue. https://www.apple.com/feedback/

There is no need to be so naive in believing that Apple does not know, what changes they have made and what they will lead to.
Moreover, never expect Apple to react to your complaints, they have not cared about their customers for a long time and will no start to care :)

**Comment by cigsz** [comment] 2024-10-17 16:27
Has anyone updated to 14.7.1 Sonoma or 15.1 Sequoia and can confirm if it still is not working in beta builds?
I have filed 2 feedbacks regarding this (first right after I updated and the second few days ago) and both of them show that there are no similar reports 🤷🏼‍♂️

**Comment by jake765111** [comment] 2024-10-17 23:37
> 
> 
> > Once again, Leaving feedback may help apple realize that users care about this issue. https://www.apple.com/feedback/
> 
> 
> 
> There is no need to be so naive in believing that Apple does not know, what changes they have made and what they will lead to.
> 
> Moreover, never expect Apple to react to your complaints, they have not cared about their customers for a long time and will no start to care :)

I agree they don't care about their customer's complaints, and feedback is almost certainly pointless, but if users complain, they will at least realize that there is users who care about this, possibly resulting in a "feature" in the future, although highly unlikely. I agree, they certainly won't change anything.  I never said they don't know what changes they made, and what it will lead to, unless it's a bug. 
Have a good day. :)

**Comment by JEMcats** [comment] 2024-10-18 00:12
I have opened a community discussion for this problem please get people to upvote it and maybe someone at Apple will see it. [discussion](https://discussions.apple.com/thread/255807028?sortBy=rank)

**Comment by cigsz** [comment] 2024-10-19 13:11
I have updated to Sonoma 14.7.1 RC2 and I'm still not able to control my fans with any app. 
Apple has been a joke for the past 2 years.

**Comment by laggage** [comment] 2024-10-20 02:54
Smae, Not work with app silicon, os version: 15.0.1

**Comment by chang2000** [comment] 2024-10-25 21:44
![SS-2024-10-25-14 41 16@2x](https://github.com/user-attachments/assets/d084b739-ff1a-4a46-8c18-4ec2fd6a5c53)
It seems working now. Just wait for a few more minutes.

**Comment by Aquariurn** [comment] 2024-10-28 18:27
Update to macOS 15.1, it still don't work
[MacBookPro20,2_tech_info.zip](https://github.com/user-attachments/files/17547250/MacBookPro20.2_tech_info.zip)

**Comment by ChristBKK** [comment] 2024-11-19 23:35
M1 with Sequoia has also problems

**Comment by kleuter** [comment] 2024-11-20 16:52
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/785

**Closed by kleuter** 2024-11-20 16:52 UTC

**Comment by maks2002001** [comment] 2024-11-20 19:58
[Uploading Mac15,6_tech_info.zip…]()

**Comment by weidali** [comment] 2024-12-03 18:36
[![2024-12-03-21-35-20.png](https://i.postimg.cc/vZqPc3tq/2024-12-03-21-35-20.png)](https://postimg.cc/18F0d0Tw)
[Mac15,7_tech_info.zip](https://github.com/user-attachments/files/17997484/Mac15.7_tech_info.zip)

**Comment by maks2002001** [comment] 2024-12-03 18:38
Got the same problem. 

￼
Kind­ regards
Maksymilian Adamczak

**Comment by hellonearth311** [comment] 2025-01-02 22:46
> Now it's working. I don't know did you do smth, but thanks 😊
> 
> UPD(10 minutes later): I have news, when the fans are spinning, they can be controlled as you like, when the fans are at zero, they do not react to anything. So it doesn't work again

thanks so much! this fixed it bro
