### ISSUE TITLE
A system to check information about two or more fans in the menubar

### ISSUE THREAD

**Issue by tars-c** [crystalidea/macs-fan-control#424] opened 2020-10-29 06:18 UTC
Why can I only see information about a fan in one?

My MacBook Pro is using 2 fans
I want to check the rpm for two fans in the MacsFanControl app.
This is very inconvenient compared to other apps.

Please update the menu bar system.

**Comment by kleuter** [comment] 2020-10-30 14:09
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/139, please vote for it

**Closed by kleuter** 2020-10-30 14:09 UTC
Labels: feature request
