### ISSUE TITLE
requires 'Mojave' but can still be launched on 10.13 and 10.12

### ISSUE THREAD

**Issue by core-code** [crystalidea/macs-fan-control#216] opened 2019-10-03 09:20 UTC
although Macs Fan Control 1.5 now officially required Mojave, it can  still be launched on 10.13 and 10.12. 

from the Info.plist of version 1.5.0.3:

```
    <key>LSMinimumSystemVersion</key>
	<string>10.12</string>
```

this should be changed to 10.14 to be in-line with the official requirements

(for some weird reason i can not guess, this has been correctly set to '10.14'  in 1.5.0.2, but not in 1.5.0.0, 1.5.0.1 and 1.5.0.3)

**Comment by kleuter** [comment] 2019-10-03 09:29
I hope that https://bugreports.qt.io/browse/QTBUG-78731 will be fixed soon and the main download will be again available 10.12 and 10.13

Duplicate of https://github.com/crystalidea/macs-fan-control/issues/211

**Closed by kleuter** 2019-10-03 09:29 UTC
