### ISSUE TITLE
User profile reset

### ISSUE THREAD

**Issue by To-Azamat** [crystalidea/macs-fan-control#470] opened 2021-02-23 11:35 UTC
Ok, I tried to modify MFC startup sequence from Task Scheduler. The aim was to somehow make MFC start for every user on PC.

I changed on General tab the option to "Run for all users", entered admin password and restart the PC.
I have MFC running, I can see the process in Task Manager. No icon in system tray, it is ok, but no activity either. I stopped the process and restatred MFC in GUI mode only to find that my custom profile was absent and all fans set to auto.

I tried several other ways to launch MFC like Task Scheduler running MFC on PC start before logons, or using NSSM to launch MFC as a service - the same result: custom profile disappears and fans set to auto. And tho the MFC runs, in thus state it actuallty does nothing.

**Comment by To-Azamat** [comment] 2021-05-08 18:24
Version 1.5.9 seems to correct the bug, now program correctly auto-starts and works. 

But now the program won’t restore default fans settings on exit/reboot.

**Comment by kleuter** [comment] 2021-05-12 08:12
Please create a new issue for that.

Closing this as duplicate of #389

**Closed by kleuter** 2021-05-12 08:12 UTC
Labels: Windows, bug
