### ISSUE TITLE
Fan profiles based on laptop plugged into charger or not

### ISSUE THREAD

**Issue by austinchenCS** [crystalidea/macs-fan-control#613] opened 2022-06-12 02:33 UTC
If the power source is the power adapter, I'd want to be able to select a certain fan profile to spin the fans harder. Once the laptop is unplugged, it would then go back to a default profile (presumably where the fans spin less hard to conserve battery)

**Comment by kleuter** [comment] 2022-06-25 21:00
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/388

**Closed by kleuter** 2022-06-25 21:00 UTC
Labels: feature request
