### ISSUE TITLE
Need help, app not working.

### ISSUE THREAD

**Issue by JovanJaimes** [crystalidea/macs-fan-control#507] opened 2021-05-11 20:16 UTC
OS: Big Sur 11.3.1
MacBook Air 13" 2017

Hi! A week ago my fans started going constant full 100% (no overheating, temperature going from 40º to 65º). Someone recommended me Macs Fan Control but I just can't make it work, can't change the fan speed at all in any configuration. Here is my tech info. If anyone has any idea on how to solve this I would appreciated. 
![Captura de Pantalla 2021-05-11 a la(s) 15 12 21](https://user-images.githubusercontent.com/83881926/117878461-6c1cbe80-b26b-11eb-8d6c-4924f2c84f2d.png)
![Captura de Pantalla 2021-05-11 a la(s) 15 12 30](https://user-images.githubusercontent.com/83881926/117878467-6f17af00-b26b-11eb-818a-068caa21117e.png)
![Captura de Pantalla 2021-05-11 a la(s) 15 15 25](https://user-images.githubusercontent.com/83881926/117878832-cb7ace80-b26b-11eb-8a4d-cbaed1d38f1c.png)

**Comment by JovanJaimes** [comment] 2021-05-11 22:25
Ps. Already tried restarting SMC several times

**Comment by kleuter** [comment] 2021-05-12 07:28
Hi,

1. I don't see you change fan control to manual, it's on Auto.
2. Does connecting a charger change anything?

**Comment by JovanJaimes** [comment] 2021-05-12 07:37
Thanks for answering! 

1. I've already tried constant rpm value and sensor-based value but it still doesn't work.
2. No, connecting a charger doesn't help

**Comment by kleuter** [comment] 2021-05-12 08:00
Unfortunately, I don't currently have a clue why this issue happens on certain computers. 
Broken temperature sensor? Need more info
I'm marking this as duplicate of https://github.com/crystalidea/macs-fan-control/issues/464

**Closed by kleuter** 2021-05-12 08:00 UTC

**Comment by JovanJaimes** [comment] 2021-05-12 08:03
I'll check that out. Thanks anyway
