### ISSUE TITLE
1.4.11 never minimizes on autostart, regardless of pref setting

### ISSUE THREAD

**Issue by rc3105** [crystalidea/macs-fan-control#102] opened 2018-09-07 05:58 UTC
1.4.11 never starts minimized, it ignores the preferences setting and you have to manually "hide to menu bar."

The last version brought up a nag screen and wouldn't start the fans until it was cleared manually.

At least the fans work now but wth is going on?

![screen shot 2018-09-07 at 12 45 47 am](https://user-images.githubusercontent.com/8398571/45200676-7cb54500-b237-11e8-9320-cba0b18606cf.png)

**Comment by kleuter** [comment] 2018-09-10 17:59
Which macOS version are you running? Did you try to toggle this option on/off?

**Comment by kleuter** [comment] 2019-11-08 14:53
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/225

**Closed by kleuter** 2019-11-08 14:53 UTC
