### ISSUE TITLE
Macbook Pro 16 M3 PRO Not support

### ISSUE THREAD

**Issue by october-03** [crystalidea/macs-fan-control#745] opened 2024-04-02 04:48 UTC
Macbook Pro 16 M3 PRO Not working

**Comment by raver119** [comment] 2024-04-02 08:39
On M3 MAX app doesn't work either.

**Comment by HunterAhlquist** [comment] 2024-04-29 19:15
Give this beta version a try if you haven't already, works with my M3 Pro
https://github.com/crystalidea/macs-fan-control/issues/721

**Comment by october-03** [comment] 2024-04-30 04:44
> Give this beta version a try if you haven't already, works with my M3 Pro #721

Thanks

**Comment by october-03** [comment] 2024-04-30 05:41
> Give this beta version a try if you haven't already, works with my M3 Pro #721

I tried this version, but it still doesn't work

**Comment by dewitpj** [comment] 2024-05-12 22:07
I can also test this issue since it affects me too

Thanks

**Comment by kleuter** [comment] 2024-11-20 16:55
Duplicate of https://github.com/crystalidea/macs-fan-control/issues/785

**Closed by kleuter** 2024-11-20 16:55 UTC
Labels: bug
