### ISSUE TITLE
Sensor based Value 0rpm?

### ISSUE THREAD

**Issue by chrizzle1984** [crystalidea/macs-fan-control#180] opened 2019-06-13 09:00 UTC
Hi,

I'm using your programm to lower the idle temperatures from my 2018 mbp 13". At the moment, the computer is on top of an ac outlet so all sensors show about 30Degrees Celsius. If I set the control to "Auto" - all fans are set to 0rpm - if i set them to "sensor based value", they stay at the min rpm value but never at 0rpm.

thx for an explanation, if u know this issue and it can't be corrected or a fix if u didn't know.

cheers
Christoph

**Comment by livelaughriley** [comment] 2019-06-29 02:53
I created an [issue](https://github.com/crystalidea/macs-fan-control/issues/147#issue-396274686) about this before, and an `Improvement` label was added to it.

My guess is that this is the expected behavior, but hopefully it'll be possible to use a sensor based value and have your fans at 0pm in a future release.

**Comment by kleuter** [comment] 2019-10-04 19:37
Duplicate of #147

**Closed by kleuter** 2019-10-04 19:37 UTC
