### ISSUE TITLE
Moderately high CPU usage

### ISSUE THREAD

**Issue by mozeryansky** [crystalidea/macs-fan-control#436] opened 2020-11-22 01:54 UTC
I get a consistent CPU usage between 0.3-1%, it's not much but often it's the the 2nd most usage on my mac. It might be because of the refresh rate or something, is there a way to lower the CPU usage?

<details>
Macs Fan Control 1.5.8.1 [Qt 5.13.2]
MacBookPro13,3
CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz [4 cores]
macOS 10.16.0

Fans:
Left side-min{2160}curr{5260}max{5927}mode{0}
Right side-min{2000}curr{4875}max{5489}mode{0}

SMC sensors:
TA0V () - 23.3438, 23.3438
TB0T (Battery Max) - 34.1992, 34.1992
TB1T (Battery Sensor 1) - 32.5977, 32.5977
TB2T (Battery Sensor 2) - 34.1992, 34.1992
TBXT () - 34.1992, 34.1992
TC0E () - 72.0508, 72.0508
TC0F () - 73.8281, 73.8281
TC0P (CPU Proximity) - 58.1875, 58.1875
TC1C (CPU Core 1) - 68, 68
TC2C (CPU Core 2) - 70, 70
TC3C (CPU Core 3) - 68, 68
TC4C (CPU Core 4) - 63, 63
TCGC (GPU PECI) - 65, 65 [H]
TCMc () - 128, 128
TCSA () - 71, 71
TCTD () - 0.121094, 0.121094
TCXC (CPU PECI) - 71.7813, 71.7813
TG0D (GPU Diode) - 68.125, 68.125 [H]
TG0F () - 67.668, 67.668
TG0P (GPU Proximity) - 63.0625, 63.0625
TGDD (GPU Diode 2) - 62, 62
TGVP () - 57.375, 57.375
TH0A (Apple SSD) - 30.625, 30.625 [H]
TH0B () - 29.5, 29.5
TH0C () - 31.25, 31.25
TH0F () - 210.25, 210.25
TH0R () - 210.25, 210.25
TH0a () - 30.625, 30.625
TH0b () - 29.5, 29.5
TH0c () - 31.25, 31.25
TH0x () - 129, 129
TM0P (Memory Proximity) - 58.5, 58.5
TPCD (Platform Controller Hub Die) - 43, 43
TTLD () - 59.4375, 59.4375
TTRD () - 33.0625, 33.0625
TW0P (Airport Card) - 58.8125, 58.8125
TaLC () - 35.9375, 35.9375
TaRC () - 34.75, 34.75
Th1H (Heatsink Proximity) - 64.5, 64.5
Th2H () - 61.75, 61.75
Ts0P (Palm Rest) - 32.1875, 32.1875
Ts0S () - 43.2656, 43.2656
Ts1P () - 27.75, 27.75
Ts1S () - 43.9063, 43.9063
Ts2S () - 42.3672, 42.3672

GPUs:
Intel HD Graphics 530 - 51
AMD Radeon Pro 460 - 0

Disk drives:
APPLE SSD SM0512L - 26

Path: /Applications/Macs Fan Control.app/Contents/MacOS/Macs Fan Control

Log:

[2020-11-20 17:04:28:699] [thread 3603] [app.cpp#280] Macs Fan Control 1.5.8.1
[2020-11-20 17:04:28:699] [thread 3603] [app.cpp#281] macOS 10.16.0
[2020-11-20 17:04:28:699] [thread 3603] [app.cpp#282] MacBookPro13,3
[2020-11-20 17:04:28:699] [thread 3603] [app.cpp#283] Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz [4 cores]
[2020-11-20 17:04:28:699] [thread 3603] [app.cpp#284] Qt 5.13.2
[2020-11-20 17:04:28:700] [thread 3603] [app_mac.mm#135] Helper installed, version - 1.0.1
[2020-11-20 17:04:28:700] [thread 3603] [app_mac.mm#150] Current version - 1.0.1
[2020-11-20 17:04:28:701] [thread 3603] [Platform_mac_smcwrite.mm#79] open XPC connection to com.crystalidea.macsfancontrol.smcwrite
[2020-11-20 17:04:29:310] [thread 3603] [Platform_mac_smcwrite.mm#150] process_command_open: OK
[2020-11-20 17:04:29:311] [thread 3603] [Service.cpp#87] detectSmcFanKeySize KeyType fpe2
[2020-11-20 17:04:29:311] [thread 3603] [Service.cpp#88] detectSmcFanKeySize KeyLen 2
[2020-11-20 17:04:29:815] [thread 4329] [FanControl.cpp#179] initialLoadThread
[2020-11-20 17:04:29:815] [thread 4329] [FanControl.cpp#125] QFanControl::loadFansFromSMC
[2020-11-20 17:04:29:815] [thread 4329] [FanControl.cpp#131] Fans count - 2
[2020-11-20 17:04:29:816] [thread 4329] [FanControl.cpp#148] Fan 0: Left side
[2020-11-20 17:04:29:818] [thread 4329] [FanControl.cpp#148] Fan 1: Right side
[2020-11-20 17:04:29:819] [thread 4329] [FanControl.cpp#59] checkFansControlModeFromSMC
[2020-11-20 17:04:29:819] [thread 4329] [TempSensorProvider.cpp#47] TempSensorDisk::loadAvailableSensors
[2020-11-20 17:04:29:820] [thread 4329] [Service.cpp#56] getSMCKeysCount: 2248343552 902
[2020-11-20 17:04:29:858] [thread 4329] [Provider_mac.mm#18] Device hold Intel(R) HD Graphics 530
[2020-11-20 17:04:29:860] [thread 4329] [Provider_mac.mm#18] Device hold AMD Radeon Pro 460
[2020-11-20 17:04:29:863] [thread 4329] [Provider_mac_watcher.mm#84] eGPUWatcher started
[2020-11-20 17:04:29:864] [thread 4329] [TempSensorGPU.cpp#74] Integrated GPU: Intel HD Graphics 530, matching SMC - yes
[2020-11-20 17:04:29:864] [thread 4329] [TempSensorGPU.cpp#91] Discrete GPU: GPU AMD Radeon Pro 460, matching SMC - yes
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#65] TemperatureSensorSMC::loadAvailableSensors
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#32] Using TC1C sensor for CPU Core average
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#32] Using TC2C sensor for CPU Core average
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#32] Using TC3C sensor for CPU Core average
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#32] Using TC4C sensor for CPU Core average
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#82] InitialLoadThread: number of supported SMC sensors: 20
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#83] InitialLoadThread: number of supported DISK sensors: 1
[2020-11-20 17:04:29:871] [thread 4329] [TempSensorProvider.cpp#84] InitialLoadThread: number of supported GPU sensors: 2
[2020-11-20 17:04:29:877] [thread 4329] [Platform_mac_smcwrite.mm#251] process_command_write: SMCWriteKey FS!  0000 OK
[2020-11-20 17:04:29:877] [thread 4329] [Service.cpp#478] Set fans mode 0
[2020-11-20 17:04:29:907] [thread 4333] [TempSensorGPU.cpp#27] Reading of GPU temperature failed
[2020-11-20 17:04:29:907] [thread 4333] [TempSensorGPU.cpp#32] Trying SMC instead
[2020-11-20 17:16:18:194] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC4C with value of 128.0
[2020-11-20 17:25:33:256] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC4C with value of 128.0
[2020-11-20 17:27:26:124] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC3C with value of 128.0
[2020-11-20 17:39:17:757] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC2C with value of 128.0
[2020-11-20 17:40:57:093] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 17:40:58:599] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 17:41:00:101] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 17:41:01:609] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 17:41:03:116] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 17:41:04:623] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 17:41:06:130] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 17:41:07:637] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC1C with value of 128.0
[2020-11-20 18:01:07:307] [thread 4333] [Service.cpp#647] getTemperature - skipping sensor TC4C with value of 128.0
[2020-11-20 18:16:38:552] [thread 3603] [FanControl.cpp#672] slotEnteringSleepMode
[2020-11-20 18:16:38:800] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:40:300] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:41:801] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:43:297] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:44:803] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:46:307] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:47:814] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:49:322] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:50:820] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:52:325] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:53:833] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:55:342] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:56:843] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 18:16:58:343] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:16:53:001] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:16:55:032] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:16:56:530] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:16:58:029] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:16:59:536] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:01:042] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:02:551] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:04:059] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:05:568] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:07:077] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:08:587] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:10:096] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 20:17:11:605] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 21:17:02:002] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 21:17:04:601] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 21:17:06:105] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 21:17:07:615] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 21:49:03:238] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 21:49:04:807] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-20 21:49:04:890] [thread 3603] [FanControl.cpp#679] slotWakeUp
[2020-11-21 06:22:09:503] [thread 3603] [FanControl.cpp#672] slotEnteringSleepMode
[2020-11-21 06:22:10:461] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:11:968] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:13:479] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:14:979] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:16:480] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:17:980] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:19:481] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:20:981] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:22:482] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:23:982] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:25:483] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:26:983] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 06:22:28:484] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:24:001] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:26:748] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:28:250] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:29:751] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:31:262] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:32:764] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:34:269] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:35:775] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:37:284] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:38:784] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:40:290] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:41:794] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:43:302] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:44:803] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 08:22:46:309] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:42:086] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:45:098] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:46:600] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:48:102] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:49:608] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:51:108] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:52:609] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:54:111] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:55:611] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:57:112] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 10:22:58:612] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:22:57:083] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:00:146] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:01:646] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:03:147] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:04:657] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:06:159] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:07:666] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:09:175] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:10:679] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:12:179] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:13:680] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:15:185] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 12:23:16:692] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:12:133] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:14:805] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:16:305] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:17:814] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:19:314] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:20:815] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:22:320] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:23:820] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:25:321] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:26:821] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:28:331] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:29:835] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 14:23:31:344] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 15:26:54:172] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 15:26:55:801] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 15:26:57:698] [thread 4334] [FanControl.cpp#554] ControlFanSpeedThread: sleep mode
[2020-11-21 15:26:58:079] [thread 3603] [FanControl.cpp#679] slotWakeUp
[2020-11-21 20:52:21:904] [thread 3603] [Service.cpp#647] getTemperature - skipping sensor TCMc with value of 128.0
[2020-11-21 20:52:21:908] [thread 3603] [Service.cpp#647] getTemperature - skipping sensor TH0F with value of 210.25
[2020-11-21 20:52:21:908] [thread 3603] [Service.cpp#647] getTemperature - skipping sensor TH0R with value of 210.25
[2020-11-21 20:52:21:910] [thread 3603] [Service.cpp#647] getTemperature - skipping sensor TH0x with value of 129.0

<img width="933" alt="Screen Shot 2020-11-21 at 8 52 36 PM" src="https://user-images.githubusercontent.com/3287719/99891771-86ba9700-2c3b-11eb-94eb-7abf333016d0.png">

</details>

**Comment by kleuter** [comment] 2021-01-30 11:31
> is there a way to lower the CPU usage

Try turning off displaying temperatures of HDD/SSD drives.

**Comment by mozeryansky** [comment] 2021-01-31 01:46
> Try turning off displaying temperatures of HDD/SSD drives.

I have the temperature set for the CPU (Average) and I like to look at the temp which is why I have this app the first place. Could the refresh rate be changed to be every 5s instead of every 1s? I'm not sure why this app would require any CPU usage at all.

**Comment by kleuter** [comment] 2021-05-12 08:35
Duplicate of #55

**Closed by kleuter** 2021-05-12 08:35 UTC
Labels: bug
